#!/bin/sh

rm -rf libltdl

if test "x${LIBTOOLIZE}" = "x" ; then
  LIBTOOLIZE="libtoolize --ltdl"
else
  LIBTOOLIZE="$LIBTOOLIZE --ltdl"
fi
export LIBTOOLIZE

cat config/*.m4 > acinclude.m4

autoreconf -s -i $*
