////
//
//
//     (C) Copyright 2003  ATI Research, Inc.    All rights reserved  
//     
//      James Percy, August 2003.
//
////

#include <stdio.h>
#include <stdlib.h>
#include "extensions.h"
#include <GL/glx.h>

//
// ATI_uber_buffer
//
PFNGLALLOCMEM3DATIPROC           glAllocMem3DATI;
PFNGLALLOCMEM2DATIPROC           glAllocMem2DATI;
PFNGLALLOCMEM1DATIPROC           glAllocMem1DATI;
PFNGLBINDFRAMEBUFFERATIPROC      glBindFramebufferATI;
PFNGLCREATEFRAMEBUFFERATIPROC    glCreateFramebufferATI;
PFNGLDELETEFRAMEBUFFERATIPROC    glDeleteFramebufferATI;
PFNGLDELETEMEMATIPROC            glDeleteMemATI;
PFNGLGETMEMPROPERTYATIPROC       glGetMemPropertyATI;
PFNGLGETMEMATIPROC               glGetMemATI;
PFNGLCOPYMEMIMAGE2DATIPROC       glCopyMemImage2DATI;
PFNGLCOPYMEMIMAGE1DATIPROC       glCopyMemImage1DATI;
PFNGLMEMSUBIMAGE3DATIPROC        glMemSubImage3DATI;
PFNGLMEMSUBIMAGE2DATIPROC        glMemSubImage2DATI;
PFNGLMEMSUBIMAGE1DATIPROC        glMemSubImage1DATI;
PFNGLCOPYMEMSUBIMAGE2DATIPROC    glCopyMemSubImage2DATI;
PFNGLCOPYMEMSUBIMAGE1DATIPROC    glCopyMemSubImage1DATI;
PFNGLMEMCOPY3DATIPROC            glMemCopy3DATI;
PFNGLMEMCOPY2DATIPROC            glMemCopy2DATI;
PFNGLMEMCOPY1DATIPROC            glMemCopy1DATI;
PFNGLATTACHMEMATIPROC              glAttachMemATI;
PFNGLVERTEXARRAYMEMATIPROC       glVertexArrayMemATI;
PFNGLDRAWELEMENTARRAYATIPROC     glDrawElementArrayATI;
PFNGLGETMEMINFOLOGATIPROC    glGetMemInfoLogATI;

//
// ARB_fragment_program
//
PFNGLPROGRAMSTRINGARBPROC				glProgramStringARB;
PFNGLBINDPROGRAMARBPROC					glBindProgramARB;
PFNGLDELETEPROGRAMSARBPROC				glDeleteProgramsARB;
PFNGLGENPROGRAMSARBPROC					glGenProgramsARB;
PFNGLPROGRAMENVPARAMETER4FARBPROC		glProgramEnvParameter4fARB;
PFNGLPROGRAMENVPARAMETER4DARBPROC		glProgramEnvParameter4dARB;
PFNGLPROGRAMENVPARAMETER4FVARBPROC		glProgramEnvParameter4fvARB;
PFNGLPROGRAMENVPARAMETER4DVARBPROC		glProgramEnvParameter4dvARB;
PFNGLPROGRAMLOCALPARAMETER4FARBPROC		glProgramLocalParameter4fARB;
PFNGLPROGRAMLOCALPARAMETER4DARBPROC		glProgramLocalParameter4dARB;
PFNGLPROGRAMLOCALPARAMETER4FVARBPROC	glProgramLocalParameter4fvARB;
PFNGLPROGRAMLOCALPARAMETER4DVARBPROC	glProgramLocalParameter4dvARB;
PFNGLGETPROGRAMENVPARAMETERFVARBPROC	glGetProgramEnvParameterfvARB;
PFNGLGETPROGRAMENVPARAMETERDVARBPROC	glGetProgramEnvParameterdvARB;
PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC	glGetProgramLocalParameterfvARB;
PFNGLGETPROGRAMLOCALPARAMETERDVARBPROC	glGetProgramLocalParameterdvARB;
PFNGLGETPROGRAMIVARBPROC				glGetProgramivARB;
PFNGLGETPROGRAMSTRINGARBPROC			glGetProgramStringARB;
PFNGLISPROGRAMARBPROC					glIsProgramARB;
PFNGLDRAWBUFFERS						glDrawBuffersATI;

//
// ARB_vertex_buffer_object
//
PFNGLBINDBUFFERARBPROC           glBindBufferARB;
PFNGLDELETEBUFFERSARBPROC        glDeleteBuffersARB;
PFNGLGENBUFFERSARBPROC           glGenBuffersARB;
PFNGLISBUFFERARBPROC             glIsBufferARB;
PFNGLBUFFERDATAARBPROC           glBufferDataARB;
PFNGLBUFFERSUBDATAARBPROC        glBuffersSubDataARB;
PFNGLGETBUFFERSUBDATAARBPROC     glGetBuffersSubDataARB;
PFNGLMAPBUFFERARBPROC            glMapBufferARB;
PFNGLUNMAPBUFFERARBPROC          glUnMapBufferARB;
PFNGLGETBUFFERPARAMETERIVARBPROC glGetBufferParameterivARB;
PFNGLGETBUFFERPOINTERVARBPROC    glGetBufferPointervARB;

//
// ARB_multitexture
//
#if 1
PFNGLCLIENTACTIVETEXTUREARBPROC			glClientActiveTextureARB;
PFNGLACTIVETEXTUREARBPROC				glActiveTextureARB;
PFNGLMULTITEXCOORD4FVARBPROC			glMultiTexCoord4fvARB;
PFNGLMULTITEXCOORD4FARBPROC				glMultiTexCoord4fARB;
PFNGLMULTITEXCOORD3FVARBPROC			glMultiTexCoord3fvARB;
PFNGLMULTITEXCOORD3FARBPROC				glMultiTexCoord3fARB;
PFNGLMULTITEXCOORD2FVARBPROC			glMultiTexCoord2fvARB;
PFNGLMULTITEXCOORD2FARBPROC				glMultiTexCoord2fARB;
PFNGLMULTITEXCOORD1FARBPROC				glMultiTexCoord1fARB;
PFNGLMULTITEXCOORD3DVARBPROC			glMultiTexCoord3dvARB;
PFNGLMULTITEXCOORD3DARBPROC		    	glMultiTexCoord3dARB;
PFNGLMULTITEXCOORD2DVARBPROC			glMultiTexCoord2dvARB;
PFNGLMULTITEXCOORD2DARBPROC				glMultiTexCoord2dARB;
PFNGLMULTITEXCOORD1DARBPROC				glMultiTexCoord1dARB;
#endif

//
// ATI_vertex_array_object
//
PFNGLNEWOBJECTBUFFERATIPROC      glNewObjectBufferATI;
PFNGLISOBJECTBUFFERATIPROC       glIsObjectBufferATI;
PFNGLUPDATEOBJECTBUFFERATIPROC   glUpdateObjectBufferATI;
PFNGLGETOBJECTBUFFERFVATIPROC    glGetObjectBufferfvATI;
PFNGLGETOBJECTBUFFERIVATIPROC    glGetObjectBufferivATI;
PFNGLFREEOBJECTBUFFERATIPROC     glDeleteObjectBufferATI;
PFNGLARRAYOBJECTATIPROC          glArrayObjectATI;
PFNGLGETARRAYOBJECTFVATIPROC     glGetArrayObjectfvATI;
PFNGLGETARRAYOBJECTIVATIPROC     glGetArrayObjectivATI;
PFNGLVARIANTARRAYOBJECTATIPROC   glVariantArrayObjectATI;
PFNGLGETVARIANTARRAYOBJECTFVATIPROC  glGetVariantArrayObjectfvATI;
PFNGLGETVARIANTARRAYOBJECTIVATIPROC  glGetVariantArrayObjectivATI;

#if 0
//
// WGL_ARB_pbuffer
//
PFNWGLCREATEPBUFFERARBPROC               wglCreatePbufferARB;
PFNWGLGETPBUFFERDCARBPROC                wglGetPbufferDCARB;
PFNWGLRELEASEPBUFFERDCARBPROC            wglReleasePbufferDCARB;
PFNWGLDESTROYPBUFFERARBPROC              wglDestroyPbufferARB;
PFNWGLQUERYPBUFFERARBPROC                wglQueryPbufferARB;
PFNWGLMAKECONTEXTCURRENTARBPROC			wglMakeContextCurrentARB;

//
// WGL_ARB_pixel_format
//
PFNWGLGETPIXELFORMATATTRIBIVARBPROC      wglGetPixelFormatAttribivARB;
PFNWGLGETPIXELFORMATATTRIBFVARBPROC      wglGetPixelFormatAttribfvARB;
PFNWGLCHOOSEPIXELFORMATARBPROC           wglChoosePixelFormatARB;

//
// ARB_render_texture.
//
PFNWGLBINDTEXIMAGEARBPROC                wglBindTexImageARB;
PFNWGLRELEASETEXIMAGEARBPROC             wglReleaseTexImageARB;
PFNWGLSETPBUFFERATTRIBARBPROC            wglSetPbufferAttribARB;
#endif

static GLboolean
IsExtSupported(const char *ext)
{
    const char *exts;
    const char *start;
    const char *where, *terminator;

    where = strchr(ext, ' ');

    if ((where != NULL) || (*ext == '\0'))
    {
        return GL_FALSE;
    }

    exts = (const char*) glGetString(GL_EXTENSIONS);
    start = exts;

    for ( ; ; )
    {
        where = strstr(start, ext);

        if (!where)
        {
            break;
        }

        terminator = where + strlen(ext);

        if ((where == start) || (*(where - 1) == ' '))
        {
            if ((*terminator == ' ') || (*terminator == '\0'))
            {
                return GL_TRUE;
            }
        }

        start = terminator;
    }

    return GL_FALSE;
}

#ifdef EXIT_ON_MISSING_EXTENSION
#define GET_PROC(x, T)                                 \
{                                                   \
    x = (T) glXGetProcAddressARB(#x);              \
    if (x == NULL)                                  \
    {                                               \
        printf("Extension %s not found.\n", #x);    \
		exit(-1);                                   \
    }                                               \
}
#else
#define GET_PROC(x, T)                                 \
{                                                   \
    x = (T) glXGetProcAddressARB(#x);              \
}
#endif


GLboolean
InitExtensions(void)
{
    // GL_ATI_uber_buffers

/* extension string not yet exported
    if (!IsExtSupported("GL_ATI_uber_buffers"))
    {
        fprintf(stderr, "InitExtensions: GL_ATI_uber_buffers not supported\n");
        return GL_FALSE;
    }
*/

    GET_PROC(glAllocMem3DATI, PFNGLALLOCMEM3DATIPROC);
    GET_PROC(glAllocMem2DATI, PFNGLALLOCMEM2DATIPROC);
    GET_PROC(glAllocMem1DATI, PFNGLALLOCMEM1DATIPROC);
    GET_PROC(glCreateFramebufferATI, PFNGLCREATEFRAMEBUFFERATIPROC);
    GET_PROC(glDeleteFramebufferATI, PFNGLDELETEFRAMEBUFFERATIPROC);
    GET_PROC(glBindFramebufferATI, PFNGLBINDFRAMEBUFFERATIPROC);
    GET_PROC(glDeleteMemATI, PFNGLDELETEMEMATIPROC);
    GET_PROC(glGetMemPropertyATI, PFNGLGETMEMPROPERTYATIPROC);
    GET_PROC(glGetMemATI, PFNGLGETMEMATIPROC);
    GET_PROC(glCopyMemImage2DATI, PFNGLCOPYMEMIMAGE2DATIPROC);
    GET_PROC(glCopyMemImage1DATI, PFNGLCOPYMEMIMAGE1DATIPROC);
    GET_PROC(glMemSubImage3DATI, PFNGLMEMSUBIMAGE3DATIPROC);
    GET_PROC(glMemSubImage2DATI, PFNGLMEMSUBIMAGE2DATIPROC);
    GET_PROC(glMemSubImage1DATI, PFNGLMEMSUBIMAGE1DATIPROC);
    GET_PROC(glCopyMemSubImage2DATI, PFNGLCOPYMEMSUBIMAGE2DATIPROC);
    GET_PROC(glCopyMemSubImage1DATI, PFNGLCOPYMEMSUBIMAGE1DATIPROC);
    GET_PROC(glMemCopy3DATI, PFNGLMEMCOPY3DATIPROC);
    GET_PROC(glMemCopy2DATI, PFNGLMEMCOPY2DATIPROC);
    GET_PROC(glMemCopy1DATI, PFNGLMEMCOPY1DATIPROC);
    GET_PROC(glAttachMemATI, PFNGLATTACHMEMATIPROC);
    GET_PROC(glVertexArrayMemATI, PFNGLVERTEXARRAYMEMATIPROC);
    GET_PROC(glDrawElementArrayATI, PFNGLDRAWELEMENTARRAYATIPROC);
    GET_PROC(glGetMemInfoLogATI, PFNGLGETMEMINFOLOGATIPROC);

    GET_PROC(glProgramStringARB, PFNGLPROGRAMSTRINGARBPROC);
    GET_PROC(glBindProgramARB, PFNGLBINDPROGRAMARBPROC);
    GET_PROC(glDeleteProgramsARB, PFNGLDELETEPROGRAMSARBPROC);
    GET_PROC(glGenProgramsARB, PFNGLGENPROGRAMSARBPROC);
    GET_PROC(glProgramEnvParameter4fARB, PFNGLPROGRAMENVPARAMETER4FARBPROC);
    GET_PROC(glProgramEnvParameter4dARB, PFNGLPROGRAMENVPARAMETER4DARBPROC);
    GET_PROC(glProgramEnvParameter4fvARB, PFNGLPROGRAMENVPARAMETER4FVARBPROC);
    GET_PROC(glProgramEnvParameter4dvARB, PFNGLPROGRAMENVPARAMETER4DVARBPROC);
    GET_PROC(glProgramLocalParameter4fARB, PFNGLPROGRAMLOCALPARAMETER4FARBPROC);
    GET_PROC(glProgramLocalParameter4dARB, PFNGLPROGRAMLOCALPARAMETER4DARBPROC);
    GET_PROC(glProgramLocalParameter4fvARB, PFNGLPROGRAMLOCALPARAMETER4FVARBPROC);
    GET_PROC(glProgramLocalParameter4dvARB, PFNGLPROGRAMLOCALPARAMETER4DVARBPROC);
    GET_PROC(glGetProgramEnvParameterfvARB, PFNGLGETPROGRAMENVPARAMETERFVARBPROC);
    GET_PROC(glGetProgramEnvParameterdvARB, PFNGLGETPROGRAMENVPARAMETERDVARBPROC);
    GET_PROC(glGetProgramLocalParameterfvARB, PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC);
    GET_PROC(glGetProgramLocalParameterdvARB, PFNGLGETPROGRAMLOCALPARAMETERDVARBPROC);
    GET_PROC(glGetProgramivARB, PFNGLGETPROGRAMIVARBPROC);
    GET_PROC(glGetProgramStringARB, PFNGLGETPROGRAMSTRINGARBPROC);
    GET_PROC(glIsProgramARB, PFNGLISPROGRAMARBPROC);
	GET_PROC(glDrawBuffersATI, PFNGLDRAWBUFFERSATIPROC);

    GET_PROC(glNewObjectBufferATI, PFNGLNEWOBJECTBUFFERATIPROC);
    GET_PROC(glIsObjectBufferATI, PFNGLISOBJECTBUFFERATIPROC);
    GET_PROC(glUpdateObjectBufferATI, PFNGLUPDATEOBJECTBUFFERATIPROC);
    GET_PROC(glGetObjectBufferfvATI, PFNGLGETOBJECTBUFFERFVATIPROC);
    GET_PROC(glGetObjectBufferivATI, PFNGLGETOBJECTBUFFERIVATIPROC);
    GET_PROC(glDeleteObjectBufferATI, PFNGLFREEOBJECTBUFFERATIPROC);
    GET_PROC(glArrayObjectATI, PFNGLARRAYOBJECTATIPROC);
    GET_PROC(glGetArrayObjectfvATI, PFNGLGETARRAYOBJECTFVATIPROC);
    GET_PROC(glGetArrayObjectivATI, PFNGLGETARRAYOBJECTIVATIPROC);
    GET_PROC(glVariantArrayObjectATI, PFNGLVARIANTARRAYOBJECTATIPROC);
    GET_PROC(glGetVariantArrayObjectfvATI, PFNGLGETVARIANTARRAYOBJECTFVATIPROC);
    GET_PROC(glGetVariantArrayObjectivATI, PFNGLGETVARIANTARRAYOBJECTIVATIPROC);

    GET_PROC(glBindBufferARB, PFNGLBINDBUFFERARBPROC);
    GET_PROC(glDeleteBuffersARB, PFNGLDELETEBUFFERSARBPROC);
    GET_PROC(glGenBuffersARB, PFNGLGENBUFFERSARBPROC);
    GET_PROC(glIsBufferARB, PFNGLISBUFFERARBPROC);
    GET_PROC(glBufferDataARB, PFNGLBUFFERDATAARBPROC);
    GET_PROC(glBuffersSubDataARB, PFNGLBUFFERSUBDATAARBPROC);
    GET_PROC(glGetBuffersSubDataARB, PFNGLGETBUFFERSUBDATAARBPROC);
    GET_PROC(glMapBufferARB, PFNGLMAPBUFFERARBPROC);
    GET_PROC(glUnMapBufferARB, PFNGLUNMAPBUFFERARBPROC);
    GET_PROC(glGetBufferParameterivARB, PFNGLGETBUFFERPARAMETERIVARBPROC);
    GET_PROC(glGetBufferParameterivARB, PFNGLGETBUFFERPARAMETERIVARBPROC);
    GET_PROC(glGetBufferPointervARB, PFNGLGETBUFFERPOINTERVARBPROC);


    GET_PROC(glClientActiveTextureARB, PFNGLCLIENTACTIVETEXTUREARBPROC);
    GET_PROC(glActiveTextureARB, PFNGLACTIVETEXTUREARBPROC);
    GET_PROC(glMultiTexCoord4fARB, PFNGLMULTITEXCOORD4FARBPROC);
    GET_PROC(glMultiTexCoord4fvARB, PFNGLMULTITEXCOORD4FVARBPROC);
    GET_PROC(glMultiTexCoord3fvARB, PFNGLMULTITEXCOORD3FVARBPROC);
    GET_PROC(glMultiTexCoord3fARB, PFNGLMULTITEXCOORD3FARBPROC );
    GET_PROC(glMultiTexCoord2fvARB, PFNGLMULTITEXCOORD2FVARBPROC);
    GET_PROC(glMultiTexCoord2fARB, PFNGLMULTITEXCOORD2FARBPROC);
    GET_PROC(glMultiTexCoord1fARB,PFNGLMULTITEXCOORD1FARBPROC );
    GET_PROC(glMultiTexCoord3dvARB,PFNGLMULTITEXCOORD3DVARBPROC );
    GET_PROC(glMultiTexCoord3dARB,PFNGLMULTITEXCOORD3DARBPROC );
    GET_PROC(glMultiTexCoord2dvARB,PFNGLMULTITEXCOORD2DVARBPROC );
    GET_PROC(glMultiTexCoord2dARB,PFNGLMULTITEXCOORD2DARBPROC );
    GET_PROC(glMultiTexCoord1dARB,PFNGLMULTITEXCOORD1DARBPROC );

#if 0
    GET_PROC(wglCreatePbufferARB);
    GET_PROC(wglGetPbufferDCARB);
    GET_PROC(wglReleasePbufferDCARB);
    GET_PROC(wglDestroyPbufferARB);
    GET_PROC(wglQueryPbufferARB);
    GET_PROC(wglMakeContextCurrentARB);

    GET_PROC(wglGetPixelFormatAttribivARB);
    GET_PROC(wglGetPixelFormatAttribfvARB);
    GET_PROC(wglChoosePixelFormatARB);

    GET_PROC(wglBindTexImageARB);
    GET_PROC(wglReleaseTexImageARB);
    GET_PROC(wglSetPbufferAttribARB);
#endif

    return GL_TRUE;
}
