#!/bin/bash

echo "Running $1 $2 $3 $4 $5 $6 "
../shell $2 $3 $4 $5 $6 < $1 >& $1_$2_$3_$4_$5_$6.out
mv *.png *.out *.ps *.dot *.vars results/
cd results/png
rm *.png

for i in ../*.png; do
  ln -s "$i" .
done
