#!/bin/sh

rm -rf libltdl

echo "You may ignore messages about updating aclocal.m4."

if test "x${LIBTOOLIZE}" = "x" ; then
  LIBTOOLIZE="libtoolize --ltdl"
else
  LIBTOOLIZE="$LIBTOOLIZE --ltdl"
fi
export LIBTOOLIZE

if test "x${AUTOMAKE}" = "x" ; then
  AUTOMAKE=automake-1.7
fi
export AUTOMAKE
if test "x${ACLOCAL}" = "x" ; then
  ACLOCAL=aclocal-1.7
fi
export ACLOCAL

# ltdl seems to require these now...
cp /usr/share/libtool/libtool.m4 .
cp /usr/share/libtool/ltdl.m4 .

cat config/*.m4 > acinclude.m4

autoreconf -s -i $*
