// WARNING - DO NOT EDIT THIS FILE:
// This file was automatically generated from scripts/Color.hpp.py.
// If you wish to change it, edit that file instead.
//
// ---
//
// Sh: A GPU metaprogramming language.
//
// Copyright 2003-2006 Serious Hack Inc.
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
// MA  02110-1301, USA
//////////////////////////////////////////////////////////////////////////////

#ifndef SHSHCOLOR_HPP
#define SHSHCOLOR_HPP

#include "Attrib.hpp"
namespace SH {

/** An n-color.
 * 
 *
 */

typedef Attrib<1, INPUT, FracUShort, COLOR> InputColor1fus;
typedef Attrib<1, OUTPUT, FracUShort, COLOR> OutputColor1fus;
typedef Attrib<1, INOUT, FracUShort, COLOR> InOutColor1fus;
typedef Attrib<1, TEMP, FracUShort, COLOR> Color1fus;
typedef Attrib<1, CONST, FracUShort, COLOR> ConstColor1fus;
typedef Attrib<2, INPUT, FracUShort, COLOR> InputColor2fus;
typedef Attrib<2, OUTPUT, FracUShort, COLOR> OutputColor2fus;
typedef Attrib<2, INOUT, FracUShort, COLOR> InOutColor2fus;
typedef Attrib<2, TEMP, FracUShort, COLOR> Color2fus;
typedef Attrib<2, CONST, FracUShort, COLOR> ConstColor2fus;
typedef Attrib<3, INPUT, FracUShort, COLOR> InputColor3fus;
typedef Attrib<3, OUTPUT, FracUShort, COLOR> OutputColor3fus;
typedef Attrib<3, INOUT, FracUShort, COLOR> InOutColor3fus;
typedef Attrib<3, TEMP, FracUShort, COLOR> Color3fus;
typedef Attrib<3, CONST, FracUShort, COLOR> ConstColor3fus;
typedef Attrib<4, INPUT, FracUShort, COLOR> InputColor4fus;
typedef Attrib<4, OUTPUT, FracUShort, COLOR> OutputColor4fus;
typedef Attrib<4, INOUT, FracUShort, COLOR> InOutColor4fus;
typedef Attrib<4, TEMP, FracUShort, COLOR> Color4fus;
typedef Attrib<4, CONST, FracUShort, COLOR> ConstColor4fus;


typedef Attrib<1, INPUT, short, COLOR> InputColor1s;
typedef Attrib<1, OUTPUT, short, COLOR> OutputColor1s;
typedef Attrib<1, INOUT, short, COLOR> InOutColor1s;
typedef Attrib<1, TEMP, short, COLOR> Color1s;
typedef Attrib<1, CONST, short, COLOR> ConstColor1s;
typedef Attrib<2, INPUT, short, COLOR> InputColor2s;
typedef Attrib<2, OUTPUT, short, COLOR> OutputColor2s;
typedef Attrib<2, INOUT, short, COLOR> InOutColor2s;
typedef Attrib<2, TEMP, short, COLOR> Color2s;
typedef Attrib<2, CONST, short, COLOR> ConstColor2s;
typedef Attrib<3, INPUT, short, COLOR> InputColor3s;
typedef Attrib<3, OUTPUT, short, COLOR> OutputColor3s;
typedef Attrib<3, INOUT, short, COLOR> InOutColor3s;
typedef Attrib<3, TEMP, short, COLOR> Color3s;
typedef Attrib<3, CONST, short, COLOR> ConstColor3s;
typedef Attrib<4, INPUT, short, COLOR> InputColor4s;
typedef Attrib<4, OUTPUT, short, COLOR> OutputColor4s;
typedef Attrib<4, INOUT, short, COLOR> InOutColor4s;
typedef Attrib<4, TEMP, short, COLOR> Color4s;
typedef Attrib<4, CONST, short, COLOR> ConstColor4s;


typedef Attrib<1, INPUT, FracUInt, COLOR> InputColor1fui;
typedef Attrib<1, OUTPUT, FracUInt, COLOR> OutputColor1fui;
typedef Attrib<1, INOUT, FracUInt, COLOR> InOutColor1fui;
typedef Attrib<1, TEMP, FracUInt, COLOR> Color1fui;
typedef Attrib<1, CONST, FracUInt, COLOR> ConstColor1fui;
typedef Attrib<2, INPUT, FracUInt, COLOR> InputColor2fui;
typedef Attrib<2, OUTPUT, FracUInt, COLOR> OutputColor2fui;
typedef Attrib<2, INOUT, FracUInt, COLOR> InOutColor2fui;
typedef Attrib<2, TEMP, FracUInt, COLOR> Color2fui;
typedef Attrib<2, CONST, FracUInt, COLOR> ConstColor2fui;
typedef Attrib<3, INPUT, FracUInt, COLOR> InputColor3fui;
typedef Attrib<3, OUTPUT, FracUInt, COLOR> OutputColor3fui;
typedef Attrib<3, INOUT, FracUInt, COLOR> InOutColor3fui;
typedef Attrib<3, TEMP, FracUInt, COLOR> Color3fui;
typedef Attrib<3, CONST, FracUInt, COLOR> ConstColor3fui;
typedef Attrib<4, INPUT, FracUInt, COLOR> InputColor4fui;
typedef Attrib<4, OUTPUT, FracUInt, COLOR> OutputColor4fui;
typedef Attrib<4, INOUT, FracUInt, COLOR> InOutColor4fui;
typedef Attrib<4, TEMP, FracUInt, COLOR> Color4fui;
typedef Attrib<4, CONST, FracUInt, COLOR> ConstColor4fui;


typedef Attrib<1, INPUT, FracByte, COLOR> InputColor1fb;
typedef Attrib<1, OUTPUT, FracByte, COLOR> OutputColor1fb;
typedef Attrib<1, INOUT, FracByte, COLOR> InOutColor1fb;
typedef Attrib<1, TEMP, FracByte, COLOR> Color1fb;
typedef Attrib<1, CONST, FracByte, COLOR> ConstColor1fb;
typedef Attrib<2, INPUT, FracByte, COLOR> InputColor2fb;
typedef Attrib<2, OUTPUT, FracByte, COLOR> OutputColor2fb;
typedef Attrib<2, INOUT, FracByte, COLOR> InOutColor2fb;
typedef Attrib<2, TEMP, FracByte, COLOR> Color2fb;
typedef Attrib<2, CONST, FracByte, COLOR> ConstColor2fb;
typedef Attrib<3, INPUT, FracByte, COLOR> InputColor3fb;
typedef Attrib<3, OUTPUT, FracByte, COLOR> OutputColor3fb;
typedef Attrib<3, INOUT, FracByte, COLOR> InOutColor3fb;
typedef Attrib<3, TEMP, FracByte, COLOR> Color3fb;
typedef Attrib<3, CONST, FracByte, COLOR> ConstColor3fb;
typedef Attrib<4, INPUT, FracByte, COLOR> InputColor4fb;
typedef Attrib<4, OUTPUT, FracByte, COLOR> OutputColor4fb;
typedef Attrib<4, INOUT, FracByte, COLOR> InOutColor4fb;
typedef Attrib<4, TEMP, FracByte, COLOR> Color4fb;
typedef Attrib<4, CONST, FracByte, COLOR> ConstColor4fb;


typedef Attrib<1, INPUT, int, COLOR> InputColor1i;
typedef Attrib<1, OUTPUT, int, COLOR> OutputColor1i;
typedef Attrib<1, INOUT, int, COLOR> InOutColor1i;
typedef Attrib<1, TEMP, int, COLOR> Color1i;
typedef Attrib<1, CONST, int, COLOR> ConstColor1i;
typedef Attrib<2, INPUT, int, COLOR> InputColor2i;
typedef Attrib<2, OUTPUT, int, COLOR> OutputColor2i;
typedef Attrib<2, INOUT, int, COLOR> InOutColor2i;
typedef Attrib<2, TEMP, int, COLOR> Color2i;
typedef Attrib<2, CONST, int, COLOR> ConstColor2i;
typedef Attrib<3, INPUT, int, COLOR> InputColor3i;
typedef Attrib<3, OUTPUT, int, COLOR> OutputColor3i;
typedef Attrib<3, INOUT, int, COLOR> InOutColor3i;
typedef Attrib<3, TEMP, int, COLOR> Color3i;
typedef Attrib<3, CONST, int, COLOR> ConstColor3i;
typedef Attrib<4, INPUT, int, COLOR> InputColor4i;
typedef Attrib<4, OUTPUT, int, COLOR> OutputColor4i;
typedef Attrib<4, INOUT, int, COLOR> InOutColor4i;
typedef Attrib<4, TEMP, int, COLOR> Color4i;
typedef Attrib<4, CONST, int, COLOR> ConstColor4i;


typedef Attrib<1, INPUT, double, COLOR> InputColor1d;
typedef Attrib<1, OUTPUT, double, COLOR> OutputColor1d;
typedef Attrib<1, INOUT, double, COLOR> InOutColor1d;
typedef Attrib<1, TEMP, double, COLOR> Color1d;
typedef Attrib<1, CONST, double, COLOR> ConstColor1d;
typedef Attrib<2, INPUT, double, COLOR> InputColor2d;
typedef Attrib<2, OUTPUT, double, COLOR> OutputColor2d;
typedef Attrib<2, INOUT, double, COLOR> InOutColor2d;
typedef Attrib<2, TEMP, double, COLOR> Color2d;
typedef Attrib<2, CONST, double, COLOR> ConstColor2d;
typedef Attrib<3, INPUT, double, COLOR> InputColor3d;
typedef Attrib<3, OUTPUT, double, COLOR> OutputColor3d;
typedef Attrib<3, INOUT, double, COLOR> InOutColor3d;
typedef Attrib<3, TEMP, double, COLOR> Color3d;
typedef Attrib<3, CONST, double, COLOR> ConstColor3d;
typedef Attrib<4, INPUT, double, COLOR> InputColor4d;
typedef Attrib<4, OUTPUT, double, COLOR> OutputColor4d;
typedef Attrib<4, INOUT, double, COLOR> InOutColor4d;
typedef Attrib<4, TEMP, double, COLOR> Color4d;
typedef Attrib<4, CONST, double, COLOR> ConstColor4d;


typedef Attrib<1, INPUT, unsigned char, COLOR> InputColor1ub;
typedef Attrib<1, OUTPUT, unsigned char, COLOR> OutputColor1ub;
typedef Attrib<1, INOUT, unsigned char, COLOR> InOutColor1ub;
typedef Attrib<1, TEMP, unsigned char, COLOR> Color1ub;
typedef Attrib<1, CONST, unsigned char, COLOR> ConstColor1ub;
typedef Attrib<2, INPUT, unsigned char, COLOR> InputColor2ub;
typedef Attrib<2, OUTPUT, unsigned char, COLOR> OutputColor2ub;
typedef Attrib<2, INOUT, unsigned char, COLOR> InOutColor2ub;
typedef Attrib<2, TEMP, unsigned char, COLOR> Color2ub;
typedef Attrib<2, CONST, unsigned char, COLOR> ConstColor2ub;
typedef Attrib<3, INPUT, unsigned char, COLOR> InputColor3ub;
typedef Attrib<3, OUTPUT, unsigned char, COLOR> OutputColor3ub;
typedef Attrib<3, INOUT, unsigned char, COLOR> InOutColor3ub;
typedef Attrib<3, TEMP, unsigned char, COLOR> Color3ub;
typedef Attrib<3, CONST, unsigned char, COLOR> ConstColor3ub;
typedef Attrib<4, INPUT, unsigned char, COLOR> InputColor4ub;
typedef Attrib<4, OUTPUT, unsigned char, COLOR> OutputColor4ub;
typedef Attrib<4, INOUT, unsigned char, COLOR> InOutColor4ub;
typedef Attrib<4, TEMP, unsigned char, COLOR> Color4ub;
typedef Attrib<4, CONST, unsigned char, COLOR> ConstColor4ub;


typedef Attrib<1, INPUT, float, COLOR> InputColor1f;
typedef Attrib<1, OUTPUT, float, COLOR> OutputColor1f;
typedef Attrib<1, INOUT, float, COLOR> InOutColor1f;
typedef Attrib<1, TEMP, float, COLOR> Color1f;
typedef Attrib<1, CONST, float, COLOR> ConstColor1f;
typedef Attrib<2, INPUT, float, COLOR> InputColor2f;
typedef Attrib<2, OUTPUT, float, COLOR> OutputColor2f;
typedef Attrib<2, INOUT, float, COLOR> InOutColor2f;
typedef Attrib<2, TEMP, float, COLOR> Color2f;
typedef Attrib<2, CONST, float, COLOR> ConstColor2f;
typedef Attrib<3, INPUT, float, COLOR> InputColor3f;
typedef Attrib<3, OUTPUT, float, COLOR> OutputColor3f;
typedef Attrib<3, INOUT, float, COLOR> InOutColor3f;
typedef Attrib<3, TEMP, float, COLOR> Color3f;
typedef Attrib<3, CONST, float, COLOR> ConstColor3f;
typedef Attrib<4, INPUT, float, COLOR> InputColor4f;
typedef Attrib<4, OUTPUT, float, COLOR> OutputColor4f;
typedef Attrib<4, INOUT, float, COLOR> InOutColor4f;
typedef Attrib<4, TEMP, float, COLOR> Color4f;
typedef Attrib<4, CONST, float, COLOR> ConstColor4f;


typedef Attrib<1, INPUT, char, COLOR> InputColor1b;
typedef Attrib<1, OUTPUT, char, COLOR> OutputColor1b;
typedef Attrib<1, INOUT, char, COLOR> InOutColor1b;
typedef Attrib<1, TEMP, char, COLOR> Color1b;
typedef Attrib<1, CONST, char, COLOR> ConstColor1b;
typedef Attrib<2, INPUT, char, COLOR> InputColor2b;
typedef Attrib<2, OUTPUT, char, COLOR> OutputColor2b;
typedef Attrib<2, INOUT, char, COLOR> InOutColor2b;
typedef Attrib<2, TEMP, char, COLOR> Color2b;
typedef Attrib<2, CONST, char, COLOR> ConstColor2b;
typedef Attrib<3, INPUT, char, COLOR> InputColor3b;
typedef Attrib<3, OUTPUT, char, COLOR> OutputColor3b;
typedef Attrib<3, INOUT, char, COLOR> InOutColor3b;
typedef Attrib<3, TEMP, char, COLOR> Color3b;
typedef Attrib<3, CONST, char, COLOR> ConstColor3b;
typedef Attrib<4, INPUT, char, COLOR> InputColor4b;
typedef Attrib<4, OUTPUT, char, COLOR> OutputColor4b;
typedef Attrib<4, INOUT, char, COLOR> InOutColor4b;
typedef Attrib<4, TEMP, char, COLOR> Color4b;
typedef Attrib<4, CONST, char, COLOR> ConstColor4b;


typedef Attrib<1, INPUT, unsigned short, COLOR> InputColor1us;
typedef Attrib<1, OUTPUT, unsigned short, COLOR> OutputColor1us;
typedef Attrib<1, INOUT, unsigned short, COLOR> InOutColor1us;
typedef Attrib<1, TEMP, unsigned short, COLOR> Color1us;
typedef Attrib<1, CONST, unsigned short, COLOR> ConstColor1us;
typedef Attrib<2, INPUT, unsigned short, COLOR> InputColor2us;
typedef Attrib<2, OUTPUT, unsigned short, COLOR> OutputColor2us;
typedef Attrib<2, INOUT, unsigned short, COLOR> InOutColor2us;
typedef Attrib<2, TEMP, unsigned short, COLOR> Color2us;
typedef Attrib<2, CONST, unsigned short, COLOR> ConstColor2us;
typedef Attrib<3, INPUT, unsigned short, COLOR> InputColor3us;
typedef Attrib<3, OUTPUT, unsigned short, COLOR> OutputColor3us;
typedef Attrib<3, INOUT, unsigned short, COLOR> InOutColor3us;
typedef Attrib<3, TEMP, unsigned short, COLOR> Color3us;
typedef Attrib<3, CONST, unsigned short, COLOR> ConstColor3us;
typedef Attrib<4, INPUT, unsigned short, COLOR> InputColor4us;
typedef Attrib<4, OUTPUT, unsigned short, COLOR> OutputColor4us;
typedef Attrib<4, INOUT, unsigned short, COLOR> InOutColor4us;
typedef Attrib<4, TEMP, unsigned short, COLOR> Color4us;
typedef Attrib<4, CONST, unsigned short, COLOR> ConstColor4us;


typedef Attrib<1, INPUT, FracUByte, COLOR> InputColor1fub;
typedef Attrib<1, OUTPUT, FracUByte, COLOR> OutputColor1fub;
typedef Attrib<1, INOUT, FracUByte, COLOR> InOutColor1fub;
typedef Attrib<1, TEMP, FracUByte, COLOR> Color1fub;
typedef Attrib<1, CONST, FracUByte, COLOR> ConstColor1fub;
typedef Attrib<2, INPUT, FracUByte, COLOR> InputColor2fub;
typedef Attrib<2, OUTPUT, FracUByte, COLOR> OutputColor2fub;
typedef Attrib<2, INOUT, FracUByte, COLOR> InOutColor2fub;
typedef Attrib<2, TEMP, FracUByte, COLOR> Color2fub;
typedef Attrib<2, CONST, FracUByte, COLOR> ConstColor2fub;
typedef Attrib<3, INPUT, FracUByte, COLOR> InputColor3fub;
typedef Attrib<3, OUTPUT, FracUByte, COLOR> OutputColor3fub;
typedef Attrib<3, INOUT, FracUByte, COLOR> InOutColor3fub;
typedef Attrib<3, TEMP, FracUByte, COLOR> Color3fub;
typedef Attrib<3, CONST, FracUByte, COLOR> ConstColor3fub;
typedef Attrib<4, INPUT, FracUByte, COLOR> InputColor4fub;
typedef Attrib<4, OUTPUT, FracUByte, COLOR> OutputColor4fub;
typedef Attrib<4, INOUT, FracUByte, COLOR> InOutColor4fub;
typedef Attrib<4, TEMP, FracUByte, COLOR> Color4fub;
typedef Attrib<4, CONST, FracUByte, COLOR> ConstColor4fub;


typedef Attrib<1, INPUT, Half, COLOR> InputColor1h;
typedef Attrib<1, OUTPUT, Half, COLOR> OutputColor1h;
typedef Attrib<1, INOUT, Half, COLOR> InOutColor1h;
typedef Attrib<1, TEMP, Half, COLOR> Color1h;
typedef Attrib<1, CONST, Half, COLOR> ConstColor1h;
typedef Attrib<2, INPUT, Half, COLOR> InputColor2h;
typedef Attrib<2, OUTPUT, Half, COLOR> OutputColor2h;
typedef Attrib<2, INOUT, Half, COLOR> InOutColor2h;
typedef Attrib<2, TEMP, Half, COLOR> Color2h;
typedef Attrib<2, CONST, Half, COLOR> ConstColor2h;
typedef Attrib<3, INPUT, Half, COLOR> InputColor3h;
typedef Attrib<3, OUTPUT, Half, COLOR> OutputColor3h;
typedef Attrib<3, INOUT, Half, COLOR> InOutColor3h;
typedef Attrib<3, TEMP, Half, COLOR> Color3h;
typedef Attrib<3, CONST, Half, COLOR> ConstColor3h;
typedef Attrib<4, INPUT, Half, COLOR> InputColor4h;
typedef Attrib<4, OUTPUT, Half, COLOR> OutputColor4h;
typedef Attrib<4, INOUT, Half, COLOR> InOutColor4h;
typedef Attrib<4, TEMP, Half, COLOR> Color4h;
typedef Attrib<4, CONST, Half, COLOR> ConstColor4h;


typedef Attrib<1, INPUT, FracShort, COLOR> InputColor1fs;
typedef Attrib<1, OUTPUT, FracShort, COLOR> OutputColor1fs;
typedef Attrib<1, INOUT, FracShort, COLOR> InOutColor1fs;
typedef Attrib<1, TEMP, FracShort, COLOR> Color1fs;
typedef Attrib<1, CONST, FracShort, COLOR> ConstColor1fs;
typedef Attrib<2, INPUT, FracShort, COLOR> InputColor2fs;
typedef Attrib<2, OUTPUT, FracShort, COLOR> OutputColor2fs;
typedef Attrib<2, INOUT, FracShort, COLOR> InOutColor2fs;
typedef Attrib<2, TEMP, FracShort, COLOR> Color2fs;
typedef Attrib<2, CONST, FracShort, COLOR> ConstColor2fs;
typedef Attrib<3, INPUT, FracShort, COLOR> InputColor3fs;
typedef Attrib<3, OUTPUT, FracShort, COLOR> OutputColor3fs;
typedef Attrib<3, INOUT, FracShort, COLOR> InOutColor3fs;
typedef Attrib<3, TEMP, FracShort, COLOR> Color3fs;
typedef Attrib<3, CONST, FracShort, COLOR> ConstColor3fs;
typedef Attrib<4, INPUT, FracShort, COLOR> InputColor4fs;
typedef Attrib<4, OUTPUT, FracShort, COLOR> OutputColor4fs;
typedef Attrib<4, INOUT, FracShort, COLOR> InOutColor4fs;
typedef Attrib<4, TEMP, FracShort, COLOR> Color4fs;
typedef Attrib<4, CONST, FracShort, COLOR> ConstColor4fs;


typedef Attrib<1, INPUT, FracInt, COLOR> InputColor1fi;
typedef Attrib<1, OUTPUT, FracInt, COLOR> OutputColor1fi;
typedef Attrib<1, INOUT, FracInt, COLOR> InOutColor1fi;
typedef Attrib<1, TEMP, FracInt, COLOR> Color1fi;
typedef Attrib<1, CONST, FracInt, COLOR> ConstColor1fi;
typedef Attrib<2, INPUT, FracInt, COLOR> InputColor2fi;
typedef Attrib<2, OUTPUT, FracInt, COLOR> OutputColor2fi;
typedef Attrib<2, INOUT, FracInt, COLOR> InOutColor2fi;
typedef Attrib<2, TEMP, FracInt, COLOR> Color2fi;
typedef Attrib<2, CONST, FracInt, COLOR> ConstColor2fi;
typedef Attrib<3, INPUT, FracInt, COLOR> InputColor3fi;
typedef Attrib<3, OUTPUT, FracInt, COLOR> OutputColor3fi;
typedef Attrib<3, INOUT, FracInt, COLOR> InOutColor3fi;
typedef Attrib<3, TEMP, FracInt, COLOR> Color3fi;
typedef Attrib<3, CONST, FracInt, COLOR> ConstColor3fi;
typedef Attrib<4, INPUT, FracInt, COLOR> InputColor4fi;
typedef Attrib<4, OUTPUT, FracInt, COLOR> OutputColor4fi;
typedef Attrib<4, INOUT, FracInt, COLOR> InOutColor4fi;
typedef Attrib<4, TEMP, FracInt, COLOR> Color4fi;
typedef Attrib<4, CONST, FracInt, COLOR> ConstColor4fi;


typedef Attrib<1, INPUT, unsigned int, COLOR> InputColor1ui;
typedef Attrib<1, OUTPUT, unsigned int, COLOR> OutputColor1ui;
typedef Attrib<1, INOUT, unsigned int, COLOR> InOutColor1ui;
typedef Attrib<1, TEMP, unsigned int, COLOR> Color1ui;
typedef Attrib<1, CONST, unsigned int, COLOR> ConstColor1ui;
typedef Attrib<2, INPUT, unsigned int, COLOR> InputColor2ui;
typedef Attrib<2, OUTPUT, unsigned int, COLOR> OutputColor2ui;
typedef Attrib<2, INOUT, unsigned int, COLOR> InOutColor2ui;
typedef Attrib<2, TEMP, unsigned int, COLOR> Color2ui;
typedef Attrib<2, CONST, unsigned int, COLOR> ConstColor2ui;
typedef Attrib<3, INPUT, unsigned int, COLOR> InputColor3ui;
typedef Attrib<3, OUTPUT, unsigned int, COLOR> OutputColor3ui;
typedef Attrib<3, INOUT, unsigned int, COLOR> InOutColor3ui;
typedef Attrib<3, TEMP, unsigned int, COLOR> Color3ui;
typedef Attrib<3, CONST, unsigned int, COLOR> ConstColor3ui;
typedef Attrib<4, INPUT, unsigned int, COLOR> InputColor4ui;
typedef Attrib<4, OUTPUT, unsigned int, COLOR> OutputColor4ui;
typedef Attrib<4, INOUT, unsigned int, COLOR> InOutColor4ui;
typedef Attrib<4, TEMP, unsigned int, COLOR> Color4ui;
typedef Attrib<4, CONST, unsigned int, COLOR> ConstColor4ui;



} // namespace SH

#endif // SHSHCOLOR_HPP
