// WARNING - DO NOT EDIT THIS FILE:
// This file was automatically generated from scripts/Plane.hpp.py.
// If you wish to change it, edit that file instead.
//
// ---
//
// Sh: A GPU metaprogramming language.
//
// Copyright 2003-2006 Serious Hack Inc.
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
// MA  02110-1301, USA
//////////////////////////////////////////////////////////////////////////////

#ifndef SHSHPLANE_HPP
#define SHSHPLANE_HPP

#include "Attrib.hpp"
namespace SH {

/** An n-plane.
 * 
 *
 */

typedef Attrib<1, INPUT, FracUShort, PLANE> InputPlane1fus;
typedef Attrib<1, OUTPUT, FracUShort, PLANE> OutputPlane1fus;
typedef Attrib<1, INOUT, FracUShort, PLANE> InOutPlane1fus;
typedef Attrib<1, TEMP, FracUShort, PLANE> Plane1fus;
typedef Attrib<1, CONST, FracUShort, PLANE> ConstPlane1fus;
typedef Attrib<2, INPUT, FracUShort, PLANE> InputPlane2fus;
typedef Attrib<2, OUTPUT, FracUShort, PLANE> OutputPlane2fus;
typedef Attrib<2, INOUT, FracUShort, PLANE> InOutPlane2fus;
typedef Attrib<2, TEMP, FracUShort, PLANE> Plane2fus;
typedef Attrib<2, CONST, FracUShort, PLANE> ConstPlane2fus;
typedef Attrib<3, INPUT, FracUShort, PLANE> InputPlane3fus;
typedef Attrib<3, OUTPUT, FracUShort, PLANE> OutputPlane3fus;
typedef Attrib<3, INOUT, FracUShort, PLANE> InOutPlane3fus;
typedef Attrib<3, TEMP, FracUShort, PLANE> Plane3fus;
typedef Attrib<3, CONST, FracUShort, PLANE> ConstPlane3fus;
typedef Attrib<4, INPUT, FracUShort, PLANE> InputPlane4fus;
typedef Attrib<4, OUTPUT, FracUShort, PLANE> OutputPlane4fus;
typedef Attrib<4, INOUT, FracUShort, PLANE> InOutPlane4fus;
typedef Attrib<4, TEMP, FracUShort, PLANE> Plane4fus;
typedef Attrib<4, CONST, FracUShort, PLANE> ConstPlane4fus;


typedef Attrib<1, INPUT, short, PLANE> InputPlane1s;
typedef Attrib<1, OUTPUT, short, PLANE> OutputPlane1s;
typedef Attrib<1, INOUT, short, PLANE> InOutPlane1s;
typedef Attrib<1, TEMP, short, PLANE> Plane1s;
typedef Attrib<1, CONST, short, PLANE> ConstPlane1s;
typedef Attrib<2, INPUT, short, PLANE> InputPlane2s;
typedef Attrib<2, OUTPUT, short, PLANE> OutputPlane2s;
typedef Attrib<2, INOUT, short, PLANE> InOutPlane2s;
typedef Attrib<2, TEMP, short, PLANE> Plane2s;
typedef Attrib<2, CONST, short, PLANE> ConstPlane2s;
typedef Attrib<3, INPUT, short, PLANE> InputPlane3s;
typedef Attrib<3, OUTPUT, short, PLANE> OutputPlane3s;
typedef Attrib<3, INOUT, short, PLANE> InOutPlane3s;
typedef Attrib<3, TEMP, short, PLANE> Plane3s;
typedef Attrib<3, CONST, short, PLANE> ConstPlane3s;
typedef Attrib<4, INPUT, short, PLANE> InputPlane4s;
typedef Attrib<4, OUTPUT, short, PLANE> OutputPlane4s;
typedef Attrib<4, INOUT, short, PLANE> InOutPlane4s;
typedef Attrib<4, TEMP, short, PLANE> Plane4s;
typedef Attrib<4, CONST, short, PLANE> ConstPlane4s;


typedef Attrib<1, INPUT, FracUInt, PLANE> InputPlane1fui;
typedef Attrib<1, OUTPUT, FracUInt, PLANE> OutputPlane1fui;
typedef Attrib<1, INOUT, FracUInt, PLANE> InOutPlane1fui;
typedef Attrib<1, TEMP, FracUInt, PLANE> Plane1fui;
typedef Attrib<1, CONST, FracUInt, PLANE> ConstPlane1fui;
typedef Attrib<2, INPUT, FracUInt, PLANE> InputPlane2fui;
typedef Attrib<2, OUTPUT, FracUInt, PLANE> OutputPlane2fui;
typedef Attrib<2, INOUT, FracUInt, PLANE> InOutPlane2fui;
typedef Attrib<2, TEMP, FracUInt, PLANE> Plane2fui;
typedef Attrib<2, CONST, FracUInt, PLANE> ConstPlane2fui;
typedef Attrib<3, INPUT, FracUInt, PLANE> InputPlane3fui;
typedef Attrib<3, OUTPUT, FracUInt, PLANE> OutputPlane3fui;
typedef Attrib<3, INOUT, FracUInt, PLANE> InOutPlane3fui;
typedef Attrib<3, TEMP, FracUInt, PLANE> Plane3fui;
typedef Attrib<3, CONST, FracUInt, PLANE> ConstPlane3fui;
typedef Attrib<4, INPUT, FracUInt, PLANE> InputPlane4fui;
typedef Attrib<4, OUTPUT, FracUInt, PLANE> OutputPlane4fui;
typedef Attrib<4, INOUT, FracUInt, PLANE> InOutPlane4fui;
typedef Attrib<4, TEMP, FracUInt, PLANE> Plane4fui;
typedef Attrib<4, CONST, FracUInt, PLANE> ConstPlane4fui;


typedef Attrib<1, INPUT, FracByte, PLANE> InputPlane1fb;
typedef Attrib<1, OUTPUT, FracByte, PLANE> OutputPlane1fb;
typedef Attrib<1, INOUT, FracByte, PLANE> InOutPlane1fb;
typedef Attrib<1, TEMP, FracByte, PLANE> Plane1fb;
typedef Attrib<1, CONST, FracByte, PLANE> ConstPlane1fb;
typedef Attrib<2, INPUT, FracByte, PLANE> InputPlane2fb;
typedef Attrib<2, OUTPUT, FracByte, PLANE> OutputPlane2fb;
typedef Attrib<2, INOUT, FracByte, PLANE> InOutPlane2fb;
typedef Attrib<2, TEMP, FracByte, PLANE> Plane2fb;
typedef Attrib<2, CONST, FracByte, PLANE> ConstPlane2fb;
typedef Attrib<3, INPUT, FracByte, PLANE> InputPlane3fb;
typedef Attrib<3, OUTPUT, FracByte, PLANE> OutputPlane3fb;
typedef Attrib<3, INOUT, FracByte, PLANE> InOutPlane3fb;
typedef Attrib<3, TEMP, FracByte, PLANE> Plane3fb;
typedef Attrib<3, CONST, FracByte, PLANE> ConstPlane3fb;
typedef Attrib<4, INPUT, FracByte, PLANE> InputPlane4fb;
typedef Attrib<4, OUTPUT, FracByte, PLANE> OutputPlane4fb;
typedef Attrib<4, INOUT, FracByte, PLANE> InOutPlane4fb;
typedef Attrib<4, TEMP, FracByte, PLANE> Plane4fb;
typedef Attrib<4, CONST, FracByte, PLANE> ConstPlane4fb;


typedef Attrib<1, INPUT, int, PLANE> InputPlane1i;
typedef Attrib<1, OUTPUT, int, PLANE> OutputPlane1i;
typedef Attrib<1, INOUT, int, PLANE> InOutPlane1i;
typedef Attrib<1, TEMP, int, PLANE> Plane1i;
typedef Attrib<1, CONST, int, PLANE> ConstPlane1i;
typedef Attrib<2, INPUT, int, PLANE> InputPlane2i;
typedef Attrib<2, OUTPUT, int, PLANE> OutputPlane2i;
typedef Attrib<2, INOUT, int, PLANE> InOutPlane2i;
typedef Attrib<2, TEMP, int, PLANE> Plane2i;
typedef Attrib<2, CONST, int, PLANE> ConstPlane2i;
typedef Attrib<3, INPUT, int, PLANE> InputPlane3i;
typedef Attrib<3, OUTPUT, int, PLANE> OutputPlane3i;
typedef Attrib<3, INOUT, int, PLANE> InOutPlane3i;
typedef Attrib<3, TEMP, int, PLANE> Plane3i;
typedef Attrib<3, CONST, int, PLANE> ConstPlane3i;
typedef Attrib<4, INPUT, int, PLANE> InputPlane4i;
typedef Attrib<4, OUTPUT, int, PLANE> OutputPlane4i;
typedef Attrib<4, INOUT, int, PLANE> InOutPlane4i;
typedef Attrib<4, TEMP, int, PLANE> Plane4i;
typedef Attrib<4, CONST, int, PLANE> ConstPlane4i;


typedef Attrib<1, INPUT, double, PLANE> InputPlane1d;
typedef Attrib<1, OUTPUT, double, PLANE> OutputPlane1d;
typedef Attrib<1, INOUT, double, PLANE> InOutPlane1d;
typedef Attrib<1, TEMP, double, PLANE> Plane1d;
typedef Attrib<1, CONST, double, PLANE> ConstPlane1d;
typedef Attrib<2, INPUT, double, PLANE> InputPlane2d;
typedef Attrib<2, OUTPUT, double, PLANE> OutputPlane2d;
typedef Attrib<2, INOUT, double, PLANE> InOutPlane2d;
typedef Attrib<2, TEMP, double, PLANE> Plane2d;
typedef Attrib<2, CONST, double, PLANE> ConstPlane2d;
typedef Attrib<3, INPUT, double, PLANE> InputPlane3d;
typedef Attrib<3, OUTPUT, double, PLANE> OutputPlane3d;
typedef Attrib<3, INOUT, double, PLANE> InOutPlane3d;
typedef Attrib<3, TEMP, double, PLANE> Plane3d;
typedef Attrib<3, CONST, double, PLANE> ConstPlane3d;
typedef Attrib<4, INPUT, double, PLANE> InputPlane4d;
typedef Attrib<4, OUTPUT, double, PLANE> OutputPlane4d;
typedef Attrib<4, INOUT, double, PLANE> InOutPlane4d;
typedef Attrib<4, TEMP, double, PLANE> Plane4d;
typedef Attrib<4, CONST, double, PLANE> ConstPlane4d;


typedef Attrib<1, INPUT, unsigned char, PLANE> InputPlane1ub;
typedef Attrib<1, OUTPUT, unsigned char, PLANE> OutputPlane1ub;
typedef Attrib<1, INOUT, unsigned char, PLANE> InOutPlane1ub;
typedef Attrib<1, TEMP, unsigned char, PLANE> Plane1ub;
typedef Attrib<1, CONST, unsigned char, PLANE> ConstPlane1ub;
typedef Attrib<2, INPUT, unsigned char, PLANE> InputPlane2ub;
typedef Attrib<2, OUTPUT, unsigned char, PLANE> OutputPlane2ub;
typedef Attrib<2, INOUT, unsigned char, PLANE> InOutPlane2ub;
typedef Attrib<2, TEMP, unsigned char, PLANE> Plane2ub;
typedef Attrib<2, CONST, unsigned char, PLANE> ConstPlane2ub;
typedef Attrib<3, INPUT, unsigned char, PLANE> InputPlane3ub;
typedef Attrib<3, OUTPUT, unsigned char, PLANE> OutputPlane3ub;
typedef Attrib<3, INOUT, unsigned char, PLANE> InOutPlane3ub;
typedef Attrib<3, TEMP, unsigned char, PLANE> Plane3ub;
typedef Attrib<3, CONST, unsigned char, PLANE> ConstPlane3ub;
typedef Attrib<4, INPUT, unsigned char, PLANE> InputPlane4ub;
typedef Attrib<4, OUTPUT, unsigned char, PLANE> OutputPlane4ub;
typedef Attrib<4, INOUT, unsigned char, PLANE> InOutPlane4ub;
typedef Attrib<4, TEMP, unsigned char, PLANE> Plane4ub;
typedef Attrib<4, CONST, unsigned char, PLANE> ConstPlane4ub;


typedef Attrib<1, INPUT, float, PLANE> InputPlane1f;
typedef Attrib<1, OUTPUT, float, PLANE> OutputPlane1f;
typedef Attrib<1, INOUT, float, PLANE> InOutPlane1f;
typedef Attrib<1, TEMP, float, PLANE> Plane1f;
typedef Attrib<1, CONST, float, PLANE> ConstPlane1f;
typedef Attrib<2, INPUT, float, PLANE> InputPlane2f;
typedef Attrib<2, OUTPUT, float, PLANE> OutputPlane2f;
typedef Attrib<2, INOUT, float, PLANE> InOutPlane2f;
typedef Attrib<2, TEMP, float, PLANE> Plane2f;
typedef Attrib<2, CONST, float, PLANE> ConstPlane2f;
typedef Attrib<3, INPUT, float, PLANE> InputPlane3f;
typedef Attrib<3, OUTPUT, float, PLANE> OutputPlane3f;
typedef Attrib<3, INOUT, float, PLANE> InOutPlane3f;
typedef Attrib<3, TEMP, float, PLANE> Plane3f;
typedef Attrib<3, CONST, float, PLANE> ConstPlane3f;
typedef Attrib<4, INPUT, float, PLANE> InputPlane4f;
typedef Attrib<4, OUTPUT, float, PLANE> OutputPlane4f;
typedef Attrib<4, INOUT, float, PLANE> InOutPlane4f;
typedef Attrib<4, TEMP, float, PLANE> Plane4f;
typedef Attrib<4, CONST, float, PLANE> ConstPlane4f;


typedef Attrib<1, INPUT, char, PLANE> InputPlane1b;
typedef Attrib<1, OUTPUT, char, PLANE> OutputPlane1b;
typedef Attrib<1, INOUT, char, PLANE> InOutPlane1b;
typedef Attrib<1, TEMP, char, PLANE> Plane1b;
typedef Attrib<1, CONST, char, PLANE> ConstPlane1b;
typedef Attrib<2, INPUT, char, PLANE> InputPlane2b;
typedef Attrib<2, OUTPUT, char, PLANE> OutputPlane2b;
typedef Attrib<2, INOUT, char, PLANE> InOutPlane2b;
typedef Attrib<2, TEMP, char, PLANE> Plane2b;
typedef Attrib<2, CONST, char, PLANE> ConstPlane2b;
typedef Attrib<3, INPUT, char, PLANE> InputPlane3b;
typedef Attrib<3, OUTPUT, char, PLANE> OutputPlane3b;
typedef Attrib<3, INOUT, char, PLANE> InOutPlane3b;
typedef Attrib<3, TEMP, char, PLANE> Plane3b;
typedef Attrib<3, CONST, char, PLANE> ConstPlane3b;
typedef Attrib<4, INPUT, char, PLANE> InputPlane4b;
typedef Attrib<4, OUTPUT, char, PLANE> OutputPlane4b;
typedef Attrib<4, INOUT, char, PLANE> InOutPlane4b;
typedef Attrib<4, TEMP, char, PLANE> Plane4b;
typedef Attrib<4, CONST, char, PLANE> ConstPlane4b;


typedef Attrib<1, INPUT, unsigned short, PLANE> InputPlane1us;
typedef Attrib<1, OUTPUT, unsigned short, PLANE> OutputPlane1us;
typedef Attrib<1, INOUT, unsigned short, PLANE> InOutPlane1us;
typedef Attrib<1, TEMP, unsigned short, PLANE> Plane1us;
typedef Attrib<1, CONST, unsigned short, PLANE> ConstPlane1us;
typedef Attrib<2, INPUT, unsigned short, PLANE> InputPlane2us;
typedef Attrib<2, OUTPUT, unsigned short, PLANE> OutputPlane2us;
typedef Attrib<2, INOUT, unsigned short, PLANE> InOutPlane2us;
typedef Attrib<2, TEMP, unsigned short, PLANE> Plane2us;
typedef Attrib<2, CONST, unsigned short, PLANE> ConstPlane2us;
typedef Attrib<3, INPUT, unsigned short, PLANE> InputPlane3us;
typedef Attrib<3, OUTPUT, unsigned short, PLANE> OutputPlane3us;
typedef Attrib<3, INOUT, unsigned short, PLANE> InOutPlane3us;
typedef Attrib<3, TEMP, unsigned short, PLANE> Plane3us;
typedef Attrib<3, CONST, unsigned short, PLANE> ConstPlane3us;
typedef Attrib<4, INPUT, unsigned short, PLANE> InputPlane4us;
typedef Attrib<4, OUTPUT, unsigned short, PLANE> OutputPlane4us;
typedef Attrib<4, INOUT, unsigned short, PLANE> InOutPlane4us;
typedef Attrib<4, TEMP, unsigned short, PLANE> Plane4us;
typedef Attrib<4, CONST, unsigned short, PLANE> ConstPlane4us;


typedef Attrib<1, INPUT, FracUByte, PLANE> InputPlane1fub;
typedef Attrib<1, OUTPUT, FracUByte, PLANE> OutputPlane1fub;
typedef Attrib<1, INOUT, FracUByte, PLANE> InOutPlane1fub;
typedef Attrib<1, TEMP, FracUByte, PLANE> Plane1fub;
typedef Attrib<1, CONST, FracUByte, PLANE> ConstPlane1fub;
typedef Attrib<2, INPUT, FracUByte, PLANE> InputPlane2fub;
typedef Attrib<2, OUTPUT, FracUByte, PLANE> OutputPlane2fub;
typedef Attrib<2, INOUT, FracUByte, PLANE> InOutPlane2fub;
typedef Attrib<2, TEMP, FracUByte, PLANE> Plane2fub;
typedef Attrib<2, CONST, FracUByte, PLANE> ConstPlane2fub;
typedef Attrib<3, INPUT, FracUByte, PLANE> InputPlane3fub;
typedef Attrib<3, OUTPUT, FracUByte, PLANE> OutputPlane3fub;
typedef Attrib<3, INOUT, FracUByte, PLANE> InOutPlane3fub;
typedef Attrib<3, TEMP, FracUByte, PLANE> Plane3fub;
typedef Attrib<3, CONST, FracUByte, PLANE> ConstPlane3fub;
typedef Attrib<4, INPUT, FracUByte, PLANE> InputPlane4fub;
typedef Attrib<4, OUTPUT, FracUByte, PLANE> OutputPlane4fub;
typedef Attrib<4, INOUT, FracUByte, PLANE> InOutPlane4fub;
typedef Attrib<4, TEMP, FracUByte, PLANE> Plane4fub;
typedef Attrib<4, CONST, FracUByte, PLANE> ConstPlane4fub;


typedef Attrib<1, INPUT, Half, PLANE> InputPlane1h;
typedef Attrib<1, OUTPUT, Half, PLANE> OutputPlane1h;
typedef Attrib<1, INOUT, Half, PLANE> InOutPlane1h;
typedef Attrib<1, TEMP, Half, PLANE> Plane1h;
typedef Attrib<1, CONST, Half, PLANE> ConstPlane1h;
typedef Attrib<2, INPUT, Half, PLANE> InputPlane2h;
typedef Attrib<2, OUTPUT, Half, PLANE> OutputPlane2h;
typedef Attrib<2, INOUT, Half, PLANE> InOutPlane2h;
typedef Attrib<2, TEMP, Half, PLANE> Plane2h;
typedef Attrib<2, CONST, Half, PLANE> ConstPlane2h;
typedef Attrib<3, INPUT, Half, PLANE> InputPlane3h;
typedef Attrib<3, OUTPUT, Half, PLANE> OutputPlane3h;
typedef Attrib<3, INOUT, Half, PLANE> InOutPlane3h;
typedef Attrib<3, TEMP, Half, PLANE> Plane3h;
typedef Attrib<3, CONST, Half, PLANE> ConstPlane3h;
typedef Attrib<4, INPUT, Half, PLANE> InputPlane4h;
typedef Attrib<4, OUTPUT, Half, PLANE> OutputPlane4h;
typedef Attrib<4, INOUT, Half, PLANE> InOutPlane4h;
typedef Attrib<4, TEMP, Half, PLANE> Plane4h;
typedef Attrib<4, CONST, Half, PLANE> ConstPlane4h;


typedef Attrib<1, INPUT, FracShort, PLANE> InputPlane1fs;
typedef Attrib<1, OUTPUT, FracShort, PLANE> OutputPlane1fs;
typedef Attrib<1, INOUT, FracShort, PLANE> InOutPlane1fs;
typedef Attrib<1, TEMP, FracShort, PLANE> Plane1fs;
typedef Attrib<1, CONST, FracShort, PLANE> ConstPlane1fs;
typedef Attrib<2, INPUT, FracShort, PLANE> InputPlane2fs;
typedef Attrib<2, OUTPUT, FracShort, PLANE> OutputPlane2fs;
typedef Attrib<2, INOUT, FracShort, PLANE> InOutPlane2fs;
typedef Attrib<2, TEMP, FracShort, PLANE> Plane2fs;
typedef Attrib<2, CONST, FracShort, PLANE> ConstPlane2fs;
typedef Attrib<3, INPUT, FracShort, PLANE> InputPlane3fs;
typedef Attrib<3, OUTPUT, FracShort, PLANE> OutputPlane3fs;
typedef Attrib<3, INOUT, FracShort, PLANE> InOutPlane3fs;
typedef Attrib<3, TEMP, FracShort, PLANE> Plane3fs;
typedef Attrib<3, CONST, FracShort, PLANE> ConstPlane3fs;
typedef Attrib<4, INPUT, FracShort, PLANE> InputPlane4fs;
typedef Attrib<4, OUTPUT, FracShort, PLANE> OutputPlane4fs;
typedef Attrib<4, INOUT, FracShort, PLANE> InOutPlane4fs;
typedef Attrib<4, TEMP, FracShort, PLANE> Plane4fs;
typedef Attrib<4, CONST, FracShort, PLANE> ConstPlane4fs;


typedef Attrib<1, INPUT, FracInt, PLANE> InputPlane1fi;
typedef Attrib<1, OUTPUT, FracInt, PLANE> OutputPlane1fi;
typedef Attrib<1, INOUT, FracInt, PLANE> InOutPlane1fi;
typedef Attrib<1, TEMP, FracInt, PLANE> Plane1fi;
typedef Attrib<1, CONST, FracInt, PLANE> ConstPlane1fi;
typedef Attrib<2, INPUT, FracInt, PLANE> InputPlane2fi;
typedef Attrib<2, OUTPUT, FracInt, PLANE> OutputPlane2fi;
typedef Attrib<2, INOUT, FracInt, PLANE> InOutPlane2fi;
typedef Attrib<2, TEMP, FracInt, PLANE> Plane2fi;
typedef Attrib<2, CONST, FracInt, PLANE> ConstPlane2fi;
typedef Attrib<3, INPUT, FracInt, PLANE> InputPlane3fi;
typedef Attrib<3, OUTPUT, FracInt, PLANE> OutputPlane3fi;
typedef Attrib<3, INOUT, FracInt, PLANE> InOutPlane3fi;
typedef Attrib<3, TEMP, FracInt, PLANE> Plane3fi;
typedef Attrib<3, CONST, FracInt, PLANE> ConstPlane3fi;
typedef Attrib<4, INPUT, FracInt, PLANE> InputPlane4fi;
typedef Attrib<4, OUTPUT, FracInt, PLANE> OutputPlane4fi;
typedef Attrib<4, INOUT, FracInt, PLANE> InOutPlane4fi;
typedef Attrib<4, TEMP, FracInt, PLANE> Plane4fi;
typedef Attrib<4, CONST, FracInt, PLANE> ConstPlane4fi;


typedef Attrib<1, INPUT, unsigned int, PLANE> InputPlane1ui;
typedef Attrib<1, OUTPUT, unsigned int, PLANE> OutputPlane1ui;
typedef Attrib<1, INOUT, unsigned int, PLANE> InOutPlane1ui;
typedef Attrib<1, TEMP, unsigned int, PLANE> Plane1ui;
typedef Attrib<1, CONST, unsigned int, PLANE> ConstPlane1ui;
typedef Attrib<2, INPUT, unsigned int, PLANE> InputPlane2ui;
typedef Attrib<2, OUTPUT, unsigned int, PLANE> OutputPlane2ui;
typedef Attrib<2, INOUT, unsigned int, PLANE> InOutPlane2ui;
typedef Attrib<2, TEMP, unsigned int, PLANE> Plane2ui;
typedef Attrib<2, CONST, unsigned int, PLANE> ConstPlane2ui;
typedef Attrib<3, INPUT, unsigned int, PLANE> InputPlane3ui;
typedef Attrib<3, OUTPUT, unsigned int, PLANE> OutputPlane3ui;
typedef Attrib<3, INOUT, unsigned int, PLANE> InOutPlane3ui;
typedef Attrib<3, TEMP, unsigned int, PLANE> Plane3ui;
typedef Attrib<3, CONST, unsigned int, PLANE> ConstPlane3ui;
typedef Attrib<4, INPUT, unsigned int, PLANE> InputPlane4ui;
typedef Attrib<4, OUTPUT, unsigned int, PLANE> OutputPlane4ui;
typedef Attrib<4, INOUT, unsigned int, PLANE> InOutPlane4ui;
typedef Attrib<4, TEMP, unsigned int, PLANE> Plane4ui;
typedef Attrib<4, CONST, unsigned int, PLANE> ConstPlane4ui;



} // namespace SH

#endif // SHSHPLANE_HPP
