// WARNING - DO NOT EDIT THIS FILE:
// This file was automatically generated from scripts/Point.hpp.py.
// If you wish to change it, edit that file instead.
//
// ---
//
// Sh: A GPU metaprogramming language.
//
// Copyright 2003-2006 Serious Hack Inc.
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
// MA  02110-1301, USA
//////////////////////////////////////////////////////////////////////////////

#ifndef SHPOINT_HPP
#define SHPOINT_HPP

#include "Attrib.hpp"
namespace SH {

/** An n-point.
 * 
 *
 */

typedef Attrib<1, INPUT, FracUShort, POINT> InputPoint1fus;
typedef Attrib<1, OUTPUT, FracUShort, POINT> OutputPoint1fus;
typedef Attrib<1, INOUT, FracUShort, POINT> InOutPoint1fus;
typedef Attrib<1, TEMP, FracUShort, POINT> Point1fus;
typedef Attrib<1, CONST, FracUShort, POINT> ConstPoint1fus;
typedef Attrib<2, INPUT, FracUShort, POINT> InputPoint2fus;
typedef Attrib<2, OUTPUT, FracUShort, POINT> OutputPoint2fus;
typedef Attrib<2, INOUT, FracUShort, POINT> InOutPoint2fus;
typedef Attrib<2, TEMP, FracUShort, POINT> Point2fus;
typedef Attrib<2, CONST, FracUShort, POINT> ConstPoint2fus;
typedef Attrib<3, INPUT, FracUShort, POINT> InputPoint3fus;
typedef Attrib<3, OUTPUT, FracUShort, POINT> OutputPoint3fus;
typedef Attrib<3, INOUT, FracUShort, POINT> InOutPoint3fus;
typedef Attrib<3, TEMP, FracUShort, POINT> Point3fus;
typedef Attrib<3, CONST, FracUShort, POINT> ConstPoint3fus;
typedef Attrib<4, INPUT, FracUShort, POINT> InputPoint4fus;
typedef Attrib<4, OUTPUT, FracUShort, POINT> OutputPoint4fus;
typedef Attrib<4, INOUT, FracUShort, POINT> InOutPoint4fus;
typedef Attrib<4, TEMP, FracUShort, POINT> Point4fus;
typedef Attrib<4, CONST, FracUShort, POINT> ConstPoint4fus;


typedef Attrib<1, INPUT, short, POINT> InputPoint1s;
typedef Attrib<1, OUTPUT, short, POINT> OutputPoint1s;
typedef Attrib<1, INOUT, short, POINT> InOutPoint1s;
typedef Attrib<1, TEMP, short, POINT> Point1s;
typedef Attrib<1, CONST, short, POINT> ConstPoint1s;
typedef Attrib<2, INPUT, short, POINT> InputPoint2s;
typedef Attrib<2, OUTPUT, short, POINT> OutputPoint2s;
typedef Attrib<2, INOUT, short, POINT> InOutPoint2s;
typedef Attrib<2, TEMP, short, POINT> Point2s;
typedef Attrib<2, CONST, short, POINT> ConstPoint2s;
typedef Attrib<3, INPUT, short, POINT> InputPoint3s;
typedef Attrib<3, OUTPUT, short, POINT> OutputPoint3s;
typedef Attrib<3, INOUT, short, POINT> InOutPoint3s;
typedef Attrib<3, TEMP, short, POINT> Point3s;
typedef Attrib<3, CONST, short, POINT> ConstPoint3s;
typedef Attrib<4, INPUT, short, POINT> InputPoint4s;
typedef Attrib<4, OUTPUT, short, POINT> OutputPoint4s;
typedef Attrib<4, INOUT, short, POINT> InOutPoint4s;
typedef Attrib<4, TEMP, short, POINT> Point4s;
typedef Attrib<4, CONST, short, POINT> ConstPoint4s;


typedef Attrib<1, INPUT, FracUInt, POINT> InputPoint1fui;
typedef Attrib<1, OUTPUT, FracUInt, POINT> OutputPoint1fui;
typedef Attrib<1, INOUT, FracUInt, POINT> InOutPoint1fui;
typedef Attrib<1, TEMP, FracUInt, POINT> Point1fui;
typedef Attrib<1, CONST, FracUInt, POINT> ConstPoint1fui;
typedef Attrib<2, INPUT, FracUInt, POINT> InputPoint2fui;
typedef Attrib<2, OUTPUT, FracUInt, POINT> OutputPoint2fui;
typedef Attrib<2, INOUT, FracUInt, POINT> InOutPoint2fui;
typedef Attrib<2, TEMP, FracUInt, POINT> Point2fui;
typedef Attrib<2, CONST, FracUInt, POINT> ConstPoint2fui;
typedef Attrib<3, INPUT, FracUInt, POINT> InputPoint3fui;
typedef Attrib<3, OUTPUT, FracUInt, POINT> OutputPoint3fui;
typedef Attrib<3, INOUT, FracUInt, POINT> InOutPoint3fui;
typedef Attrib<3, TEMP, FracUInt, POINT> Point3fui;
typedef Attrib<3, CONST, FracUInt, POINT> ConstPoint3fui;
typedef Attrib<4, INPUT, FracUInt, POINT> InputPoint4fui;
typedef Attrib<4, OUTPUT, FracUInt, POINT> OutputPoint4fui;
typedef Attrib<4, INOUT, FracUInt, POINT> InOutPoint4fui;
typedef Attrib<4, TEMP, FracUInt, POINT> Point4fui;
typedef Attrib<4, CONST, FracUInt, POINT> ConstPoint4fui;


typedef Attrib<1, INPUT, FracByte, POINT> InputPoint1fb;
typedef Attrib<1, OUTPUT, FracByte, POINT> OutputPoint1fb;
typedef Attrib<1, INOUT, FracByte, POINT> InOutPoint1fb;
typedef Attrib<1, TEMP, FracByte, POINT> Point1fb;
typedef Attrib<1, CONST, FracByte, POINT> ConstPoint1fb;
typedef Attrib<2, INPUT, FracByte, POINT> InputPoint2fb;
typedef Attrib<2, OUTPUT, FracByte, POINT> OutputPoint2fb;
typedef Attrib<2, INOUT, FracByte, POINT> InOutPoint2fb;
typedef Attrib<2, TEMP, FracByte, POINT> Point2fb;
typedef Attrib<2, CONST, FracByte, POINT> ConstPoint2fb;
typedef Attrib<3, INPUT, FracByte, POINT> InputPoint3fb;
typedef Attrib<3, OUTPUT, FracByte, POINT> OutputPoint3fb;
typedef Attrib<3, INOUT, FracByte, POINT> InOutPoint3fb;
typedef Attrib<3, TEMP, FracByte, POINT> Point3fb;
typedef Attrib<3, CONST, FracByte, POINT> ConstPoint3fb;
typedef Attrib<4, INPUT, FracByte, POINT> InputPoint4fb;
typedef Attrib<4, OUTPUT, FracByte, POINT> OutputPoint4fb;
typedef Attrib<4, INOUT, FracByte, POINT> InOutPoint4fb;
typedef Attrib<4, TEMP, FracByte, POINT> Point4fb;
typedef Attrib<4, CONST, FracByte, POINT> ConstPoint4fb;


typedef Attrib<1, INPUT, int, POINT> InputPoint1i;
typedef Attrib<1, OUTPUT, int, POINT> OutputPoint1i;
typedef Attrib<1, INOUT, int, POINT> InOutPoint1i;
typedef Attrib<1, TEMP, int, POINT> Point1i;
typedef Attrib<1, CONST, int, POINT> ConstPoint1i;
typedef Attrib<2, INPUT, int, POINT> InputPoint2i;
typedef Attrib<2, OUTPUT, int, POINT> OutputPoint2i;
typedef Attrib<2, INOUT, int, POINT> InOutPoint2i;
typedef Attrib<2, TEMP, int, POINT> Point2i;
typedef Attrib<2, CONST, int, POINT> ConstPoint2i;
typedef Attrib<3, INPUT, int, POINT> InputPoint3i;
typedef Attrib<3, OUTPUT, int, POINT> OutputPoint3i;
typedef Attrib<3, INOUT, int, POINT> InOutPoint3i;
typedef Attrib<3, TEMP, int, POINT> Point3i;
typedef Attrib<3, CONST, int, POINT> ConstPoint3i;
typedef Attrib<4, INPUT, int, POINT> InputPoint4i;
typedef Attrib<4, OUTPUT, int, POINT> OutputPoint4i;
typedef Attrib<4, INOUT, int, POINT> InOutPoint4i;
typedef Attrib<4, TEMP, int, POINT> Point4i;
typedef Attrib<4, CONST, int, POINT> ConstPoint4i;


typedef Attrib<1, INPUT, double, POINT> InputPoint1d;
typedef Attrib<1, OUTPUT, double, POINT> OutputPoint1d;
typedef Attrib<1, INOUT, double, POINT> InOutPoint1d;
typedef Attrib<1, TEMP, double, POINT> Point1d;
typedef Attrib<1, CONST, double, POINT> ConstPoint1d;
typedef Attrib<2, INPUT, double, POINT> InputPoint2d;
typedef Attrib<2, OUTPUT, double, POINT> OutputPoint2d;
typedef Attrib<2, INOUT, double, POINT> InOutPoint2d;
typedef Attrib<2, TEMP, double, POINT> Point2d;
typedef Attrib<2, CONST, double, POINT> ConstPoint2d;
typedef Attrib<3, INPUT, double, POINT> InputPoint3d;
typedef Attrib<3, OUTPUT, double, POINT> OutputPoint3d;
typedef Attrib<3, INOUT, double, POINT> InOutPoint3d;
typedef Attrib<3, TEMP, double, POINT> Point3d;
typedef Attrib<3, CONST, double, POINT> ConstPoint3d;
typedef Attrib<4, INPUT, double, POINT> InputPoint4d;
typedef Attrib<4, OUTPUT, double, POINT> OutputPoint4d;
typedef Attrib<4, INOUT, double, POINT> InOutPoint4d;
typedef Attrib<4, TEMP, double, POINT> Point4d;
typedef Attrib<4, CONST, double, POINT> ConstPoint4d;


typedef Attrib<1, INPUT, unsigned char, POINT> InputPoint1ub;
typedef Attrib<1, OUTPUT, unsigned char, POINT> OutputPoint1ub;
typedef Attrib<1, INOUT, unsigned char, POINT> InOutPoint1ub;
typedef Attrib<1, TEMP, unsigned char, POINT> Point1ub;
typedef Attrib<1, CONST, unsigned char, POINT> ConstPoint1ub;
typedef Attrib<2, INPUT, unsigned char, POINT> InputPoint2ub;
typedef Attrib<2, OUTPUT, unsigned char, POINT> OutputPoint2ub;
typedef Attrib<2, INOUT, unsigned char, POINT> InOutPoint2ub;
typedef Attrib<2, TEMP, unsigned char, POINT> Point2ub;
typedef Attrib<2, CONST, unsigned char, POINT> ConstPoint2ub;
typedef Attrib<3, INPUT, unsigned char, POINT> InputPoint3ub;
typedef Attrib<3, OUTPUT, unsigned char, POINT> OutputPoint3ub;
typedef Attrib<3, INOUT, unsigned char, POINT> InOutPoint3ub;
typedef Attrib<3, TEMP, unsigned char, POINT> Point3ub;
typedef Attrib<3, CONST, unsigned char, POINT> ConstPoint3ub;
typedef Attrib<4, INPUT, unsigned char, POINT> InputPoint4ub;
typedef Attrib<4, OUTPUT, unsigned char, POINT> OutputPoint4ub;
typedef Attrib<4, INOUT, unsigned char, POINT> InOutPoint4ub;
typedef Attrib<4, TEMP, unsigned char, POINT> Point4ub;
typedef Attrib<4, CONST, unsigned char, POINT> ConstPoint4ub;


typedef Attrib<1, INPUT, float, POINT> InputPoint1f;
typedef Attrib<1, OUTPUT, float, POINT> OutputPoint1f;
typedef Attrib<1, INOUT, float, POINT> InOutPoint1f;
typedef Attrib<1, TEMP, float, POINT> Point1f;
typedef Attrib<1, CONST, float, POINT> ConstPoint1f;
typedef Attrib<2, INPUT, float, POINT> InputPoint2f;
typedef Attrib<2, OUTPUT, float, POINT> OutputPoint2f;
typedef Attrib<2, INOUT, float, POINT> InOutPoint2f;
typedef Attrib<2, TEMP, float, POINT> Point2f;
typedef Attrib<2, CONST, float, POINT> ConstPoint2f;
typedef Attrib<3, INPUT, float, POINT> InputPoint3f;
typedef Attrib<3, OUTPUT, float, POINT> OutputPoint3f;
typedef Attrib<3, INOUT, float, POINT> InOutPoint3f;
typedef Attrib<3, TEMP, float, POINT> Point3f;
typedef Attrib<3, CONST, float, POINT> ConstPoint3f;
typedef Attrib<4, INPUT, float, POINT> InputPoint4f;
typedef Attrib<4, OUTPUT, float, POINT> OutputPoint4f;
typedef Attrib<4, INOUT, float, POINT> InOutPoint4f;
typedef Attrib<4, TEMP, float, POINT> Point4f;
typedef Attrib<4, CONST, float, POINT> ConstPoint4f;


typedef Attrib<1, INPUT, char, POINT> InputPoint1b;
typedef Attrib<1, OUTPUT, char, POINT> OutputPoint1b;
typedef Attrib<1, INOUT, char, POINT> InOutPoint1b;
typedef Attrib<1, TEMP, char, POINT> Point1b;
typedef Attrib<1, CONST, char, POINT> ConstPoint1b;
typedef Attrib<2, INPUT, char, POINT> InputPoint2b;
typedef Attrib<2, OUTPUT, char, POINT> OutputPoint2b;
typedef Attrib<2, INOUT, char, POINT> InOutPoint2b;
typedef Attrib<2, TEMP, char, POINT> Point2b;
typedef Attrib<2, CONST, char, POINT> ConstPoint2b;
typedef Attrib<3, INPUT, char, POINT> InputPoint3b;
typedef Attrib<3, OUTPUT, char, POINT> OutputPoint3b;
typedef Attrib<3, INOUT, char, POINT> InOutPoint3b;
typedef Attrib<3, TEMP, char, POINT> Point3b;
typedef Attrib<3, CONST, char, POINT> ConstPoint3b;
typedef Attrib<4, INPUT, char, POINT> InputPoint4b;
typedef Attrib<4, OUTPUT, char, POINT> OutputPoint4b;
typedef Attrib<4, INOUT, char, POINT> InOutPoint4b;
typedef Attrib<4, TEMP, char, POINT> Point4b;
typedef Attrib<4, CONST, char, POINT> ConstPoint4b;


typedef Attrib<1, INPUT, unsigned short, POINT> InputPoint1us;
typedef Attrib<1, OUTPUT, unsigned short, POINT> OutputPoint1us;
typedef Attrib<1, INOUT, unsigned short, POINT> InOutPoint1us;
typedef Attrib<1, TEMP, unsigned short, POINT> Point1us;
typedef Attrib<1, CONST, unsigned short, POINT> ConstPoint1us;
typedef Attrib<2, INPUT, unsigned short, POINT> InputPoint2us;
typedef Attrib<2, OUTPUT, unsigned short, POINT> OutputPoint2us;
typedef Attrib<2, INOUT, unsigned short, POINT> InOutPoint2us;
typedef Attrib<2, TEMP, unsigned short, POINT> Point2us;
typedef Attrib<2, CONST, unsigned short, POINT> ConstPoint2us;
typedef Attrib<3, INPUT, unsigned short, POINT> InputPoint3us;
typedef Attrib<3, OUTPUT, unsigned short, POINT> OutputPoint3us;
typedef Attrib<3, INOUT, unsigned short, POINT> InOutPoint3us;
typedef Attrib<3, TEMP, unsigned short, POINT> Point3us;
typedef Attrib<3, CONST, unsigned short, POINT> ConstPoint3us;
typedef Attrib<4, INPUT, unsigned short, POINT> InputPoint4us;
typedef Attrib<4, OUTPUT, unsigned short, POINT> OutputPoint4us;
typedef Attrib<4, INOUT, unsigned short, POINT> InOutPoint4us;
typedef Attrib<4, TEMP, unsigned short, POINT> Point4us;
typedef Attrib<4, CONST, unsigned short, POINT> ConstPoint4us;


typedef Attrib<1, INPUT, FracUByte, POINT> InputPoint1fub;
typedef Attrib<1, OUTPUT, FracUByte, POINT> OutputPoint1fub;
typedef Attrib<1, INOUT, FracUByte, POINT> InOutPoint1fub;
typedef Attrib<1, TEMP, FracUByte, POINT> Point1fub;
typedef Attrib<1, CONST, FracUByte, POINT> ConstPoint1fub;
typedef Attrib<2, INPUT, FracUByte, POINT> InputPoint2fub;
typedef Attrib<2, OUTPUT, FracUByte, POINT> OutputPoint2fub;
typedef Attrib<2, INOUT, FracUByte, POINT> InOutPoint2fub;
typedef Attrib<2, TEMP, FracUByte, POINT> Point2fub;
typedef Attrib<2, CONST, FracUByte, POINT> ConstPoint2fub;
typedef Attrib<3, INPUT, FracUByte, POINT> InputPoint3fub;
typedef Attrib<3, OUTPUT, FracUByte, POINT> OutputPoint3fub;
typedef Attrib<3, INOUT, FracUByte, POINT> InOutPoint3fub;
typedef Attrib<3, TEMP, FracUByte, POINT> Point3fub;
typedef Attrib<3, CONST, FracUByte, POINT> ConstPoint3fub;
typedef Attrib<4, INPUT, FracUByte, POINT> InputPoint4fub;
typedef Attrib<4, OUTPUT, FracUByte, POINT> OutputPoint4fub;
typedef Attrib<4, INOUT, FracUByte, POINT> InOutPoint4fub;
typedef Attrib<4, TEMP, FracUByte, POINT> Point4fub;
typedef Attrib<4, CONST, FracUByte, POINT> ConstPoint4fub;


typedef Attrib<1, INPUT, Half, POINT> InputPoint1h;
typedef Attrib<1, OUTPUT, Half, POINT> OutputPoint1h;
typedef Attrib<1, INOUT, Half, POINT> InOutPoint1h;
typedef Attrib<1, TEMP, Half, POINT> Point1h;
typedef Attrib<1, CONST, Half, POINT> ConstPoint1h;
typedef Attrib<2, INPUT, Half, POINT> InputPoint2h;
typedef Attrib<2, OUTPUT, Half, POINT> OutputPoint2h;
typedef Attrib<2, INOUT, Half, POINT> InOutPoint2h;
typedef Attrib<2, TEMP, Half, POINT> Point2h;
typedef Attrib<2, CONST, Half, POINT> ConstPoint2h;
typedef Attrib<3, INPUT, Half, POINT> InputPoint3h;
typedef Attrib<3, OUTPUT, Half, POINT> OutputPoint3h;
typedef Attrib<3, INOUT, Half, POINT> InOutPoint3h;
typedef Attrib<3, TEMP, Half, POINT> Point3h;
typedef Attrib<3, CONST, Half, POINT> ConstPoint3h;
typedef Attrib<4, INPUT, Half, POINT> InputPoint4h;
typedef Attrib<4, OUTPUT, Half, POINT> OutputPoint4h;
typedef Attrib<4, INOUT, Half, POINT> InOutPoint4h;
typedef Attrib<4, TEMP, Half, POINT> Point4h;
typedef Attrib<4, CONST, Half, POINT> ConstPoint4h;


typedef Attrib<1, INPUT, FracShort, POINT> InputPoint1fs;
typedef Attrib<1, OUTPUT, FracShort, POINT> OutputPoint1fs;
typedef Attrib<1, INOUT, FracShort, POINT> InOutPoint1fs;
typedef Attrib<1, TEMP, FracShort, POINT> Point1fs;
typedef Attrib<1, CONST, FracShort, POINT> ConstPoint1fs;
typedef Attrib<2, INPUT, FracShort, POINT> InputPoint2fs;
typedef Attrib<2, OUTPUT, FracShort, POINT> OutputPoint2fs;
typedef Attrib<2, INOUT, FracShort, POINT> InOutPoint2fs;
typedef Attrib<2, TEMP, FracShort, POINT> Point2fs;
typedef Attrib<2, CONST, FracShort, POINT> ConstPoint2fs;
typedef Attrib<3, INPUT, FracShort, POINT> InputPoint3fs;
typedef Attrib<3, OUTPUT, FracShort, POINT> OutputPoint3fs;
typedef Attrib<3, INOUT, FracShort, POINT> InOutPoint3fs;
typedef Attrib<3, TEMP, FracShort, POINT> Point3fs;
typedef Attrib<3, CONST, FracShort, POINT> ConstPoint3fs;
typedef Attrib<4, INPUT, FracShort, POINT> InputPoint4fs;
typedef Attrib<4, OUTPUT, FracShort, POINT> OutputPoint4fs;
typedef Attrib<4, INOUT, FracShort, POINT> InOutPoint4fs;
typedef Attrib<4, TEMP, FracShort, POINT> Point4fs;
typedef Attrib<4, CONST, FracShort, POINT> ConstPoint4fs;


typedef Attrib<1, INPUT, FracInt, POINT> InputPoint1fi;
typedef Attrib<1, OUTPUT, FracInt, POINT> OutputPoint1fi;
typedef Attrib<1, INOUT, FracInt, POINT> InOutPoint1fi;
typedef Attrib<1, TEMP, FracInt, POINT> Point1fi;
typedef Attrib<1, CONST, FracInt, POINT> ConstPoint1fi;
typedef Attrib<2, INPUT, FracInt, POINT> InputPoint2fi;
typedef Attrib<2, OUTPUT, FracInt, POINT> OutputPoint2fi;
typedef Attrib<2, INOUT, FracInt, POINT> InOutPoint2fi;
typedef Attrib<2, TEMP, FracInt, POINT> Point2fi;
typedef Attrib<2, CONST, FracInt, POINT> ConstPoint2fi;
typedef Attrib<3, INPUT, FracInt, POINT> InputPoint3fi;
typedef Attrib<3, OUTPUT, FracInt, POINT> OutputPoint3fi;
typedef Attrib<3, INOUT, FracInt, POINT> InOutPoint3fi;
typedef Attrib<3, TEMP, FracInt, POINT> Point3fi;
typedef Attrib<3, CONST, FracInt, POINT> ConstPoint3fi;
typedef Attrib<4, INPUT, FracInt, POINT> InputPoint4fi;
typedef Attrib<4, OUTPUT, FracInt, POINT> OutputPoint4fi;
typedef Attrib<4, INOUT, FracInt, POINT> InOutPoint4fi;
typedef Attrib<4, TEMP, FracInt, POINT> Point4fi;
typedef Attrib<4, CONST, FracInt, POINT> ConstPoint4fi;


typedef Attrib<1, INPUT, unsigned int, POINT> InputPoint1ui;
typedef Attrib<1, OUTPUT, unsigned int, POINT> OutputPoint1ui;
typedef Attrib<1, INOUT, unsigned int, POINT> InOutPoint1ui;
typedef Attrib<1, TEMP, unsigned int, POINT> Point1ui;
typedef Attrib<1, CONST, unsigned int, POINT> ConstPoint1ui;
typedef Attrib<2, INPUT, unsigned int, POINT> InputPoint2ui;
typedef Attrib<2, OUTPUT, unsigned int, POINT> OutputPoint2ui;
typedef Attrib<2, INOUT, unsigned int, POINT> InOutPoint2ui;
typedef Attrib<2, TEMP, unsigned int, POINT> Point2ui;
typedef Attrib<2, CONST, unsigned int, POINT> ConstPoint2ui;
typedef Attrib<3, INPUT, unsigned int, POINT> InputPoint3ui;
typedef Attrib<3, OUTPUT, unsigned int, POINT> OutputPoint3ui;
typedef Attrib<3, INOUT, unsigned int, POINT> InOutPoint3ui;
typedef Attrib<3, TEMP, unsigned int, POINT> Point3ui;
typedef Attrib<3, CONST, unsigned int, POINT> ConstPoint3ui;
typedef Attrib<4, INPUT, unsigned int, POINT> InputPoint4ui;
typedef Attrib<4, OUTPUT, unsigned int, POINT> OutputPoint4ui;
typedef Attrib<4, INOUT, unsigned int, POINT> InOutPoint4ui;
typedef Attrib<4, TEMP, unsigned int, POINT> Point4ui;
typedef Attrib<4, CONST, unsigned int, POINT> ConstPoint4ui;



} // namespace SH

#endif // SHPOINT_HPP
