// WARNING - DO NOT EDIT THIS FILE:
// This file was automatically generated from scripts/Position.hpp.py.
// If you wish to change it, edit that file instead.
//
// ---
//
// Sh: A GPU metaprogramming language.
//
// Copyright 2003-2006 Serious Hack Inc.
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
// MA  02110-1301, USA
//////////////////////////////////////////////////////////////////////////////

#ifndef SHSHPOSITION_HPP
#define SHSHPOSITION_HPP

#include "Point.hpp"
namespace SH {

/** A vertex or fragment position.
 * 
 * This is semantically a point, but is bound preferentially to the position
 * input and output of the rasterizer or to the vertex position when
 * used in vertex and fragment shaders.
 * 
 *
 */

typedef Attrib<1, SH_INPUT, FracUShort, SH_POSITION> InputPosition1fus;
typedef Attrib<1, SH_OUTPUT, FracUShort, SH_POSITION> OutputPosition1fus;
typedef Attrib<1, SH_INOUT, FracUShort, SH_POSITION> InOutPosition1fus;
typedef Attrib<1, SH_TEMP, FracUShort, SH_POSITION> Position1fus;
typedef Attrib<1, SH_CONST, FracUShort, SH_POSITION> ConstPosition1fus;
typedef Attrib<2, SH_INPUT, FracUShort, SH_POSITION> InputPosition2fus;
typedef Attrib<2, SH_OUTPUT, FracUShort, SH_POSITION> OutputPosition2fus;
typedef Attrib<2, SH_INOUT, FracUShort, SH_POSITION> InOutPosition2fus;
typedef Attrib<2, SH_TEMP, FracUShort, SH_POSITION> Position2fus;
typedef Attrib<2, SH_CONST, FracUShort, SH_POSITION> ConstPosition2fus;
typedef Attrib<3, SH_INPUT, FracUShort, SH_POSITION> InputPosition3fus;
typedef Attrib<3, SH_OUTPUT, FracUShort, SH_POSITION> OutputPosition3fus;
typedef Attrib<3, SH_INOUT, FracUShort, SH_POSITION> InOutPosition3fus;
typedef Attrib<3, SH_TEMP, FracUShort, SH_POSITION> Position3fus;
typedef Attrib<3, SH_CONST, FracUShort, SH_POSITION> ConstPosition3fus;
typedef Attrib<4, SH_INPUT, FracUShort, SH_POSITION> InputPosition4fus;
typedef Attrib<4, SH_OUTPUT, FracUShort, SH_POSITION> OutputPosition4fus;
typedef Attrib<4, SH_INOUT, FracUShort, SH_POSITION> InOutPosition4fus;
typedef Attrib<4, SH_TEMP, FracUShort, SH_POSITION> Position4fus;
typedef Attrib<4, SH_CONST, FracUShort, SH_POSITION> ConstPosition4fus;


typedef Attrib<1, SH_INPUT, short, SH_POSITION> InputPosition1s;
typedef Attrib<1, SH_OUTPUT, short, SH_POSITION> OutputPosition1s;
typedef Attrib<1, SH_INOUT, short, SH_POSITION> InOutPosition1s;
typedef Attrib<1, SH_TEMP, short, SH_POSITION> Position1s;
typedef Attrib<1, SH_CONST, short, SH_POSITION> ConstPosition1s;
typedef Attrib<2, SH_INPUT, short, SH_POSITION> InputPosition2s;
typedef Attrib<2, SH_OUTPUT, short, SH_POSITION> OutputPosition2s;
typedef Attrib<2, SH_INOUT, short, SH_POSITION> InOutPosition2s;
typedef Attrib<2, SH_TEMP, short, SH_POSITION> Position2s;
typedef Attrib<2, SH_CONST, short, SH_POSITION> ConstPosition2s;
typedef Attrib<3, SH_INPUT, short, SH_POSITION> InputPosition3s;
typedef Attrib<3, SH_OUTPUT, short, SH_POSITION> OutputPosition3s;
typedef Attrib<3, SH_INOUT, short, SH_POSITION> InOutPosition3s;
typedef Attrib<3, SH_TEMP, short, SH_POSITION> Position3s;
typedef Attrib<3, SH_CONST, short, SH_POSITION> ConstPosition3s;
typedef Attrib<4, SH_INPUT, short, SH_POSITION> InputPosition4s;
typedef Attrib<4, SH_OUTPUT, short, SH_POSITION> OutputPosition4s;
typedef Attrib<4, SH_INOUT, short, SH_POSITION> InOutPosition4s;
typedef Attrib<4, SH_TEMP, short, SH_POSITION> Position4s;
typedef Attrib<4, SH_CONST, short, SH_POSITION> ConstPosition4s;


typedef Attrib<1, SH_INPUT, FracUInt, SH_POSITION> InputPosition1fui;
typedef Attrib<1, SH_OUTPUT, FracUInt, SH_POSITION> OutputPosition1fui;
typedef Attrib<1, SH_INOUT, FracUInt, SH_POSITION> InOutPosition1fui;
typedef Attrib<1, SH_TEMP, FracUInt, SH_POSITION> Position1fui;
typedef Attrib<1, SH_CONST, FracUInt, SH_POSITION> ConstPosition1fui;
typedef Attrib<2, SH_INPUT, FracUInt, SH_POSITION> InputPosition2fui;
typedef Attrib<2, SH_OUTPUT, FracUInt, SH_POSITION> OutputPosition2fui;
typedef Attrib<2, SH_INOUT, FracUInt, SH_POSITION> InOutPosition2fui;
typedef Attrib<2, SH_TEMP, FracUInt, SH_POSITION> Position2fui;
typedef Attrib<2, SH_CONST, FracUInt, SH_POSITION> ConstPosition2fui;
typedef Attrib<3, SH_INPUT, FracUInt, SH_POSITION> InputPosition3fui;
typedef Attrib<3, SH_OUTPUT, FracUInt, SH_POSITION> OutputPosition3fui;
typedef Attrib<3, SH_INOUT, FracUInt, SH_POSITION> InOutPosition3fui;
typedef Attrib<3, SH_TEMP, FracUInt, SH_POSITION> Position3fui;
typedef Attrib<3, SH_CONST, FracUInt, SH_POSITION> ConstPosition3fui;
typedef Attrib<4, SH_INPUT, FracUInt, SH_POSITION> InputPosition4fui;
typedef Attrib<4, SH_OUTPUT, FracUInt, SH_POSITION> OutputPosition4fui;
typedef Attrib<4, SH_INOUT, FracUInt, SH_POSITION> InOutPosition4fui;
typedef Attrib<4, SH_TEMP, FracUInt, SH_POSITION> Position4fui;
typedef Attrib<4, SH_CONST, FracUInt, SH_POSITION> ConstPosition4fui;


typedef Attrib<1, SH_INPUT, FracByte, SH_POSITION> InputPosition1fb;
typedef Attrib<1, SH_OUTPUT, FracByte, SH_POSITION> OutputPosition1fb;
typedef Attrib<1, SH_INOUT, FracByte, SH_POSITION> InOutPosition1fb;
typedef Attrib<1, SH_TEMP, FracByte, SH_POSITION> Position1fb;
typedef Attrib<1, SH_CONST, FracByte, SH_POSITION> ConstPosition1fb;
typedef Attrib<2, SH_INPUT, FracByte, SH_POSITION> InputPosition2fb;
typedef Attrib<2, SH_OUTPUT, FracByte, SH_POSITION> OutputPosition2fb;
typedef Attrib<2, SH_INOUT, FracByte, SH_POSITION> InOutPosition2fb;
typedef Attrib<2, SH_TEMP, FracByte, SH_POSITION> Position2fb;
typedef Attrib<2, SH_CONST, FracByte, SH_POSITION> ConstPosition2fb;
typedef Attrib<3, SH_INPUT, FracByte, SH_POSITION> InputPosition3fb;
typedef Attrib<3, SH_OUTPUT, FracByte, SH_POSITION> OutputPosition3fb;
typedef Attrib<3, SH_INOUT, FracByte, SH_POSITION> InOutPosition3fb;
typedef Attrib<3, SH_TEMP, FracByte, SH_POSITION> Position3fb;
typedef Attrib<3, SH_CONST, FracByte, SH_POSITION> ConstPosition3fb;
typedef Attrib<4, SH_INPUT, FracByte, SH_POSITION> InputPosition4fb;
typedef Attrib<4, SH_OUTPUT, FracByte, SH_POSITION> OutputPosition4fb;
typedef Attrib<4, SH_INOUT, FracByte, SH_POSITION> InOutPosition4fb;
typedef Attrib<4, SH_TEMP, FracByte, SH_POSITION> Position4fb;
typedef Attrib<4, SH_CONST, FracByte, SH_POSITION> ConstPosition4fb;


typedef Attrib<1, SH_INPUT, int, SH_POSITION> InputPosition1i;
typedef Attrib<1, SH_OUTPUT, int, SH_POSITION> OutputPosition1i;
typedef Attrib<1, SH_INOUT, int, SH_POSITION> InOutPosition1i;
typedef Attrib<1, SH_TEMP, int, SH_POSITION> Position1i;
typedef Attrib<1, SH_CONST, int, SH_POSITION> ConstPosition1i;
typedef Attrib<2, SH_INPUT, int, SH_POSITION> InputPosition2i;
typedef Attrib<2, SH_OUTPUT, int, SH_POSITION> OutputPosition2i;
typedef Attrib<2, SH_INOUT, int, SH_POSITION> InOutPosition2i;
typedef Attrib<2, SH_TEMP, int, SH_POSITION> Position2i;
typedef Attrib<2, SH_CONST, int, SH_POSITION> ConstPosition2i;
typedef Attrib<3, SH_INPUT, int, SH_POSITION> InputPosition3i;
typedef Attrib<3, SH_OUTPUT, int, SH_POSITION> OutputPosition3i;
typedef Attrib<3, SH_INOUT, int, SH_POSITION> InOutPosition3i;
typedef Attrib<3, SH_TEMP, int, SH_POSITION> Position3i;
typedef Attrib<3, SH_CONST, int, SH_POSITION> ConstPosition3i;
typedef Attrib<4, SH_INPUT, int, SH_POSITION> InputPosition4i;
typedef Attrib<4, SH_OUTPUT, int, SH_POSITION> OutputPosition4i;
typedef Attrib<4, SH_INOUT, int, SH_POSITION> InOutPosition4i;
typedef Attrib<4, SH_TEMP, int, SH_POSITION> Position4i;
typedef Attrib<4, SH_CONST, int, SH_POSITION> ConstPosition4i;


typedef Attrib<1, SH_INPUT, double, SH_POSITION> InputPosition1d;
typedef Attrib<1, SH_OUTPUT, double, SH_POSITION> OutputPosition1d;
typedef Attrib<1, SH_INOUT, double, SH_POSITION> InOutPosition1d;
typedef Attrib<1, SH_TEMP, double, SH_POSITION> Position1d;
typedef Attrib<1, SH_CONST, double, SH_POSITION> ConstPosition1d;
typedef Attrib<2, SH_INPUT, double, SH_POSITION> InputPosition2d;
typedef Attrib<2, SH_OUTPUT, double, SH_POSITION> OutputPosition2d;
typedef Attrib<2, SH_INOUT, double, SH_POSITION> InOutPosition2d;
typedef Attrib<2, SH_TEMP, double, SH_POSITION> Position2d;
typedef Attrib<2, SH_CONST, double, SH_POSITION> ConstPosition2d;
typedef Attrib<3, SH_INPUT, double, SH_POSITION> InputPosition3d;
typedef Attrib<3, SH_OUTPUT, double, SH_POSITION> OutputPosition3d;
typedef Attrib<3, SH_INOUT, double, SH_POSITION> InOutPosition3d;
typedef Attrib<3, SH_TEMP, double, SH_POSITION> Position3d;
typedef Attrib<3, SH_CONST, double, SH_POSITION> ConstPosition3d;
typedef Attrib<4, SH_INPUT, double, SH_POSITION> InputPosition4d;
typedef Attrib<4, SH_OUTPUT, double, SH_POSITION> OutputPosition4d;
typedef Attrib<4, SH_INOUT, double, SH_POSITION> InOutPosition4d;
typedef Attrib<4, SH_TEMP, double, SH_POSITION> Position4d;
typedef Attrib<4, SH_CONST, double, SH_POSITION> ConstPosition4d;


typedef Attrib<1, SH_INPUT, unsigned char, SH_POSITION> InputPosition1ub;
typedef Attrib<1, SH_OUTPUT, unsigned char, SH_POSITION> OutputPosition1ub;
typedef Attrib<1, SH_INOUT, unsigned char, SH_POSITION> InOutPosition1ub;
typedef Attrib<1, SH_TEMP, unsigned char, SH_POSITION> Position1ub;
typedef Attrib<1, SH_CONST, unsigned char, SH_POSITION> ConstPosition1ub;
typedef Attrib<2, SH_INPUT, unsigned char, SH_POSITION> InputPosition2ub;
typedef Attrib<2, SH_OUTPUT, unsigned char, SH_POSITION> OutputPosition2ub;
typedef Attrib<2, SH_INOUT, unsigned char, SH_POSITION> InOutPosition2ub;
typedef Attrib<2, SH_TEMP, unsigned char, SH_POSITION> Position2ub;
typedef Attrib<2, SH_CONST, unsigned char, SH_POSITION> ConstPosition2ub;
typedef Attrib<3, SH_INPUT, unsigned char, SH_POSITION> InputPosition3ub;
typedef Attrib<3, SH_OUTPUT, unsigned char, SH_POSITION> OutputPosition3ub;
typedef Attrib<3, SH_INOUT, unsigned char, SH_POSITION> InOutPosition3ub;
typedef Attrib<3, SH_TEMP, unsigned char, SH_POSITION> Position3ub;
typedef Attrib<3, SH_CONST, unsigned char, SH_POSITION> ConstPosition3ub;
typedef Attrib<4, SH_INPUT, unsigned char, SH_POSITION> InputPosition4ub;
typedef Attrib<4, SH_OUTPUT, unsigned char, SH_POSITION> OutputPosition4ub;
typedef Attrib<4, SH_INOUT, unsigned char, SH_POSITION> InOutPosition4ub;
typedef Attrib<4, SH_TEMP, unsigned char, SH_POSITION> Position4ub;
typedef Attrib<4, SH_CONST, unsigned char, SH_POSITION> ConstPosition4ub;


typedef Attrib<1, SH_INPUT, float, SH_POSITION> InputPosition1f;
typedef Attrib<1, SH_OUTPUT, float, SH_POSITION> OutputPosition1f;
typedef Attrib<1, SH_INOUT, float, SH_POSITION> InOutPosition1f;
typedef Attrib<1, SH_TEMP, float, SH_POSITION> Position1f;
typedef Attrib<1, SH_CONST, float, SH_POSITION> ConstPosition1f;
typedef Attrib<2, SH_INPUT, float, SH_POSITION> InputPosition2f;
typedef Attrib<2, SH_OUTPUT, float, SH_POSITION> OutputPosition2f;
typedef Attrib<2, SH_INOUT, float, SH_POSITION> InOutPosition2f;
typedef Attrib<2, SH_TEMP, float, SH_POSITION> Position2f;
typedef Attrib<2, SH_CONST, float, SH_POSITION> ConstPosition2f;
typedef Attrib<3, SH_INPUT, float, SH_POSITION> InputPosition3f;
typedef Attrib<3, SH_OUTPUT, float, SH_POSITION> OutputPosition3f;
typedef Attrib<3, SH_INOUT, float, SH_POSITION> InOutPosition3f;
typedef Attrib<3, SH_TEMP, float, SH_POSITION> Position3f;
typedef Attrib<3, SH_CONST, float, SH_POSITION> ConstPosition3f;
typedef Attrib<4, SH_INPUT, float, SH_POSITION> InputPosition4f;
typedef Attrib<4, SH_OUTPUT, float, SH_POSITION> OutputPosition4f;
typedef Attrib<4, SH_INOUT, float, SH_POSITION> InOutPosition4f;
typedef Attrib<4, SH_TEMP, float, SH_POSITION> Position4f;
typedef Attrib<4, SH_CONST, float, SH_POSITION> ConstPosition4f;


typedef Attrib<1, SH_INPUT, char, SH_POSITION> InputPosition1b;
typedef Attrib<1, SH_OUTPUT, char, SH_POSITION> OutputPosition1b;
typedef Attrib<1, SH_INOUT, char, SH_POSITION> InOutPosition1b;
typedef Attrib<1, SH_TEMP, char, SH_POSITION> Position1b;
typedef Attrib<1, SH_CONST, char, SH_POSITION> ConstPosition1b;
typedef Attrib<2, SH_INPUT, char, SH_POSITION> InputPosition2b;
typedef Attrib<2, SH_OUTPUT, char, SH_POSITION> OutputPosition2b;
typedef Attrib<2, SH_INOUT, char, SH_POSITION> InOutPosition2b;
typedef Attrib<2, SH_TEMP, char, SH_POSITION> Position2b;
typedef Attrib<2, SH_CONST, char, SH_POSITION> ConstPosition2b;
typedef Attrib<3, SH_INPUT, char, SH_POSITION> InputPosition3b;
typedef Attrib<3, SH_OUTPUT, char, SH_POSITION> OutputPosition3b;
typedef Attrib<3, SH_INOUT, char, SH_POSITION> InOutPosition3b;
typedef Attrib<3, SH_TEMP, char, SH_POSITION> Position3b;
typedef Attrib<3, SH_CONST, char, SH_POSITION> ConstPosition3b;
typedef Attrib<4, SH_INPUT, char, SH_POSITION> InputPosition4b;
typedef Attrib<4, SH_OUTPUT, char, SH_POSITION> OutputPosition4b;
typedef Attrib<4, SH_INOUT, char, SH_POSITION> InOutPosition4b;
typedef Attrib<4, SH_TEMP, char, SH_POSITION> Position4b;
typedef Attrib<4, SH_CONST, char, SH_POSITION> ConstPosition4b;


typedef Attrib<1, SH_INPUT, unsigned short, SH_POSITION> InputPosition1us;
typedef Attrib<1, SH_OUTPUT, unsigned short, SH_POSITION> OutputPosition1us;
typedef Attrib<1, SH_INOUT, unsigned short, SH_POSITION> InOutPosition1us;
typedef Attrib<1, SH_TEMP, unsigned short, SH_POSITION> Position1us;
typedef Attrib<1, SH_CONST, unsigned short, SH_POSITION> ConstPosition1us;
typedef Attrib<2, SH_INPUT, unsigned short, SH_POSITION> InputPosition2us;
typedef Attrib<2, SH_OUTPUT, unsigned short, SH_POSITION> OutputPosition2us;
typedef Attrib<2, SH_INOUT, unsigned short, SH_POSITION> InOutPosition2us;
typedef Attrib<2, SH_TEMP, unsigned short, SH_POSITION> Position2us;
typedef Attrib<2, SH_CONST, unsigned short, SH_POSITION> ConstPosition2us;
typedef Attrib<3, SH_INPUT, unsigned short, SH_POSITION> InputPosition3us;
typedef Attrib<3, SH_OUTPUT, unsigned short, SH_POSITION> OutputPosition3us;
typedef Attrib<3, SH_INOUT, unsigned short, SH_POSITION> InOutPosition3us;
typedef Attrib<3, SH_TEMP, unsigned short, SH_POSITION> Position3us;
typedef Attrib<3, SH_CONST, unsigned short, SH_POSITION> ConstPosition3us;
typedef Attrib<4, SH_INPUT, unsigned short, SH_POSITION> InputPosition4us;
typedef Attrib<4, SH_OUTPUT, unsigned short, SH_POSITION> OutputPosition4us;
typedef Attrib<4, SH_INOUT, unsigned short, SH_POSITION> InOutPosition4us;
typedef Attrib<4, SH_TEMP, unsigned short, SH_POSITION> Position4us;
typedef Attrib<4, SH_CONST, unsigned short, SH_POSITION> ConstPosition4us;


typedef Attrib<1, SH_INPUT, FracUByte, SH_POSITION> InputPosition1fub;
typedef Attrib<1, SH_OUTPUT, FracUByte, SH_POSITION> OutputPosition1fub;
typedef Attrib<1, SH_INOUT, FracUByte, SH_POSITION> InOutPosition1fub;
typedef Attrib<1, SH_TEMP, FracUByte, SH_POSITION> Position1fub;
typedef Attrib<1, SH_CONST, FracUByte, SH_POSITION> ConstPosition1fub;
typedef Attrib<2, SH_INPUT, FracUByte, SH_POSITION> InputPosition2fub;
typedef Attrib<2, SH_OUTPUT, FracUByte, SH_POSITION> OutputPosition2fub;
typedef Attrib<2, SH_INOUT, FracUByte, SH_POSITION> InOutPosition2fub;
typedef Attrib<2, SH_TEMP, FracUByte, SH_POSITION> Position2fub;
typedef Attrib<2, SH_CONST, FracUByte, SH_POSITION> ConstPosition2fub;
typedef Attrib<3, SH_INPUT, FracUByte, SH_POSITION> InputPosition3fub;
typedef Attrib<3, SH_OUTPUT, FracUByte, SH_POSITION> OutputPosition3fub;
typedef Attrib<3, SH_INOUT, FracUByte, SH_POSITION> InOutPosition3fub;
typedef Attrib<3, SH_TEMP, FracUByte, SH_POSITION> Position3fub;
typedef Attrib<3, SH_CONST, FracUByte, SH_POSITION> ConstPosition3fub;
typedef Attrib<4, SH_INPUT, FracUByte, SH_POSITION> InputPosition4fub;
typedef Attrib<4, SH_OUTPUT, FracUByte, SH_POSITION> OutputPosition4fub;
typedef Attrib<4, SH_INOUT, FracUByte, SH_POSITION> InOutPosition4fub;
typedef Attrib<4, SH_TEMP, FracUByte, SH_POSITION> Position4fub;
typedef Attrib<4, SH_CONST, FracUByte, SH_POSITION> ConstPosition4fub;


typedef Attrib<1, SH_INPUT, Half, SH_POSITION> InputPosition1h;
typedef Attrib<1, SH_OUTPUT, Half, SH_POSITION> OutputPosition1h;
typedef Attrib<1, SH_INOUT, Half, SH_POSITION> InOutPosition1h;
typedef Attrib<1, SH_TEMP, Half, SH_POSITION> Position1h;
typedef Attrib<1, SH_CONST, Half, SH_POSITION> ConstPosition1h;
typedef Attrib<2, SH_INPUT, Half, SH_POSITION> InputPosition2h;
typedef Attrib<2, SH_OUTPUT, Half, SH_POSITION> OutputPosition2h;
typedef Attrib<2, SH_INOUT, Half, SH_POSITION> InOutPosition2h;
typedef Attrib<2, SH_TEMP, Half, SH_POSITION> Position2h;
typedef Attrib<2, SH_CONST, Half, SH_POSITION> ConstPosition2h;
typedef Attrib<3, SH_INPUT, Half, SH_POSITION> InputPosition3h;
typedef Attrib<3, SH_OUTPUT, Half, SH_POSITION> OutputPosition3h;
typedef Attrib<3, SH_INOUT, Half, SH_POSITION> InOutPosition3h;
typedef Attrib<3, SH_TEMP, Half, SH_POSITION> Position3h;
typedef Attrib<3, SH_CONST, Half, SH_POSITION> ConstPosition3h;
typedef Attrib<4, SH_INPUT, Half, SH_POSITION> InputPosition4h;
typedef Attrib<4, SH_OUTPUT, Half, SH_POSITION> OutputPosition4h;
typedef Attrib<4, SH_INOUT, Half, SH_POSITION> InOutPosition4h;
typedef Attrib<4, SH_TEMP, Half, SH_POSITION> Position4h;
typedef Attrib<4, SH_CONST, Half, SH_POSITION> ConstPosition4h;


typedef Attrib<1, SH_INPUT, FracShort, SH_POSITION> InputPosition1fs;
typedef Attrib<1, SH_OUTPUT, FracShort, SH_POSITION> OutputPosition1fs;
typedef Attrib<1, SH_INOUT, FracShort, SH_POSITION> InOutPosition1fs;
typedef Attrib<1, SH_TEMP, FracShort, SH_POSITION> Position1fs;
typedef Attrib<1, SH_CONST, FracShort, SH_POSITION> ConstPosition1fs;
typedef Attrib<2, SH_INPUT, FracShort, SH_POSITION> InputPosition2fs;
typedef Attrib<2, SH_OUTPUT, FracShort, SH_POSITION> OutputPosition2fs;
typedef Attrib<2, SH_INOUT, FracShort, SH_POSITION> InOutPosition2fs;
typedef Attrib<2, SH_TEMP, FracShort, SH_POSITION> Position2fs;
typedef Attrib<2, SH_CONST, FracShort, SH_POSITION> ConstPosition2fs;
typedef Attrib<3, SH_INPUT, FracShort, SH_POSITION> InputPosition3fs;
typedef Attrib<3, SH_OUTPUT, FracShort, SH_POSITION> OutputPosition3fs;
typedef Attrib<3, SH_INOUT, FracShort, SH_POSITION> InOutPosition3fs;
typedef Attrib<3, SH_TEMP, FracShort, SH_POSITION> Position3fs;
typedef Attrib<3, SH_CONST, FracShort, SH_POSITION> ConstPosition3fs;
typedef Attrib<4, SH_INPUT, FracShort, SH_POSITION> InputPosition4fs;
typedef Attrib<4, SH_OUTPUT, FracShort, SH_POSITION> OutputPosition4fs;
typedef Attrib<4, SH_INOUT, FracShort, SH_POSITION> InOutPosition4fs;
typedef Attrib<4, SH_TEMP, FracShort, SH_POSITION> Position4fs;
typedef Attrib<4, SH_CONST, FracShort, SH_POSITION> ConstPosition4fs;


typedef Attrib<1, SH_INPUT, FracInt, SH_POSITION> InputPosition1fi;
typedef Attrib<1, SH_OUTPUT, FracInt, SH_POSITION> OutputPosition1fi;
typedef Attrib<1, SH_INOUT, FracInt, SH_POSITION> InOutPosition1fi;
typedef Attrib<1, SH_TEMP, FracInt, SH_POSITION> Position1fi;
typedef Attrib<1, SH_CONST, FracInt, SH_POSITION> ConstPosition1fi;
typedef Attrib<2, SH_INPUT, FracInt, SH_POSITION> InputPosition2fi;
typedef Attrib<2, SH_OUTPUT, FracInt, SH_POSITION> OutputPosition2fi;
typedef Attrib<2, SH_INOUT, FracInt, SH_POSITION> InOutPosition2fi;
typedef Attrib<2, SH_TEMP, FracInt, SH_POSITION> Position2fi;
typedef Attrib<2, SH_CONST, FracInt, SH_POSITION> ConstPosition2fi;
typedef Attrib<3, SH_INPUT, FracInt, SH_POSITION> InputPosition3fi;
typedef Attrib<3, SH_OUTPUT, FracInt, SH_POSITION> OutputPosition3fi;
typedef Attrib<3, SH_INOUT, FracInt, SH_POSITION> InOutPosition3fi;
typedef Attrib<3, SH_TEMP, FracInt, SH_POSITION> Position3fi;
typedef Attrib<3, SH_CONST, FracInt, SH_POSITION> ConstPosition3fi;
typedef Attrib<4, SH_INPUT, FracInt, SH_POSITION> InputPosition4fi;
typedef Attrib<4, SH_OUTPUT, FracInt, SH_POSITION> OutputPosition4fi;
typedef Attrib<4, SH_INOUT, FracInt, SH_POSITION> InOutPosition4fi;
typedef Attrib<4, SH_TEMP, FracInt, SH_POSITION> Position4fi;
typedef Attrib<4, SH_CONST, FracInt, SH_POSITION> ConstPosition4fi;


typedef Attrib<1, SH_INPUT, unsigned int, SH_POSITION> InputPosition1ui;
typedef Attrib<1, SH_OUTPUT, unsigned int, SH_POSITION> OutputPosition1ui;
typedef Attrib<1, SH_INOUT, unsigned int, SH_POSITION> InOutPosition1ui;
typedef Attrib<1, SH_TEMP, unsigned int, SH_POSITION> Position1ui;
typedef Attrib<1, SH_CONST, unsigned int, SH_POSITION> ConstPosition1ui;
typedef Attrib<2, SH_INPUT, unsigned int, SH_POSITION> InputPosition2ui;
typedef Attrib<2, SH_OUTPUT, unsigned int, SH_POSITION> OutputPosition2ui;
typedef Attrib<2, SH_INOUT, unsigned int, SH_POSITION> InOutPosition2ui;
typedef Attrib<2, SH_TEMP, unsigned int, SH_POSITION> Position2ui;
typedef Attrib<2, SH_CONST, unsigned int, SH_POSITION> ConstPosition2ui;
typedef Attrib<3, SH_INPUT, unsigned int, SH_POSITION> InputPosition3ui;
typedef Attrib<3, SH_OUTPUT, unsigned int, SH_POSITION> OutputPosition3ui;
typedef Attrib<3, SH_INOUT, unsigned int, SH_POSITION> InOutPosition3ui;
typedef Attrib<3, SH_TEMP, unsigned int, SH_POSITION> Position3ui;
typedef Attrib<3, SH_CONST, unsigned int, SH_POSITION> ConstPosition3ui;
typedef Attrib<4, SH_INPUT, unsigned int, SH_POSITION> InputPosition4ui;
typedef Attrib<4, SH_OUTPUT, unsigned int, SH_POSITION> OutputPosition4ui;
typedef Attrib<4, SH_INOUT, unsigned int, SH_POSITION> InOutPosition4ui;
typedef Attrib<4, SH_TEMP, unsigned int, SH_POSITION> Position4ui;
typedef Attrib<4, SH_CONST, unsigned int, SH_POSITION> ConstPosition4ui;



} // namespace SH

#endif // SHSHPOSITION_HPP
