// WARNING - DO NOT EDIT THIS FILE:
// This file was automatically generated from scripts/TexCoord.hpp.py.
// If you wish to change it, edit that file instead.
//
// ---
//
// Sh: A GPU metaprogramming language.
//
// Copyright 2003-2006 Serious Hack Inc.
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
// MA  02110-1301, USA
//////////////////////////////////////////////////////////////////////////////

#ifndef SHSHTEXCOORD_HPP
#define SHSHTEXCOORD_HPP

#include "Attrib.hpp"
namespace SH {

/** A texture coordinate.
 * 
 *
 */

typedef Attrib<1, SH_INPUT, FracUShort, SH_TEXCOORD> InputTexCoord1fus;
typedef Attrib<1, SH_OUTPUT, FracUShort, SH_TEXCOORD> OutputTexCoord1fus;
typedef Attrib<1, SH_INOUT, FracUShort, SH_TEXCOORD> InOutTexCoord1fus;
typedef Attrib<1, SH_TEMP, FracUShort, SH_TEXCOORD> TexCoord1fus;
typedef Attrib<1, SH_CONST, FracUShort, SH_TEXCOORD> ConstTexCoord1fus;
typedef Attrib<2, SH_INPUT, FracUShort, SH_TEXCOORD> InputTexCoord2fus;
typedef Attrib<2, SH_OUTPUT, FracUShort, SH_TEXCOORD> OutputTexCoord2fus;
typedef Attrib<2, SH_INOUT, FracUShort, SH_TEXCOORD> InOutTexCoord2fus;
typedef Attrib<2, SH_TEMP, FracUShort, SH_TEXCOORD> TexCoord2fus;
typedef Attrib<2, SH_CONST, FracUShort, SH_TEXCOORD> ConstTexCoord2fus;
typedef Attrib<3, SH_INPUT, FracUShort, SH_TEXCOORD> InputTexCoord3fus;
typedef Attrib<3, SH_OUTPUT, FracUShort, SH_TEXCOORD> OutputTexCoord3fus;
typedef Attrib<3, SH_INOUT, FracUShort, SH_TEXCOORD> InOutTexCoord3fus;
typedef Attrib<3, SH_TEMP, FracUShort, SH_TEXCOORD> TexCoord3fus;
typedef Attrib<3, SH_CONST, FracUShort, SH_TEXCOORD> ConstTexCoord3fus;
typedef Attrib<4, SH_INPUT, FracUShort, SH_TEXCOORD> InputTexCoord4fus;
typedef Attrib<4, SH_OUTPUT, FracUShort, SH_TEXCOORD> OutputTexCoord4fus;
typedef Attrib<4, SH_INOUT, FracUShort, SH_TEXCOORD> InOutTexCoord4fus;
typedef Attrib<4, SH_TEMP, FracUShort, SH_TEXCOORD> TexCoord4fus;
typedef Attrib<4, SH_CONST, FracUShort, SH_TEXCOORD> ConstTexCoord4fus;


typedef Attrib<1, SH_INPUT, short, SH_TEXCOORD> InputTexCoord1s;
typedef Attrib<1, SH_OUTPUT, short, SH_TEXCOORD> OutputTexCoord1s;
typedef Attrib<1, SH_INOUT, short, SH_TEXCOORD> InOutTexCoord1s;
typedef Attrib<1, SH_TEMP, short, SH_TEXCOORD> TexCoord1s;
typedef Attrib<1, SH_CONST, short, SH_TEXCOORD> ConstTexCoord1s;
typedef Attrib<2, SH_INPUT, short, SH_TEXCOORD> InputTexCoord2s;
typedef Attrib<2, SH_OUTPUT, short, SH_TEXCOORD> OutputTexCoord2s;
typedef Attrib<2, SH_INOUT, short, SH_TEXCOORD> InOutTexCoord2s;
typedef Attrib<2, SH_TEMP, short, SH_TEXCOORD> TexCoord2s;
typedef Attrib<2, SH_CONST, short, SH_TEXCOORD> ConstTexCoord2s;
typedef Attrib<3, SH_INPUT, short, SH_TEXCOORD> InputTexCoord3s;
typedef Attrib<3, SH_OUTPUT, short, SH_TEXCOORD> OutputTexCoord3s;
typedef Attrib<3, SH_INOUT, short, SH_TEXCOORD> InOutTexCoord3s;
typedef Attrib<3, SH_TEMP, short, SH_TEXCOORD> TexCoord3s;
typedef Attrib<3, SH_CONST, short, SH_TEXCOORD> ConstTexCoord3s;
typedef Attrib<4, SH_INPUT, short, SH_TEXCOORD> InputTexCoord4s;
typedef Attrib<4, SH_OUTPUT, short, SH_TEXCOORD> OutputTexCoord4s;
typedef Attrib<4, SH_INOUT, short, SH_TEXCOORD> InOutTexCoord4s;
typedef Attrib<4, SH_TEMP, short, SH_TEXCOORD> TexCoord4s;
typedef Attrib<4, SH_CONST, short, SH_TEXCOORD> ConstTexCoord4s;


typedef Attrib<1, SH_INPUT, FracUInt, SH_TEXCOORD> InputTexCoord1fui;
typedef Attrib<1, SH_OUTPUT, FracUInt, SH_TEXCOORD> OutputTexCoord1fui;
typedef Attrib<1, SH_INOUT, FracUInt, SH_TEXCOORD> InOutTexCoord1fui;
typedef Attrib<1, SH_TEMP, FracUInt, SH_TEXCOORD> TexCoord1fui;
typedef Attrib<1, SH_CONST, FracUInt, SH_TEXCOORD> ConstTexCoord1fui;
typedef Attrib<2, SH_INPUT, FracUInt, SH_TEXCOORD> InputTexCoord2fui;
typedef Attrib<2, SH_OUTPUT, FracUInt, SH_TEXCOORD> OutputTexCoord2fui;
typedef Attrib<2, SH_INOUT, FracUInt, SH_TEXCOORD> InOutTexCoord2fui;
typedef Attrib<2, SH_TEMP, FracUInt, SH_TEXCOORD> TexCoord2fui;
typedef Attrib<2, SH_CONST, FracUInt, SH_TEXCOORD> ConstTexCoord2fui;
typedef Attrib<3, SH_INPUT, FracUInt, SH_TEXCOORD> InputTexCoord3fui;
typedef Attrib<3, SH_OUTPUT, FracUInt, SH_TEXCOORD> OutputTexCoord3fui;
typedef Attrib<3, SH_INOUT, FracUInt, SH_TEXCOORD> InOutTexCoord3fui;
typedef Attrib<3, SH_TEMP, FracUInt, SH_TEXCOORD> TexCoord3fui;
typedef Attrib<3, SH_CONST, FracUInt, SH_TEXCOORD> ConstTexCoord3fui;
typedef Attrib<4, SH_INPUT, FracUInt, SH_TEXCOORD> InputTexCoord4fui;
typedef Attrib<4, SH_OUTPUT, FracUInt, SH_TEXCOORD> OutputTexCoord4fui;
typedef Attrib<4, SH_INOUT, FracUInt, SH_TEXCOORD> InOutTexCoord4fui;
typedef Attrib<4, SH_TEMP, FracUInt, SH_TEXCOORD> TexCoord4fui;
typedef Attrib<4, SH_CONST, FracUInt, SH_TEXCOORD> ConstTexCoord4fui;


typedef Attrib<1, SH_INPUT, FracByte, SH_TEXCOORD> InputTexCoord1fb;
typedef Attrib<1, SH_OUTPUT, FracByte, SH_TEXCOORD> OutputTexCoord1fb;
typedef Attrib<1, SH_INOUT, FracByte, SH_TEXCOORD> InOutTexCoord1fb;
typedef Attrib<1, SH_TEMP, FracByte, SH_TEXCOORD> TexCoord1fb;
typedef Attrib<1, SH_CONST, FracByte, SH_TEXCOORD> ConstTexCoord1fb;
typedef Attrib<2, SH_INPUT, FracByte, SH_TEXCOORD> InputTexCoord2fb;
typedef Attrib<2, SH_OUTPUT, FracByte, SH_TEXCOORD> OutputTexCoord2fb;
typedef Attrib<2, SH_INOUT, FracByte, SH_TEXCOORD> InOutTexCoord2fb;
typedef Attrib<2, SH_TEMP, FracByte, SH_TEXCOORD> TexCoord2fb;
typedef Attrib<2, SH_CONST, FracByte, SH_TEXCOORD> ConstTexCoord2fb;
typedef Attrib<3, SH_INPUT, FracByte, SH_TEXCOORD> InputTexCoord3fb;
typedef Attrib<3, SH_OUTPUT, FracByte, SH_TEXCOORD> OutputTexCoord3fb;
typedef Attrib<3, SH_INOUT, FracByte, SH_TEXCOORD> InOutTexCoord3fb;
typedef Attrib<3, SH_TEMP, FracByte, SH_TEXCOORD> TexCoord3fb;
typedef Attrib<3, SH_CONST, FracByte, SH_TEXCOORD> ConstTexCoord3fb;
typedef Attrib<4, SH_INPUT, FracByte, SH_TEXCOORD> InputTexCoord4fb;
typedef Attrib<4, SH_OUTPUT, FracByte, SH_TEXCOORD> OutputTexCoord4fb;
typedef Attrib<4, SH_INOUT, FracByte, SH_TEXCOORD> InOutTexCoord4fb;
typedef Attrib<4, SH_TEMP, FracByte, SH_TEXCOORD> TexCoord4fb;
typedef Attrib<4, SH_CONST, FracByte, SH_TEXCOORD> ConstTexCoord4fb;


typedef Attrib<1, SH_INPUT, int, SH_TEXCOORD> InputTexCoord1i;
typedef Attrib<1, SH_OUTPUT, int, SH_TEXCOORD> OutputTexCoord1i;
typedef Attrib<1, SH_INOUT, int, SH_TEXCOORD> InOutTexCoord1i;
typedef Attrib<1, SH_TEMP, int, SH_TEXCOORD> TexCoord1i;
typedef Attrib<1, SH_CONST, int, SH_TEXCOORD> ConstTexCoord1i;
typedef Attrib<2, SH_INPUT, int, SH_TEXCOORD> InputTexCoord2i;
typedef Attrib<2, SH_OUTPUT, int, SH_TEXCOORD> OutputTexCoord2i;
typedef Attrib<2, SH_INOUT, int, SH_TEXCOORD> InOutTexCoord2i;
typedef Attrib<2, SH_TEMP, int, SH_TEXCOORD> TexCoord2i;
typedef Attrib<2, SH_CONST, int, SH_TEXCOORD> ConstTexCoord2i;
typedef Attrib<3, SH_INPUT, int, SH_TEXCOORD> InputTexCoord3i;
typedef Attrib<3, SH_OUTPUT, int, SH_TEXCOORD> OutputTexCoord3i;
typedef Attrib<3, SH_INOUT, int, SH_TEXCOORD> InOutTexCoord3i;
typedef Attrib<3, SH_TEMP, int, SH_TEXCOORD> TexCoord3i;
typedef Attrib<3, SH_CONST, int, SH_TEXCOORD> ConstTexCoord3i;
typedef Attrib<4, SH_INPUT, int, SH_TEXCOORD> InputTexCoord4i;
typedef Attrib<4, SH_OUTPUT, int, SH_TEXCOORD> OutputTexCoord4i;
typedef Attrib<4, SH_INOUT, int, SH_TEXCOORD> InOutTexCoord4i;
typedef Attrib<4, SH_TEMP, int, SH_TEXCOORD> TexCoord4i;
typedef Attrib<4, SH_CONST, int, SH_TEXCOORD> ConstTexCoord4i;


typedef Attrib<1, SH_INPUT, double, SH_TEXCOORD> InputTexCoord1d;
typedef Attrib<1, SH_OUTPUT, double, SH_TEXCOORD> OutputTexCoord1d;
typedef Attrib<1, SH_INOUT, double, SH_TEXCOORD> InOutTexCoord1d;
typedef Attrib<1, SH_TEMP, double, SH_TEXCOORD> TexCoord1d;
typedef Attrib<1, SH_CONST, double, SH_TEXCOORD> ConstTexCoord1d;
typedef Attrib<2, SH_INPUT, double, SH_TEXCOORD> InputTexCoord2d;
typedef Attrib<2, SH_OUTPUT, double, SH_TEXCOORD> OutputTexCoord2d;
typedef Attrib<2, SH_INOUT, double, SH_TEXCOORD> InOutTexCoord2d;
typedef Attrib<2, SH_TEMP, double, SH_TEXCOORD> TexCoord2d;
typedef Attrib<2, SH_CONST, double, SH_TEXCOORD> ConstTexCoord2d;
typedef Attrib<3, SH_INPUT, double, SH_TEXCOORD> InputTexCoord3d;
typedef Attrib<3, SH_OUTPUT, double, SH_TEXCOORD> OutputTexCoord3d;
typedef Attrib<3, SH_INOUT, double, SH_TEXCOORD> InOutTexCoord3d;
typedef Attrib<3, SH_TEMP, double, SH_TEXCOORD> TexCoord3d;
typedef Attrib<3, SH_CONST, double, SH_TEXCOORD> ConstTexCoord3d;
typedef Attrib<4, SH_INPUT, double, SH_TEXCOORD> InputTexCoord4d;
typedef Attrib<4, SH_OUTPUT, double, SH_TEXCOORD> OutputTexCoord4d;
typedef Attrib<4, SH_INOUT, double, SH_TEXCOORD> InOutTexCoord4d;
typedef Attrib<4, SH_TEMP, double, SH_TEXCOORD> TexCoord4d;
typedef Attrib<4, SH_CONST, double, SH_TEXCOORD> ConstTexCoord4d;


typedef Attrib<1, SH_INPUT, unsigned char, SH_TEXCOORD> InputTexCoord1ub;
typedef Attrib<1, SH_OUTPUT, unsigned char, SH_TEXCOORD> OutputTexCoord1ub;
typedef Attrib<1, SH_INOUT, unsigned char, SH_TEXCOORD> InOutTexCoord1ub;
typedef Attrib<1, SH_TEMP, unsigned char, SH_TEXCOORD> TexCoord1ub;
typedef Attrib<1, SH_CONST, unsigned char, SH_TEXCOORD> ConstTexCoord1ub;
typedef Attrib<2, SH_INPUT, unsigned char, SH_TEXCOORD> InputTexCoord2ub;
typedef Attrib<2, SH_OUTPUT, unsigned char, SH_TEXCOORD> OutputTexCoord2ub;
typedef Attrib<2, SH_INOUT, unsigned char, SH_TEXCOORD> InOutTexCoord2ub;
typedef Attrib<2, SH_TEMP, unsigned char, SH_TEXCOORD> TexCoord2ub;
typedef Attrib<2, SH_CONST, unsigned char, SH_TEXCOORD> ConstTexCoord2ub;
typedef Attrib<3, SH_INPUT, unsigned char, SH_TEXCOORD> InputTexCoord3ub;
typedef Attrib<3, SH_OUTPUT, unsigned char, SH_TEXCOORD> OutputTexCoord3ub;
typedef Attrib<3, SH_INOUT, unsigned char, SH_TEXCOORD> InOutTexCoord3ub;
typedef Attrib<3, SH_TEMP, unsigned char, SH_TEXCOORD> TexCoord3ub;
typedef Attrib<3, SH_CONST, unsigned char, SH_TEXCOORD> ConstTexCoord3ub;
typedef Attrib<4, SH_INPUT, unsigned char, SH_TEXCOORD> InputTexCoord4ub;
typedef Attrib<4, SH_OUTPUT, unsigned char, SH_TEXCOORD> OutputTexCoord4ub;
typedef Attrib<4, SH_INOUT, unsigned char, SH_TEXCOORD> InOutTexCoord4ub;
typedef Attrib<4, SH_TEMP, unsigned char, SH_TEXCOORD> TexCoord4ub;
typedef Attrib<4, SH_CONST, unsigned char, SH_TEXCOORD> ConstTexCoord4ub;


typedef Attrib<1, SH_INPUT, float, SH_TEXCOORD> InputTexCoord1f;
typedef Attrib<1, SH_OUTPUT, float, SH_TEXCOORD> OutputTexCoord1f;
typedef Attrib<1, SH_INOUT, float, SH_TEXCOORD> InOutTexCoord1f;
typedef Attrib<1, SH_TEMP, float, SH_TEXCOORD> TexCoord1f;
typedef Attrib<1, SH_CONST, float, SH_TEXCOORD> ConstTexCoord1f;
typedef Attrib<2, SH_INPUT, float, SH_TEXCOORD> InputTexCoord2f;
typedef Attrib<2, SH_OUTPUT, float, SH_TEXCOORD> OutputTexCoord2f;
typedef Attrib<2, SH_INOUT, float, SH_TEXCOORD> InOutTexCoord2f;
typedef Attrib<2, SH_TEMP, float, SH_TEXCOORD> TexCoord2f;
typedef Attrib<2, SH_CONST, float, SH_TEXCOORD> ConstTexCoord2f;
typedef Attrib<3, SH_INPUT, float, SH_TEXCOORD> InputTexCoord3f;
typedef Attrib<3, SH_OUTPUT, float, SH_TEXCOORD> OutputTexCoord3f;
typedef Attrib<3, SH_INOUT, float, SH_TEXCOORD> InOutTexCoord3f;
typedef Attrib<3, SH_TEMP, float, SH_TEXCOORD> TexCoord3f;
typedef Attrib<3, SH_CONST, float, SH_TEXCOORD> ConstTexCoord3f;
typedef Attrib<4, SH_INPUT, float, SH_TEXCOORD> InputTexCoord4f;
typedef Attrib<4, SH_OUTPUT, float, SH_TEXCOORD> OutputTexCoord4f;
typedef Attrib<4, SH_INOUT, float, SH_TEXCOORD> InOutTexCoord4f;
typedef Attrib<4, SH_TEMP, float, SH_TEXCOORD> TexCoord4f;
typedef Attrib<4, SH_CONST, float, SH_TEXCOORD> ConstTexCoord4f;


typedef Attrib<1, SH_INPUT, char, SH_TEXCOORD> InputTexCoord1b;
typedef Attrib<1, SH_OUTPUT, char, SH_TEXCOORD> OutputTexCoord1b;
typedef Attrib<1, SH_INOUT, char, SH_TEXCOORD> InOutTexCoord1b;
typedef Attrib<1, SH_TEMP, char, SH_TEXCOORD> TexCoord1b;
typedef Attrib<1, SH_CONST, char, SH_TEXCOORD> ConstTexCoord1b;
typedef Attrib<2, SH_INPUT, char, SH_TEXCOORD> InputTexCoord2b;
typedef Attrib<2, SH_OUTPUT, char, SH_TEXCOORD> OutputTexCoord2b;
typedef Attrib<2, SH_INOUT, char, SH_TEXCOORD> InOutTexCoord2b;
typedef Attrib<2, SH_TEMP, char, SH_TEXCOORD> TexCoord2b;
typedef Attrib<2, SH_CONST, char, SH_TEXCOORD> ConstTexCoord2b;
typedef Attrib<3, SH_INPUT, char, SH_TEXCOORD> InputTexCoord3b;
typedef Attrib<3, SH_OUTPUT, char, SH_TEXCOORD> OutputTexCoord3b;
typedef Attrib<3, SH_INOUT, char, SH_TEXCOORD> InOutTexCoord3b;
typedef Attrib<3, SH_TEMP, char, SH_TEXCOORD> TexCoord3b;
typedef Attrib<3, SH_CONST, char, SH_TEXCOORD> ConstTexCoord3b;
typedef Attrib<4, SH_INPUT, char, SH_TEXCOORD> InputTexCoord4b;
typedef Attrib<4, SH_OUTPUT, char, SH_TEXCOORD> OutputTexCoord4b;
typedef Attrib<4, SH_INOUT, char, SH_TEXCOORD> InOutTexCoord4b;
typedef Attrib<4, SH_TEMP, char, SH_TEXCOORD> TexCoord4b;
typedef Attrib<4, SH_CONST, char, SH_TEXCOORD> ConstTexCoord4b;


typedef Attrib<1, SH_INPUT, unsigned short, SH_TEXCOORD> InputTexCoord1us;
typedef Attrib<1, SH_OUTPUT, unsigned short, SH_TEXCOORD> OutputTexCoord1us;
typedef Attrib<1, SH_INOUT, unsigned short, SH_TEXCOORD> InOutTexCoord1us;
typedef Attrib<1, SH_TEMP, unsigned short, SH_TEXCOORD> TexCoord1us;
typedef Attrib<1, SH_CONST, unsigned short, SH_TEXCOORD> ConstTexCoord1us;
typedef Attrib<2, SH_INPUT, unsigned short, SH_TEXCOORD> InputTexCoord2us;
typedef Attrib<2, SH_OUTPUT, unsigned short, SH_TEXCOORD> OutputTexCoord2us;
typedef Attrib<2, SH_INOUT, unsigned short, SH_TEXCOORD> InOutTexCoord2us;
typedef Attrib<2, SH_TEMP, unsigned short, SH_TEXCOORD> TexCoord2us;
typedef Attrib<2, SH_CONST, unsigned short, SH_TEXCOORD> ConstTexCoord2us;
typedef Attrib<3, SH_INPUT, unsigned short, SH_TEXCOORD> InputTexCoord3us;
typedef Attrib<3, SH_OUTPUT, unsigned short, SH_TEXCOORD> OutputTexCoord3us;
typedef Attrib<3, SH_INOUT, unsigned short, SH_TEXCOORD> InOutTexCoord3us;
typedef Attrib<3, SH_TEMP, unsigned short, SH_TEXCOORD> TexCoord3us;
typedef Attrib<3, SH_CONST, unsigned short, SH_TEXCOORD> ConstTexCoord3us;
typedef Attrib<4, SH_INPUT, unsigned short, SH_TEXCOORD> InputTexCoord4us;
typedef Attrib<4, SH_OUTPUT, unsigned short, SH_TEXCOORD> OutputTexCoord4us;
typedef Attrib<4, SH_INOUT, unsigned short, SH_TEXCOORD> InOutTexCoord4us;
typedef Attrib<4, SH_TEMP, unsigned short, SH_TEXCOORD> TexCoord4us;
typedef Attrib<4, SH_CONST, unsigned short, SH_TEXCOORD> ConstTexCoord4us;


typedef Attrib<1, SH_INPUT, FracUByte, SH_TEXCOORD> InputTexCoord1fub;
typedef Attrib<1, SH_OUTPUT, FracUByte, SH_TEXCOORD> OutputTexCoord1fub;
typedef Attrib<1, SH_INOUT, FracUByte, SH_TEXCOORD> InOutTexCoord1fub;
typedef Attrib<1, SH_TEMP, FracUByte, SH_TEXCOORD> TexCoord1fub;
typedef Attrib<1, SH_CONST, FracUByte, SH_TEXCOORD> ConstTexCoord1fub;
typedef Attrib<2, SH_INPUT, FracUByte, SH_TEXCOORD> InputTexCoord2fub;
typedef Attrib<2, SH_OUTPUT, FracUByte, SH_TEXCOORD> OutputTexCoord2fub;
typedef Attrib<2, SH_INOUT, FracUByte, SH_TEXCOORD> InOutTexCoord2fub;
typedef Attrib<2, SH_TEMP, FracUByte, SH_TEXCOORD> TexCoord2fub;
typedef Attrib<2, SH_CONST, FracUByte, SH_TEXCOORD> ConstTexCoord2fub;
typedef Attrib<3, SH_INPUT, FracUByte, SH_TEXCOORD> InputTexCoord3fub;
typedef Attrib<3, SH_OUTPUT, FracUByte, SH_TEXCOORD> OutputTexCoord3fub;
typedef Attrib<3, SH_INOUT, FracUByte, SH_TEXCOORD> InOutTexCoord3fub;
typedef Attrib<3, SH_TEMP, FracUByte, SH_TEXCOORD> TexCoord3fub;
typedef Attrib<3, SH_CONST, FracUByte, SH_TEXCOORD> ConstTexCoord3fub;
typedef Attrib<4, SH_INPUT, FracUByte, SH_TEXCOORD> InputTexCoord4fub;
typedef Attrib<4, SH_OUTPUT, FracUByte, SH_TEXCOORD> OutputTexCoord4fub;
typedef Attrib<4, SH_INOUT, FracUByte, SH_TEXCOORD> InOutTexCoord4fub;
typedef Attrib<4, SH_TEMP, FracUByte, SH_TEXCOORD> TexCoord4fub;
typedef Attrib<4, SH_CONST, FracUByte, SH_TEXCOORD> ConstTexCoord4fub;


typedef Attrib<1, SH_INPUT, Half, SH_TEXCOORD> InputTexCoord1h;
typedef Attrib<1, SH_OUTPUT, Half, SH_TEXCOORD> OutputTexCoord1h;
typedef Attrib<1, SH_INOUT, Half, SH_TEXCOORD> InOutTexCoord1h;
typedef Attrib<1, SH_TEMP, Half, SH_TEXCOORD> TexCoord1h;
typedef Attrib<1, SH_CONST, Half, SH_TEXCOORD> ConstTexCoord1h;
typedef Attrib<2, SH_INPUT, Half, SH_TEXCOORD> InputTexCoord2h;
typedef Attrib<2, SH_OUTPUT, Half, SH_TEXCOORD> OutputTexCoord2h;
typedef Attrib<2, SH_INOUT, Half, SH_TEXCOORD> InOutTexCoord2h;
typedef Attrib<2, SH_TEMP, Half, SH_TEXCOORD> TexCoord2h;
typedef Attrib<2, SH_CONST, Half, SH_TEXCOORD> ConstTexCoord2h;
typedef Attrib<3, SH_INPUT, Half, SH_TEXCOORD> InputTexCoord3h;
typedef Attrib<3, SH_OUTPUT, Half, SH_TEXCOORD> OutputTexCoord3h;
typedef Attrib<3, SH_INOUT, Half, SH_TEXCOORD> InOutTexCoord3h;
typedef Attrib<3, SH_TEMP, Half, SH_TEXCOORD> TexCoord3h;
typedef Attrib<3, SH_CONST, Half, SH_TEXCOORD> ConstTexCoord3h;
typedef Attrib<4, SH_INPUT, Half, SH_TEXCOORD> InputTexCoord4h;
typedef Attrib<4, SH_OUTPUT, Half, SH_TEXCOORD> OutputTexCoord4h;
typedef Attrib<4, SH_INOUT, Half, SH_TEXCOORD> InOutTexCoord4h;
typedef Attrib<4, SH_TEMP, Half, SH_TEXCOORD> TexCoord4h;
typedef Attrib<4, SH_CONST, Half, SH_TEXCOORD> ConstTexCoord4h;


typedef Attrib<1, SH_INPUT, FracShort, SH_TEXCOORD> InputTexCoord1fs;
typedef Attrib<1, SH_OUTPUT, FracShort, SH_TEXCOORD> OutputTexCoord1fs;
typedef Attrib<1, SH_INOUT, FracShort, SH_TEXCOORD> InOutTexCoord1fs;
typedef Attrib<1, SH_TEMP, FracShort, SH_TEXCOORD> TexCoord1fs;
typedef Attrib<1, SH_CONST, FracShort, SH_TEXCOORD> ConstTexCoord1fs;
typedef Attrib<2, SH_INPUT, FracShort, SH_TEXCOORD> InputTexCoord2fs;
typedef Attrib<2, SH_OUTPUT, FracShort, SH_TEXCOORD> OutputTexCoord2fs;
typedef Attrib<2, SH_INOUT, FracShort, SH_TEXCOORD> InOutTexCoord2fs;
typedef Attrib<2, SH_TEMP, FracShort, SH_TEXCOORD> TexCoord2fs;
typedef Attrib<2, SH_CONST, FracShort, SH_TEXCOORD> ConstTexCoord2fs;
typedef Attrib<3, SH_INPUT, FracShort, SH_TEXCOORD> InputTexCoord3fs;
typedef Attrib<3, SH_OUTPUT, FracShort, SH_TEXCOORD> OutputTexCoord3fs;
typedef Attrib<3, SH_INOUT, FracShort, SH_TEXCOORD> InOutTexCoord3fs;
typedef Attrib<3, SH_TEMP, FracShort, SH_TEXCOORD> TexCoord3fs;
typedef Attrib<3, SH_CONST, FracShort, SH_TEXCOORD> ConstTexCoord3fs;
typedef Attrib<4, SH_INPUT, FracShort, SH_TEXCOORD> InputTexCoord4fs;
typedef Attrib<4, SH_OUTPUT, FracShort, SH_TEXCOORD> OutputTexCoord4fs;
typedef Attrib<4, SH_INOUT, FracShort, SH_TEXCOORD> InOutTexCoord4fs;
typedef Attrib<4, SH_TEMP, FracShort, SH_TEXCOORD> TexCoord4fs;
typedef Attrib<4, SH_CONST, FracShort, SH_TEXCOORD> ConstTexCoord4fs;


typedef Attrib<1, SH_INPUT, FracInt, SH_TEXCOORD> InputTexCoord1fi;
typedef Attrib<1, SH_OUTPUT, FracInt, SH_TEXCOORD> OutputTexCoord1fi;
typedef Attrib<1, SH_INOUT, FracInt, SH_TEXCOORD> InOutTexCoord1fi;
typedef Attrib<1, SH_TEMP, FracInt, SH_TEXCOORD> TexCoord1fi;
typedef Attrib<1, SH_CONST, FracInt, SH_TEXCOORD> ConstTexCoord1fi;
typedef Attrib<2, SH_INPUT, FracInt, SH_TEXCOORD> InputTexCoord2fi;
typedef Attrib<2, SH_OUTPUT, FracInt, SH_TEXCOORD> OutputTexCoord2fi;
typedef Attrib<2, SH_INOUT, FracInt, SH_TEXCOORD> InOutTexCoord2fi;
typedef Attrib<2, SH_TEMP, FracInt, SH_TEXCOORD> TexCoord2fi;
typedef Attrib<2, SH_CONST, FracInt, SH_TEXCOORD> ConstTexCoord2fi;
typedef Attrib<3, SH_INPUT, FracInt, SH_TEXCOORD> InputTexCoord3fi;
typedef Attrib<3, SH_OUTPUT, FracInt, SH_TEXCOORD> OutputTexCoord3fi;
typedef Attrib<3, SH_INOUT, FracInt, SH_TEXCOORD> InOutTexCoord3fi;
typedef Attrib<3, SH_TEMP, FracInt, SH_TEXCOORD> TexCoord3fi;
typedef Attrib<3, SH_CONST, FracInt, SH_TEXCOORD> ConstTexCoord3fi;
typedef Attrib<4, SH_INPUT, FracInt, SH_TEXCOORD> InputTexCoord4fi;
typedef Attrib<4, SH_OUTPUT, FracInt, SH_TEXCOORD> OutputTexCoord4fi;
typedef Attrib<4, SH_INOUT, FracInt, SH_TEXCOORD> InOutTexCoord4fi;
typedef Attrib<4, SH_TEMP, FracInt, SH_TEXCOORD> TexCoord4fi;
typedef Attrib<4, SH_CONST, FracInt, SH_TEXCOORD> ConstTexCoord4fi;


typedef Attrib<1, SH_INPUT, unsigned int, SH_TEXCOORD> InputTexCoord1ui;
typedef Attrib<1, SH_OUTPUT, unsigned int, SH_TEXCOORD> OutputTexCoord1ui;
typedef Attrib<1, SH_INOUT, unsigned int, SH_TEXCOORD> InOutTexCoord1ui;
typedef Attrib<1, SH_TEMP, unsigned int, SH_TEXCOORD> TexCoord1ui;
typedef Attrib<1, SH_CONST, unsigned int, SH_TEXCOORD> ConstTexCoord1ui;
typedef Attrib<2, SH_INPUT, unsigned int, SH_TEXCOORD> InputTexCoord2ui;
typedef Attrib<2, SH_OUTPUT, unsigned int, SH_TEXCOORD> OutputTexCoord2ui;
typedef Attrib<2, SH_INOUT, unsigned int, SH_TEXCOORD> InOutTexCoord2ui;
typedef Attrib<2, SH_TEMP, unsigned int, SH_TEXCOORD> TexCoord2ui;
typedef Attrib<2, SH_CONST, unsigned int, SH_TEXCOORD> ConstTexCoord2ui;
typedef Attrib<3, SH_INPUT, unsigned int, SH_TEXCOORD> InputTexCoord3ui;
typedef Attrib<3, SH_OUTPUT, unsigned int, SH_TEXCOORD> OutputTexCoord3ui;
typedef Attrib<3, SH_INOUT, unsigned int, SH_TEXCOORD> InOutTexCoord3ui;
typedef Attrib<3, SH_TEMP, unsigned int, SH_TEXCOORD> TexCoord3ui;
typedef Attrib<3, SH_CONST, unsigned int, SH_TEXCOORD> ConstTexCoord3ui;
typedef Attrib<4, SH_INPUT, unsigned int, SH_TEXCOORD> InputTexCoord4ui;
typedef Attrib<4, SH_OUTPUT, unsigned int, SH_TEXCOORD> OutputTexCoord4ui;
typedef Attrib<4, SH_INOUT, unsigned int, SH_TEXCOORD> InOutTexCoord4ui;
typedef Attrib<4, SH_TEMP, unsigned int, SH_TEXCOORD> TexCoord4ui;
typedef Attrib<4, SH_CONST, unsigned int, SH_TEXCOORD> ConstTexCoord4ui;



} // namespace SH

#endif // SHSHTEXCOORD_HPP
