// WARNING - DO NOT EDIT THIS FILE:
// This file was automatically generated from scripts/Vector.hpp.py.
// If you wish to change it, edit that file instead.
//
// ---
//
// Sh: A GPU metaprogramming language.
//
// Copyright 2003-2006 Serious Hack Inc.
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
// MA  02110-1301, USA
//////////////////////////////////////////////////////////////////////////////

#ifndef SHVECTOR_HPP
#define SHVECTOR_HPP

#include "Attrib.hpp"
namespace SH {

/** A (geometric) n-vector.
 * 
 * By "vector" we mean a geometric vector, not just a tuple or an
 * array (unlike the unfortunate terminology in the standard
 * library).
 *
 */

typedef Attrib<1, INPUT, FracUShort, VECTOR> InputVector1fus;
typedef Attrib<1, OUTPUT, FracUShort, VECTOR> OutputVector1fus;
typedef Attrib<1, INOUT, FracUShort, VECTOR> InOutVector1fus;
typedef Attrib<1, TEMP, FracUShort, VECTOR> Vector1fus;
typedef Attrib<1, CONST, FracUShort, VECTOR> ConstVector1fus;
typedef Attrib<2, INPUT, FracUShort, VECTOR> InputVector2fus;
typedef Attrib<2, OUTPUT, FracUShort, VECTOR> OutputVector2fus;
typedef Attrib<2, INOUT, FracUShort, VECTOR> InOutVector2fus;
typedef Attrib<2, TEMP, FracUShort, VECTOR> Vector2fus;
typedef Attrib<2, CONST, FracUShort, VECTOR> ConstVector2fus;
typedef Attrib<3, INPUT, FracUShort, VECTOR> InputVector3fus;
typedef Attrib<3, OUTPUT, FracUShort, VECTOR> OutputVector3fus;
typedef Attrib<3, INOUT, FracUShort, VECTOR> InOutVector3fus;
typedef Attrib<3, TEMP, FracUShort, VECTOR> Vector3fus;
typedef Attrib<3, CONST, FracUShort, VECTOR> ConstVector3fus;
typedef Attrib<4, INPUT, FracUShort, VECTOR> InputVector4fus;
typedef Attrib<4, OUTPUT, FracUShort, VECTOR> OutputVector4fus;
typedef Attrib<4, INOUT, FracUShort, VECTOR> InOutVector4fus;
typedef Attrib<4, TEMP, FracUShort, VECTOR> Vector4fus;
typedef Attrib<4, CONST, FracUShort, VECTOR> ConstVector4fus;


typedef Attrib<1, INPUT, short, VECTOR> InputVector1s;
typedef Attrib<1, OUTPUT, short, VECTOR> OutputVector1s;
typedef Attrib<1, INOUT, short, VECTOR> InOutVector1s;
typedef Attrib<1, TEMP, short, VECTOR> Vector1s;
typedef Attrib<1, CONST, short, VECTOR> ConstVector1s;
typedef Attrib<2, INPUT, short, VECTOR> InputVector2s;
typedef Attrib<2, OUTPUT, short, VECTOR> OutputVector2s;
typedef Attrib<2, INOUT, short, VECTOR> InOutVector2s;
typedef Attrib<2, TEMP, short, VECTOR> Vector2s;
typedef Attrib<2, CONST, short, VECTOR> ConstVector2s;
typedef Attrib<3, INPUT, short, VECTOR> InputVector3s;
typedef Attrib<3, OUTPUT, short, VECTOR> OutputVector3s;
typedef Attrib<3, INOUT, short, VECTOR> InOutVector3s;
typedef Attrib<3, TEMP, short, VECTOR> Vector3s;
typedef Attrib<3, CONST, short, VECTOR> ConstVector3s;
typedef Attrib<4, INPUT, short, VECTOR> InputVector4s;
typedef Attrib<4, OUTPUT, short, VECTOR> OutputVector4s;
typedef Attrib<4, INOUT, short, VECTOR> InOutVector4s;
typedef Attrib<4, TEMP, short, VECTOR> Vector4s;
typedef Attrib<4, CONST, short, VECTOR> ConstVector4s;


typedef Attrib<1, INPUT, FracUInt, VECTOR> InputVector1fui;
typedef Attrib<1, OUTPUT, FracUInt, VECTOR> OutputVector1fui;
typedef Attrib<1, INOUT, FracUInt, VECTOR> InOutVector1fui;
typedef Attrib<1, TEMP, FracUInt, VECTOR> Vector1fui;
typedef Attrib<1, CONST, FracUInt, VECTOR> ConstVector1fui;
typedef Attrib<2, INPUT, FracUInt, VECTOR> InputVector2fui;
typedef Attrib<2, OUTPUT, FracUInt, VECTOR> OutputVector2fui;
typedef Attrib<2, INOUT, FracUInt, VECTOR> InOutVector2fui;
typedef Attrib<2, TEMP, FracUInt, VECTOR> Vector2fui;
typedef Attrib<2, CONST, FracUInt, VECTOR> ConstVector2fui;
typedef Attrib<3, INPUT, FracUInt, VECTOR> InputVector3fui;
typedef Attrib<3, OUTPUT, FracUInt, VECTOR> OutputVector3fui;
typedef Attrib<3, INOUT, FracUInt, VECTOR> InOutVector3fui;
typedef Attrib<3, TEMP, FracUInt, VECTOR> Vector3fui;
typedef Attrib<3, CONST, FracUInt, VECTOR> ConstVector3fui;
typedef Attrib<4, INPUT, FracUInt, VECTOR> InputVector4fui;
typedef Attrib<4, OUTPUT, FracUInt, VECTOR> OutputVector4fui;
typedef Attrib<4, INOUT, FracUInt, VECTOR> InOutVector4fui;
typedef Attrib<4, TEMP, FracUInt, VECTOR> Vector4fui;
typedef Attrib<4, CONST, FracUInt, VECTOR> ConstVector4fui;


typedef Attrib<1, INPUT, FracByte, VECTOR> InputVector1fb;
typedef Attrib<1, OUTPUT, FracByte, VECTOR> OutputVector1fb;
typedef Attrib<1, INOUT, FracByte, VECTOR> InOutVector1fb;
typedef Attrib<1, TEMP, FracByte, VECTOR> Vector1fb;
typedef Attrib<1, CONST, FracByte, VECTOR> ConstVector1fb;
typedef Attrib<2, INPUT, FracByte, VECTOR> InputVector2fb;
typedef Attrib<2, OUTPUT, FracByte, VECTOR> OutputVector2fb;
typedef Attrib<2, INOUT, FracByte, VECTOR> InOutVector2fb;
typedef Attrib<2, TEMP, FracByte, VECTOR> Vector2fb;
typedef Attrib<2, CONST, FracByte, VECTOR> ConstVector2fb;
typedef Attrib<3, INPUT, FracByte, VECTOR> InputVector3fb;
typedef Attrib<3, OUTPUT, FracByte, VECTOR> OutputVector3fb;
typedef Attrib<3, INOUT, FracByte, VECTOR> InOutVector3fb;
typedef Attrib<3, TEMP, FracByte, VECTOR> Vector3fb;
typedef Attrib<3, CONST, FracByte, VECTOR> ConstVector3fb;
typedef Attrib<4, INPUT, FracByte, VECTOR> InputVector4fb;
typedef Attrib<4, OUTPUT, FracByte, VECTOR> OutputVector4fb;
typedef Attrib<4, INOUT, FracByte, VECTOR> InOutVector4fb;
typedef Attrib<4, TEMP, FracByte, VECTOR> Vector4fb;
typedef Attrib<4, CONST, FracByte, VECTOR> ConstVector4fb;


typedef Attrib<1, INPUT, int, VECTOR> InputVector1i;
typedef Attrib<1, OUTPUT, int, VECTOR> OutputVector1i;
typedef Attrib<1, INOUT, int, VECTOR> InOutVector1i;
typedef Attrib<1, TEMP, int, VECTOR> Vector1i;
typedef Attrib<1, CONST, int, VECTOR> ConstVector1i;
typedef Attrib<2, INPUT, int, VECTOR> InputVector2i;
typedef Attrib<2, OUTPUT, int, VECTOR> OutputVector2i;
typedef Attrib<2, INOUT, int, VECTOR> InOutVector2i;
typedef Attrib<2, TEMP, int, VECTOR> Vector2i;
typedef Attrib<2, CONST, int, VECTOR> ConstVector2i;
typedef Attrib<3, INPUT, int, VECTOR> InputVector3i;
typedef Attrib<3, OUTPUT, int, VECTOR> OutputVector3i;
typedef Attrib<3, INOUT, int, VECTOR> InOutVector3i;
typedef Attrib<3, TEMP, int, VECTOR> Vector3i;
typedef Attrib<3, CONST, int, VECTOR> ConstVector3i;
typedef Attrib<4, INPUT, int, VECTOR> InputVector4i;
typedef Attrib<4, OUTPUT, int, VECTOR> OutputVector4i;
typedef Attrib<4, INOUT, int, VECTOR> InOutVector4i;
typedef Attrib<4, TEMP, int, VECTOR> Vector4i;
typedef Attrib<4, CONST, int, VECTOR> ConstVector4i;


typedef Attrib<1, INPUT, double, VECTOR> InputVector1d;
typedef Attrib<1, OUTPUT, double, VECTOR> OutputVector1d;
typedef Attrib<1, INOUT, double, VECTOR> InOutVector1d;
typedef Attrib<1, TEMP, double, VECTOR> Vector1d;
typedef Attrib<1, CONST, double, VECTOR> ConstVector1d;
typedef Attrib<2, INPUT, double, VECTOR> InputVector2d;
typedef Attrib<2, OUTPUT, double, VECTOR> OutputVector2d;
typedef Attrib<2, INOUT, double, VECTOR> InOutVector2d;
typedef Attrib<2, TEMP, double, VECTOR> Vector2d;
typedef Attrib<2, CONST, double, VECTOR> ConstVector2d;
typedef Attrib<3, INPUT, double, VECTOR> InputVector3d;
typedef Attrib<3, OUTPUT, double, VECTOR> OutputVector3d;
typedef Attrib<3, INOUT, double, VECTOR> InOutVector3d;
typedef Attrib<3, TEMP, double, VECTOR> Vector3d;
typedef Attrib<3, CONST, double, VECTOR> ConstVector3d;
typedef Attrib<4, INPUT, double, VECTOR> InputVector4d;
typedef Attrib<4, OUTPUT, double, VECTOR> OutputVector4d;
typedef Attrib<4, INOUT, double, VECTOR> InOutVector4d;
typedef Attrib<4, TEMP, double, VECTOR> Vector4d;
typedef Attrib<4, CONST, double, VECTOR> ConstVector4d;


typedef Attrib<1, INPUT, unsigned char, VECTOR> InputVector1ub;
typedef Attrib<1, OUTPUT, unsigned char, VECTOR> OutputVector1ub;
typedef Attrib<1, INOUT, unsigned char, VECTOR> InOutVector1ub;
typedef Attrib<1, TEMP, unsigned char, VECTOR> Vector1ub;
typedef Attrib<1, CONST, unsigned char, VECTOR> ConstVector1ub;
typedef Attrib<2, INPUT, unsigned char, VECTOR> InputVector2ub;
typedef Attrib<2, OUTPUT, unsigned char, VECTOR> OutputVector2ub;
typedef Attrib<2, INOUT, unsigned char, VECTOR> InOutVector2ub;
typedef Attrib<2, TEMP, unsigned char, VECTOR> Vector2ub;
typedef Attrib<2, CONST, unsigned char, VECTOR> ConstVector2ub;
typedef Attrib<3, INPUT, unsigned char, VECTOR> InputVector3ub;
typedef Attrib<3, OUTPUT, unsigned char, VECTOR> OutputVector3ub;
typedef Attrib<3, INOUT, unsigned char, VECTOR> InOutVector3ub;
typedef Attrib<3, TEMP, unsigned char, VECTOR> Vector3ub;
typedef Attrib<3, CONST, unsigned char, VECTOR> ConstVector3ub;
typedef Attrib<4, INPUT, unsigned char, VECTOR> InputVector4ub;
typedef Attrib<4, OUTPUT, unsigned char, VECTOR> OutputVector4ub;
typedef Attrib<4, INOUT, unsigned char, VECTOR> InOutVector4ub;
typedef Attrib<4, TEMP, unsigned char, VECTOR> Vector4ub;
typedef Attrib<4, CONST, unsigned char, VECTOR> ConstVector4ub;


typedef Attrib<1, INPUT, float, VECTOR> InputVector1f;
typedef Attrib<1, OUTPUT, float, VECTOR> OutputVector1f;
typedef Attrib<1, INOUT, float, VECTOR> InOutVector1f;
typedef Attrib<1, TEMP, float, VECTOR> Vector1f;
typedef Attrib<1, CONST, float, VECTOR> ConstVector1f;
typedef Attrib<2, INPUT, float, VECTOR> InputVector2f;
typedef Attrib<2, OUTPUT, float, VECTOR> OutputVector2f;
typedef Attrib<2, INOUT, float, VECTOR> InOutVector2f;
typedef Attrib<2, TEMP, float, VECTOR> Vector2f;
typedef Attrib<2, CONST, float, VECTOR> ConstVector2f;
typedef Attrib<3, INPUT, float, VECTOR> InputVector3f;
typedef Attrib<3, OUTPUT, float, VECTOR> OutputVector3f;
typedef Attrib<3, INOUT, float, VECTOR> InOutVector3f;
typedef Attrib<3, TEMP, float, VECTOR> Vector3f;
typedef Attrib<3, CONST, float, VECTOR> ConstVector3f;
typedef Attrib<4, INPUT, float, VECTOR> InputVector4f;
typedef Attrib<4, OUTPUT, float, VECTOR> OutputVector4f;
typedef Attrib<4, INOUT, float, VECTOR> InOutVector4f;
typedef Attrib<4, TEMP, float, VECTOR> Vector4f;
typedef Attrib<4, CONST, float, VECTOR> ConstVector4f;


typedef Attrib<1, INPUT, char, VECTOR> InputVector1b;
typedef Attrib<1, OUTPUT, char, VECTOR> OutputVector1b;
typedef Attrib<1, INOUT, char, VECTOR> InOutVector1b;
typedef Attrib<1, TEMP, char, VECTOR> Vector1b;
typedef Attrib<1, CONST, char, VECTOR> ConstVector1b;
typedef Attrib<2, INPUT, char, VECTOR> InputVector2b;
typedef Attrib<2, OUTPUT, char, VECTOR> OutputVector2b;
typedef Attrib<2, INOUT, char, VECTOR> InOutVector2b;
typedef Attrib<2, TEMP, char, VECTOR> Vector2b;
typedef Attrib<2, CONST, char, VECTOR> ConstVector2b;
typedef Attrib<3, INPUT, char, VECTOR> InputVector3b;
typedef Attrib<3, OUTPUT, char, VECTOR> OutputVector3b;
typedef Attrib<3, INOUT, char, VECTOR> InOutVector3b;
typedef Attrib<3, TEMP, char, VECTOR> Vector3b;
typedef Attrib<3, CONST, char, VECTOR> ConstVector3b;
typedef Attrib<4, INPUT, char, VECTOR> InputVector4b;
typedef Attrib<4, OUTPUT, char, VECTOR> OutputVector4b;
typedef Attrib<4, INOUT, char, VECTOR> InOutVector4b;
typedef Attrib<4, TEMP, char, VECTOR> Vector4b;
typedef Attrib<4, CONST, char, VECTOR> ConstVector4b;


typedef Attrib<1, INPUT, unsigned short, VECTOR> InputVector1us;
typedef Attrib<1, OUTPUT, unsigned short, VECTOR> OutputVector1us;
typedef Attrib<1, INOUT, unsigned short, VECTOR> InOutVector1us;
typedef Attrib<1, TEMP, unsigned short, VECTOR> Vector1us;
typedef Attrib<1, CONST, unsigned short, VECTOR> ConstVector1us;
typedef Attrib<2, INPUT, unsigned short, VECTOR> InputVector2us;
typedef Attrib<2, OUTPUT, unsigned short, VECTOR> OutputVector2us;
typedef Attrib<2, INOUT, unsigned short, VECTOR> InOutVector2us;
typedef Attrib<2, TEMP, unsigned short, VECTOR> Vector2us;
typedef Attrib<2, CONST, unsigned short, VECTOR> ConstVector2us;
typedef Attrib<3, INPUT, unsigned short, VECTOR> InputVector3us;
typedef Attrib<3, OUTPUT, unsigned short, VECTOR> OutputVector3us;
typedef Attrib<3, INOUT, unsigned short, VECTOR> InOutVector3us;
typedef Attrib<3, TEMP, unsigned short, VECTOR> Vector3us;
typedef Attrib<3, CONST, unsigned short, VECTOR> ConstVector3us;
typedef Attrib<4, INPUT, unsigned short, VECTOR> InputVector4us;
typedef Attrib<4, OUTPUT, unsigned short, VECTOR> OutputVector4us;
typedef Attrib<4, INOUT, unsigned short, VECTOR> InOutVector4us;
typedef Attrib<4, TEMP, unsigned short, VECTOR> Vector4us;
typedef Attrib<4, CONST, unsigned short, VECTOR> ConstVector4us;


typedef Attrib<1, INPUT, FracUByte, VECTOR> InputVector1fub;
typedef Attrib<1, OUTPUT, FracUByte, VECTOR> OutputVector1fub;
typedef Attrib<1, INOUT, FracUByte, VECTOR> InOutVector1fub;
typedef Attrib<1, TEMP, FracUByte, VECTOR> Vector1fub;
typedef Attrib<1, CONST, FracUByte, VECTOR> ConstVector1fub;
typedef Attrib<2, INPUT, FracUByte, VECTOR> InputVector2fub;
typedef Attrib<2, OUTPUT, FracUByte, VECTOR> OutputVector2fub;
typedef Attrib<2, INOUT, FracUByte, VECTOR> InOutVector2fub;
typedef Attrib<2, TEMP, FracUByte, VECTOR> Vector2fub;
typedef Attrib<2, CONST, FracUByte, VECTOR> ConstVector2fub;
typedef Attrib<3, INPUT, FracUByte, VECTOR> InputVector3fub;
typedef Attrib<3, OUTPUT, FracUByte, VECTOR> OutputVector3fub;
typedef Attrib<3, INOUT, FracUByte, VECTOR> InOutVector3fub;
typedef Attrib<3, TEMP, FracUByte, VECTOR> Vector3fub;
typedef Attrib<3, CONST, FracUByte, VECTOR> ConstVector3fub;
typedef Attrib<4, INPUT, FracUByte, VECTOR> InputVector4fub;
typedef Attrib<4, OUTPUT, FracUByte, VECTOR> OutputVector4fub;
typedef Attrib<4, INOUT, FracUByte, VECTOR> InOutVector4fub;
typedef Attrib<4, TEMP, FracUByte, VECTOR> Vector4fub;
typedef Attrib<4, CONST, FracUByte, VECTOR> ConstVector4fub;


typedef Attrib<1, INPUT, Half, VECTOR> InputVector1h;
typedef Attrib<1, OUTPUT, Half, VECTOR> OutputVector1h;
typedef Attrib<1, INOUT, Half, VECTOR> InOutVector1h;
typedef Attrib<1, TEMP, Half, VECTOR> Vector1h;
typedef Attrib<1, CONST, Half, VECTOR> ConstVector1h;
typedef Attrib<2, INPUT, Half, VECTOR> InputVector2h;
typedef Attrib<2, OUTPUT, Half, VECTOR> OutputVector2h;
typedef Attrib<2, INOUT, Half, VECTOR> InOutVector2h;
typedef Attrib<2, TEMP, Half, VECTOR> Vector2h;
typedef Attrib<2, CONST, Half, VECTOR> ConstVector2h;
typedef Attrib<3, INPUT, Half, VECTOR> InputVector3h;
typedef Attrib<3, OUTPUT, Half, VECTOR> OutputVector3h;
typedef Attrib<3, INOUT, Half, VECTOR> InOutVector3h;
typedef Attrib<3, TEMP, Half, VECTOR> Vector3h;
typedef Attrib<3, CONST, Half, VECTOR> ConstVector3h;
typedef Attrib<4, INPUT, Half, VECTOR> InputVector4h;
typedef Attrib<4, OUTPUT, Half, VECTOR> OutputVector4h;
typedef Attrib<4, INOUT, Half, VECTOR> InOutVector4h;
typedef Attrib<4, TEMP, Half, VECTOR> Vector4h;
typedef Attrib<4, CONST, Half, VECTOR> ConstVector4h;


typedef Attrib<1, INPUT, FracShort, VECTOR> InputVector1fs;
typedef Attrib<1, OUTPUT, FracShort, VECTOR> OutputVector1fs;
typedef Attrib<1, INOUT, FracShort, VECTOR> InOutVector1fs;
typedef Attrib<1, TEMP, FracShort, VECTOR> Vector1fs;
typedef Attrib<1, CONST, FracShort, VECTOR> ConstVector1fs;
typedef Attrib<2, INPUT, FracShort, VECTOR> InputVector2fs;
typedef Attrib<2, OUTPUT, FracShort, VECTOR> OutputVector2fs;
typedef Attrib<2, INOUT, FracShort, VECTOR> InOutVector2fs;
typedef Attrib<2, TEMP, FracShort, VECTOR> Vector2fs;
typedef Attrib<2, CONST, FracShort, VECTOR> ConstVector2fs;
typedef Attrib<3, INPUT, FracShort, VECTOR> InputVector3fs;
typedef Attrib<3, OUTPUT, FracShort, VECTOR> OutputVector3fs;
typedef Attrib<3, INOUT, FracShort, VECTOR> InOutVector3fs;
typedef Attrib<3, TEMP, FracShort, VECTOR> Vector3fs;
typedef Attrib<3, CONST, FracShort, VECTOR> ConstVector3fs;
typedef Attrib<4, INPUT, FracShort, VECTOR> InputVector4fs;
typedef Attrib<4, OUTPUT, FracShort, VECTOR> OutputVector4fs;
typedef Attrib<4, INOUT, FracShort, VECTOR> InOutVector4fs;
typedef Attrib<4, TEMP, FracShort, VECTOR> Vector4fs;
typedef Attrib<4, CONST, FracShort, VECTOR> ConstVector4fs;


typedef Attrib<1, INPUT, FracInt, VECTOR> InputVector1fi;
typedef Attrib<1, OUTPUT, FracInt, VECTOR> OutputVector1fi;
typedef Attrib<1, INOUT, FracInt, VECTOR> InOutVector1fi;
typedef Attrib<1, TEMP, FracInt, VECTOR> Vector1fi;
typedef Attrib<1, CONST, FracInt, VECTOR> ConstVector1fi;
typedef Attrib<2, INPUT, FracInt, VECTOR> InputVector2fi;
typedef Attrib<2, OUTPUT, FracInt, VECTOR> OutputVector2fi;
typedef Attrib<2, INOUT, FracInt, VECTOR> InOutVector2fi;
typedef Attrib<2, TEMP, FracInt, VECTOR> Vector2fi;
typedef Attrib<2, CONST, FracInt, VECTOR> ConstVector2fi;
typedef Attrib<3, INPUT, FracInt, VECTOR> InputVector3fi;
typedef Attrib<3, OUTPUT, FracInt, VECTOR> OutputVector3fi;
typedef Attrib<3, INOUT, FracInt, VECTOR> InOutVector3fi;
typedef Attrib<3, TEMP, FracInt, VECTOR> Vector3fi;
typedef Attrib<3, CONST, FracInt, VECTOR> ConstVector3fi;
typedef Attrib<4, INPUT, FracInt, VECTOR> InputVector4fi;
typedef Attrib<4, OUTPUT, FracInt, VECTOR> OutputVector4fi;
typedef Attrib<4, INOUT, FracInt, VECTOR> InOutVector4fi;
typedef Attrib<4, TEMP, FracInt, VECTOR> Vector4fi;
typedef Attrib<4, CONST, FracInt, VECTOR> ConstVector4fi;


typedef Attrib<1, INPUT, unsigned int, VECTOR> InputVector1ui;
typedef Attrib<1, OUTPUT, unsigned int, VECTOR> OutputVector1ui;
typedef Attrib<1, INOUT, unsigned int, VECTOR> InOutVector1ui;
typedef Attrib<1, TEMP, unsigned int, VECTOR> Vector1ui;
typedef Attrib<1, CONST, unsigned int, VECTOR> ConstVector1ui;
typedef Attrib<2, INPUT, unsigned int, VECTOR> InputVector2ui;
typedef Attrib<2, OUTPUT, unsigned int, VECTOR> OutputVector2ui;
typedef Attrib<2, INOUT, unsigned int, VECTOR> InOutVector2ui;
typedef Attrib<2, TEMP, unsigned int, VECTOR> Vector2ui;
typedef Attrib<2, CONST, unsigned int, VECTOR> ConstVector2ui;
typedef Attrib<3, INPUT, unsigned int, VECTOR> InputVector3ui;
typedef Attrib<3, OUTPUT, unsigned int, VECTOR> OutputVector3ui;
typedef Attrib<3, INOUT, unsigned int, VECTOR> InOutVector3ui;
typedef Attrib<3, TEMP, unsigned int, VECTOR> Vector3ui;
typedef Attrib<3, CONST, unsigned int, VECTOR> ConstVector3ui;
typedef Attrib<4, INPUT, unsigned int, VECTOR> InputVector4ui;
typedef Attrib<4, OUTPUT, unsigned int, VECTOR> OutputVector4ui;
typedef Attrib<4, INOUT, unsigned int, VECTOR> InOutVector4ui;
typedef Attrib<4, TEMP, unsigned int, VECTOR> Vector4ui;
typedef Attrib<4, CONST, unsigned int, VECTOR> ConstVector4ui;



} // namespace SH

#endif // SHVECTOR_HPP
