#! /bin/bash
# simple-minded script to avoid typing in all the commands

sudo opcontrol --shutdown
sudo opcontrol --reset
sudo opcontrol --setup \
        --vmlinux=/usr/lib/debug/lib/modules/`uname -r`/vmlinux \
                --event=CPU_CLK_UNHALTED:100000:0:1:1 --separate=library
sudo opcontrol --start --no-vmlinux
$@
sudo opcontrol --shutdown
