SOURCES = $(wildcard *.cpp)
EXECUTABLES = $(SOURCES:.cpp=)
OBJECTS = $(SOURCES:.cpp=.obj)
DEPENDS = $(SOURCES:.cpp=.d)
LDADD = ..\..\src\libsh.lib
CLEANFILES = $(SOURCES:.cpp=)

all:

%.exe: %.obj
	$(CXX) $(CXXFLAGS) /Fe$* $< $(LDADD) $(LDFLAGS)

w32testarb.exe: w32testarb.obj
	$(CXX) $(CXXFLAGS) /Few32testarb w32testarb.obj $(LDFLAGS) $(OPENGL_DIR)\lib\OPENGL32.LIB ..\..\src\libsh.lib

include ../../win32.mk
CPPFLAGS += -I..\..\src 
CPPFLAGS += -DSH_DLLEXPORT=__declspec(dllimport)

include $(DEPENDS)


