// WARNING - DO NOT EDIT THIS FILE:
// This file was automatically generated from scripts/ShNormal.hpp.py.
// If you wish to change it, edit that file instead.
//
// ---
//
// Sh: A GPU metaprogramming language.
//
// Copyright 2003-2005 Serious Hack Inc.
// 
// This software is provided 'as-is', without any express or implied
// warranty. In no event will the authors be held liable for any damages
// arising from the use of this software.
// 
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it
// freely, subject to the following restrictions:
// 
// 1. The origin of this software must not be misrepresented; you must
// not claim that you wrote the original software. If you use this
// software in a product, an acknowledgment in the product documentation
// would be appreciated but is not required.
// 
// 2. Altered source versions must be plainly marked as such, and must
// not be misrepresented as being the original software.
// 
// 3. This notice may not be removed or altered from any source
// distribution.
//////////////////////////////////////////////////////////////////////////////

#ifndef SH_SHNORMAL_HPP
#define SH_SHNORMAL_HPP

#include "ShVector.hpp"
namespace SH {

/** An n-normal.
 * 
 *
 */

typedef ShAttrib<1, SH_INPUT, ShFracUShort, SH_NORMAL> ShInputNormal1fus;
typedef ShAttrib<1, SH_OUTPUT, ShFracUShort, SH_NORMAL> ShOutputNormal1fus;
typedef ShAttrib<1, SH_INOUT, ShFracUShort, SH_NORMAL> ShInOutNormal1fus;
typedef ShAttrib<1, SH_TEMP, ShFracUShort, SH_NORMAL> ShNormal1fus;
typedef ShAttrib<1, SH_CONST, ShFracUShort, SH_NORMAL> ShConstNormal1fus;
typedef ShAttrib<2, SH_INPUT, ShFracUShort, SH_NORMAL> ShInputNormal2fus;
typedef ShAttrib<2, SH_OUTPUT, ShFracUShort, SH_NORMAL> ShOutputNormal2fus;
typedef ShAttrib<2, SH_INOUT, ShFracUShort, SH_NORMAL> ShInOutNormal2fus;
typedef ShAttrib<2, SH_TEMP, ShFracUShort, SH_NORMAL> ShNormal2fus;
typedef ShAttrib<2, SH_CONST, ShFracUShort, SH_NORMAL> ShConstNormal2fus;
typedef ShAttrib<3, SH_INPUT, ShFracUShort, SH_NORMAL> ShInputNormal3fus;
typedef ShAttrib<3, SH_OUTPUT, ShFracUShort, SH_NORMAL> ShOutputNormal3fus;
typedef ShAttrib<3, SH_INOUT, ShFracUShort, SH_NORMAL> ShInOutNormal3fus;
typedef ShAttrib<3, SH_TEMP, ShFracUShort, SH_NORMAL> ShNormal3fus;
typedef ShAttrib<3, SH_CONST, ShFracUShort, SH_NORMAL> ShConstNormal3fus;
typedef ShAttrib<4, SH_INPUT, ShFracUShort, SH_NORMAL> ShInputNormal4fus;
typedef ShAttrib<4, SH_OUTPUT, ShFracUShort, SH_NORMAL> ShOutputNormal4fus;
typedef ShAttrib<4, SH_INOUT, ShFracUShort, SH_NORMAL> ShInOutNormal4fus;
typedef ShAttrib<4, SH_TEMP, ShFracUShort, SH_NORMAL> ShNormal4fus;
typedef ShAttrib<4, SH_CONST, ShFracUShort, SH_NORMAL> ShConstNormal4fus;


typedef ShAttrib<1, SH_INPUT, short, SH_NORMAL> ShInputNormal1s;
typedef ShAttrib<1, SH_OUTPUT, short, SH_NORMAL> ShOutputNormal1s;
typedef ShAttrib<1, SH_INOUT, short, SH_NORMAL> ShInOutNormal1s;
typedef ShAttrib<1, SH_TEMP, short, SH_NORMAL> ShNormal1s;
typedef ShAttrib<1, SH_CONST, short, SH_NORMAL> ShConstNormal1s;
typedef ShAttrib<2, SH_INPUT, short, SH_NORMAL> ShInputNormal2s;
typedef ShAttrib<2, SH_OUTPUT, short, SH_NORMAL> ShOutputNormal2s;
typedef ShAttrib<2, SH_INOUT, short, SH_NORMAL> ShInOutNormal2s;
typedef ShAttrib<2, SH_TEMP, short, SH_NORMAL> ShNormal2s;
typedef ShAttrib<2, SH_CONST, short, SH_NORMAL> ShConstNormal2s;
typedef ShAttrib<3, SH_INPUT, short, SH_NORMAL> ShInputNormal3s;
typedef ShAttrib<3, SH_OUTPUT, short, SH_NORMAL> ShOutputNormal3s;
typedef ShAttrib<3, SH_INOUT, short, SH_NORMAL> ShInOutNormal3s;
typedef ShAttrib<3, SH_TEMP, short, SH_NORMAL> ShNormal3s;
typedef ShAttrib<3, SH_CONST, short, SH_NORMAL> ShConstNormal3s;
typedef ShAttrib<4, SH_INPUT, short, SH_NORMAL> ShInputNormal4s;
typedef ShAttrib<4, SH_OUTPUT, short, SH_NORMAL> ShOutputNormal4s;
typedef ShAttrib<4, SH_INOUT, short, SH_NORMAL> ShInOutNormal4s;
typedef ShAttrib<4, SH_TEMP, short, SH_NORMAL> ShNormal4s;
typedef ShAttrib<4, SH_CONST, short, SH_NORMAL> ShConstNormal4s;


typedef ShAttrib<1, SH_INPUT, ShFracUInt, SH_NORMAL> ShInputNormal1fui;
typedef ShAttrib<1, SH_OUTPUT, ShFracUInt, SH_NORMAL> ShOutputNormal1fui;
typedef ShAttrib<1, SH_INOUT, ShFracUInt, SH_NORMAL> ShInOutNormal1fui;
typedef ShAttrib<1, SH_TEMP, ShFracUInt, SH_NORMAL> ShNormal1fui;
typedef ShAttrib<1, SH_CONST, ShFracUInt, SH_NORMAL> ShConstNormal1fui;
typedef ShAttrib<2, SH_INPUT, ShFracUInt, SH_NORMAL> ShInputNormal2fui;
typedef ShAttrib<2, SH_OUTPUT, ShFracUInt, SH_NORMAL> ShOutputNormal2fui;
typedef ShAttrib<2, SH_INOUT, ShFracUInt, SH_NORMAL> ShInOutNormal2fui;
typedef ShAttrib<2, SH_TEMP, ShFracUInt, SH_NORMAL> ShNormal2fui;
typedef ShAttrib<2, SH_CONST, ShFracUInt, SH_NORMAL> ShConstNormal2fui;
typedef ShAttrib<3, SH_INPUT, ShFracUInt, SH_NORMAL> ShInputNormal3fui;
typedef ShAttrib<3, SH_OUTPUT, ShFracUInt, SH_NORMAL> ShOutputNormal3fui;
typedef ShAttrib<3, SH_INOUT, ShFracUInt, SH_NORMAL> ShInOutNormal3fui;
typedef ShAttrib<3, SH_TEMP, ShFracUInt, SH_NORMAL> ShNormal3fui;
typedef ShAttrib<3, SH_CONST, ShFracUInt, SH_NORMAL> ShConstNormal3fui;
typedef ShAttrib<4, SH_INPUT, ShFracUInt, SH_NORMAL> ShInputNormal4fui;
typedef ShAttrib<4, SH_OUTPUT, ShFracUInt, SH_NORMAL> ShOutputNormal4fui;
typedef ShAttrib<4, SH_INOUT, ShFracUInt, SH_NORMAL> ShInOutNormal4fui;
typedef ShAttrib<4, SH_TEMP, ShFracUInt, SH_NORMAL> ShNormal4fui;
typedef ShAttrib<4, SH_CONST, ShFracUInt, SH_NORMAL> ShConstNormal4fui;


typedef ShAttrib<1, SH_INPUT, ShFracByte, SH_NORMAL> ShInputNormal1fb;
typedef ShAttrib<1, SH_OUTPUT, ShFracByte, SH_NORMAL> ShOutputNormal1fb;
typedef ShAttrib<1, SH_INOUT, ShFracByte, SH_NORMAL> ShInOutNormal1fb;
typedef ShAttrib<1, SH_TEMP, ShFracByte, SH_NORMAL> ShNormal1fb;
typedef ShAttrib<1, SH_CONST, ShFracByte, SH_NORMAL> ShConstNormal1fb;
typedef ShAttrib<2, SH_INPUT, ShFracByte, SH_NORMAL> ShInputNormal2fb;
typedef ShAttrib<2, SH_OUTPUT, ShFracByte, SH_NORMAL> ShOutputNormal2fb;
typedef ShAttrib<2, SH_INOUT, ShFracByte, SH_NORMAL> ShInOutNormal2fb;
typedef ShAttrib<2, SH_TEMP, ShFracByte, SH_NORMAL> ShNormal2fb;
typedef ShAttrib<2, SH_CONST, ShFracByte, SH_NORMAL> ShConstNormal2fb;
typedef ShAttrib<3, SH_INPUT, ShFracByte, SH_NORMAL> ShInputNormal3fb;
typedef ShAttrib<3, SH_OUTPUT, ShFracByte, SH_NORMAL> ShOutputNormal3fb;
typedef ShAttrib<3, SH_INOUT, ShFracByte, SH_NORMAL> ShInOutNormal3fb;
typedef ShAttrib<3, SH_TEMP, ShFracByte, SH_NORMAL> ShNormal3fb;
typedef ShAttrib<3, SH_CONST, ShFracByte, SH_NORMAL> ShConstNormal3fb;
typedef ShAttrib<4, SH_INPUT, ShFracByte, SH_NORMAL> ShInputNormal4fb;
typedef ShAttrib<4, SH_OUTPUT, ShFracByte, SH_NORMAL> ShOutputNormal4fb;
typedef ShAttrib<4, SH_INOUT, ShFracByte, SH_NORMAL> ShInOutNormal4fb;
typedef ShAttrib<4, SH_TEMP, ShFracByte, SH_NORMAL> ShNormal4fb;
typedef ShAttrib<4, SH_CONST, ShFracByte, SH_NORMAL> ShConstNormal4fb;


typedef ShAttrib<1, SH_INPUT, int, SH_NORMAL> ShInputNormal1i;
typedef ShAttrib<1, SH_OUTPUT, int, SH_NORMAL> ShOutputNormal1i;
typedef ShAttrib<1, SH_INOUT, int, SH_NORMAL> ShInOutNormal1i;
typedef ShAttrib<1, SH_TEMP, int, SH_NORMAL> ShNormal1i;
typedef ShAttrib<1, SH_CONST, int, SH_NORMAL> ShConstNormal1i;
typedef ShAttrib<2, SH_INPUT, int, SH_NORMAL> ShInputNormal2i;
typedef ShAttrib<2, SH_OUTPUT, int, SH_NORMAL> ShOutputNormal2i;
typedef ShAttrib<2, SH_INOUT, int, SH_NORMAL> ShInOutNormal2i;
typedef ShAttrib<2, SH_TEMP, int, SH_NORMAL> ShNormal2i;
typedef ShAttrib<2, SH_CONST, int, SH_NORMAL> ShConstNormal2i;
typedef ShAttrib<3, SH_INPUT, int, SH_NORMAL> ShInputNormal3i;
typedef ShAttrib<3, SH_OUTPUT, int, SH_NORMAL> ShOutputNormal3i;
typedef ShAttrib<3, SH_INOUT, int, SH_NORMAL> ShInOutNormal3i;
typedef ShAttrib<3, SH_TEMP, int, SH_NORMAL> ShNormal3i;
typedef ShAttrib<3, SH_CONST, int, SH_NORMAL> ShConstNormal3i;
typedef ShAttrib<4, SH_INPUT, int, SH_NORMAL> ShInputNormal4i;
typedef ShAttrib<4, SH_OUTPUT, int, SH_NORMAL> ShOutputNormal4i;
typedef ShAttrib<4, SH_INOUT, int, SH_NORMAL> ShInOutNormal4i;
typedef ShAttrib<4, SH_TEMP, int, SH_NORMAL> ShNormal4i;
typedef ShAttrib<4, SH_CONST, int, SH_NORMAL> ShConstNormal4i;


typedef ShAttrib<1, SH_INPUT, double, SH_NORMAL> ShInputNormal1d;
typedef ShAttrib<1, SH_OUTPUT, double, SH_NORMAL> ShOutputNormal1d;
typedef ShAttrib<1, SH_INOUT, double, SH_NORMAL> ShInOutNormal1d;
typedef ShAttrib<1, SH_TEMP, double, SH_NORMAL> ShNormal1d;
typedef ShAttrib<1, SH_CONST, double, SH_NORMAL> ShConstNormal1d;
typedef ShAttrib<2, SH_INPUT, double, SH_NORMAL> ShInputNormal2d;
typedef ShAttrib<2, SH_OUTPUT, double, SH_NORMAL> ShOutputNormal2d;
typedef ShAttrib<2, SH_INOUT, double, SH_NORMAL> ShInOutNormal2d;
typedef ShAttrib<2, SH_TEMP, double, SH_NORMAL> ShNormal2d;
typedef ShAttrib<2, SH_CONST, double, SH_NORMAL> ShConstNormal2d;
typedef ShAttrib<3, SH_INPUT, double, SH_NORMAL> ShInputNormal3d;
typedef ShAttrib<3, SH_OUTPUT, double, SH_NORMAL> ShOutputNormal3d;
typedef ShAttrib<3, SH_INOUT, double, SH_NORMAL> ShInOutNormal3d;
typedef ShAttrib<3, SH_TEMP, double, SH_NORMAL> ShNormal3d;
typedef ShAttrib<3, SH_CONST, double, SH_NORMAL> ShConstNormal3d;
typedef ShAttrib<4, SH_INPUT, double, SH_NORMAL> ShInputNormal4d;
typedef ShAttrib<4, SH_OUTPUT, double, SH_NORMAL> ShOutputNormal4d;
typedef ShAttrib<4, SH_INOUT, double, SH_NORMAL> ShInOutNormal4d;
typedef ShAttrib<4, SH_TEMP, double, SH_NORMAL> ShNormal4d;
typedef ShAttrib<4, SH_CONST, double, SH_NORMAL> ShConstNormal4d;


typedef ShAttrib<1, SH_INPUT, unsigned char, SH_NORMAL> ShInputNormal1ub;
typedef ShAttrib<1, SH_OUTPUT, unsigned char, SH_NORMAL> ShOutputNormal1ub;
typedef ShAttrib<1, SH_INOUT, unsigned char, SH_NORMAL> ShInOutNormal1ub;
typedef ShAttrib<1, SH_TEMP, unsigned char, SH_NORMAL> ShNormal1ub;
typedef ShAttrib<1, SH_CONST, unsigned char, SH_NORMAL> ShConstNormal1ub;
typedef ShAttrib<2, SH_INPUT, unsigned char, SH_NORMAL> ShInputNormal2ub;
typedef ShAttrib<2, SH_OUTPUT, unsigned char, SH_NORMAL> ShOutputNormal2ub;
typedef ShAttrib<2, SH_INOUT, unsigned char, SH_NORMAL> ShInOutNormal2ub;
typedef ShAttrib<2, SH_TEMP, unsigned char, SH_NORMAL> ShNormal2ub;
typedef ShAttrib<2, SH_CONST, unsigned char, SH_NORMAL> ShConstNormal2ub;
typedef ShAttrib<3, SH_INPUT, unsigned char, SH_NORMAL> ShInputNormal3ub;
typedef ShAttrib<3, SH_OUTPUT, unsigned char, SH_NORMAL> ShOutputNormal3ub;
typedef ShAttrib<3, SH_INOUT, unsigned char, SH_NORMAL> ShInOutNormal3ub;
typedef ShAttrib<3, SH_TEMP, unsigned char, SH_NORMAL> ShNormal3ub;
typedef ShAttrib<3, SH_CONST, unsigned char, SH_NORMAL> ShConstNormal3ub;
typedef ShAttrib<4, SH_INPUT, unsigned char, SH_NORMAL> ShInputNormal4ub;
typedef ShAttrib<4, SH_OUTPUT, unsigned char, SH_NORMAL> ShOutputNormal4ub;
typedef ShAttrib<4, SH_INOUT, unsigned char, SH_NORMAL> ShInOutNormal4ub;
typedef ShAttrib<4, SH_TEMP, unsigned char, SH_NORMAL> ShNormal4ub;
typedef ShAttrib<4, SH_CONST, unsigned char, SH_NORMAL> ShConstNormal4ub;


typedef ShAttrib<1, SH_INPUT, float, SH_NORMAL> ShInputNormal1f;
typedef ShAttrib<1, SH_OUTPUT, float, SH_NORMAL> ShOutputNormal1f;
typedef ShAttrib<1, SH_INOUT, float, SH_NORMAL> ShInOutNormal1f;
typedef ShAttrib<1, SH_TEMP, float, SH_NORMAL> ShNormal1f;
typedef ShAttrib<1, SH_CONST, float, SH_NORMAL> ShConstNormal1f;
typedef ShAttrib<2, SH_INPUT, float, SH_NORMAL> ShInputNormal2f;
typedef ShAttrib<2, SH_OUTPUT, float, SH_NORMAL> ShOutputNormal2f;
typedef ShAttrib<2, SH_INOUT, float, SH_NORMAL> ShInOutNormal2f;
typedef ShAttrib<2, SH_TEMP, float, SH_NORMAL> ShNormal2f;
typedef ShAttrib<2, SH_CONST, float, SH_NORMAL> ShConstNormal2f;
typedef ShAttrib<3, SH_INPUT, float, SH_NORMAL> ShInputNormal3f;
typedef ShAttrib<3, SH_OUTPUT, float, SH_NORMAL> ShOutputNormal3f;
typedef ShAttrib<3, SH_INOUT, float, SH_NORMAL> ShInOutNormal3f;
typedef ShAttrib<3, SH_TEMP, float, SH_NORMAL> ShNormal3f;
typedef ShAttrib<3, SH_CONST, float, SH_NORMAL> ShConstNormal3f;
typedef ShAttrib<4, SH_INPUT, float, SH_NORMAL> ShInputNormal4f;
typedef ShAttrib<4, SH_OUTPUT, float, SH_NORMAL> ShOutputNormal4f;
typedef ShAttrib<4, SH_INOUT, float, SH_NORMAL> ShInOutNormal4f;
typedef ShAttrib<4, SH_TEMP, float, SH_NORMAL> ShNormal4f;
typedef ShAttrib<4, SH_CONST, float, SH_NORMAL> ShConstNormal4f;


typedef ShAttrib<1, SH_INPUT, char, SH_NORMAL> ShInputNormal1b;
typedef ShAttrib<1, SH_OUTPUT, char, SH_NORMAL> ShOutputNormal1b;
typedef ShAttrib<1, SH_INOUT, char, SH_NORMAL> ShInOutNormal1b;
typedef ShAttrib<1, SH_TEMP, char, SH_NORMAL> ShNormal1b;
typedef ShAttrib<1, SH_CONST, char, SH_NORMAL> ShConstNormal1b;
typedef ShAttrib<2, SH_INPUT, char, SH_NORMAL> ShInputNormal2b;
typedef ShAttrib<2, SH_OUTPUT, char, SH_NORMAL> ShOutputNormal2b;
typedef ShAttrib<2, SH_INOUT, char, SH_NORMAL> ShInOutNormal2b;
typedef ShAttrib<2, SH_TEMP, char, SH_NORMAL> ShNormal2b;
typedef ShAttrib<2, SH_CONST, char, SH_NORMAL> ShConstNormal2b;
typedef ShAttrib<3, SH_INPUT, char, SH_NORMAL> ShInputNormal3b;
typedef ShAttrib<3, SH_OUTPUT, char, SH_NORMAL> ShOutputNormal3b;
typedef ShAttrib<3, SH_INOUT, char, SH_NORMAL> ShInOutNormal3b;
typedef ShAttrib<3, SH_TEMP, char, SH_NORMAL> ShNormal3b;
typedef ShAttrib<3, SH_CONST, char, SH_NORMAL> ShConstNormal3b;
typedef ShAttrib<4, SH_INPUT, char, SH_NORMAL> ShInputNormal4b;
typedef ShAttrib<4, SH_OUTPUT, char, SH_NORMAL> ShOutputNormal4b;
typedef ShAttrib<4, SH_INOUT, char, SH_NORMAL> ShInOutNormal4b;
typedef ShAttrib<4, SH_TEMP, char, SH_NORMAL> ShNormal4b;
typedef ShAttrib<4, SH_CONST, char, SH_NORMAL> ShConstNormal4b;


typedef ShAttrib<1, SH_INPUT, unsigned short, SH_NORMAL> ShInputNormal1us;
typedef ShAttrib<1, SH_OUTPUT, unsigned short, SH_NORMAL> ShOutputNormal1us;
typedef ShAttrib<1, SH_INOUT, unsigned short, SH_NORMAL> ShInOutNormal1us;
typedef ShAttrib<1, SH_TEMP, unsigned short, SH_NORMAL> ShNormal1us;
typedef ShAttrib<1, SH_CONST, unsigned short, SH_NORMAL> ShConstNormal1us;
typedef ShAttrib<2, SH_INPUT, unsigned short, SH_NORMAL> ShInputNormal2us;
typedef ShAttrib<2, SH_OUTPUT, unsigned short, SH_NORMAL> ShOutputNormal2us;
typedef ShAttrib<2, SH_INOUT, unsigned short, SH_NORMAL> ShInOutNormal2us;
typedef ShAttrib<2, SH_TEMP, unsigned short, SH_NORMAL> ShNormal2us;
typedef ShAttrib<2, SH_CONST, unsigned short, SH_NORMAL> ShConstNormal2us;
typedef ShAttrib<3, SH_INPUT, unsigned short, SH_NORMAL> ShInputNormal3us;
typedef ShAttrib<3, SH_OUTPUT, unsigned short, SH_NORMAL> ShOutputNormal3us;
typedef ShAttrib<3, SH_INOUT, unsigned short, SH_NORMAL> ShInOutNormal3us;
typedef ShAttrib<3, SH_TEMP, unsigned short, SH_NORMAL> ShNormal3us;
typedef ShAttrib<3, SH_CONST, unsigned short, SH_NORMAL> ShConstNormal3us;
typedef ShAttrib<4, SH_INPUT, unsigned short, SH_NORMAL> ShInputNormal4us;
typedef ShAttrib<4, SH_OUTPUT, unsigned short, SH_NORMAL> ShOutputNormal4us;
typedef ShAttrib<4, SH_INOUT, unsigned short, SH_NORMAL> ShInOutNormal4us;
typedef ShAttrib<4, SH_TEMP, unsigned short, SH_NORMAL> ShNormal4us;
typedef ShAttrib<4, SH_CONST, unsigned short, SH_NORMAL> ShConstNormal4us;


typedef ShAttrib<1, SH_INPUT, ShFracUByte, SH_NORMAL> ShInputNormal1fub;
typedef ShAttrib<1, SH_OUTPUT, ShFracUByte, SH_NORMAL> ShOutputNormal1fub;
typedef ShAttrib<1, SH_INOUT, ShFracUByte, SH_NORMAL> ShInOutNormal1fub;
typedef ShAttrib<1, SH_TEMP, ShFracUByte, SH_NORMAL> ShNormal1fub;
typedef ShAttrib<1, SH_CONST, ShFracUByte, SH_NORMAL> ShConstNormal1fub;
typedef ShAttrib<2, SH_INPUT, ShFracUByte, SH_NORMAL> ShInputNormal2fub;
typedef ShAttrib<2, SH_OUTPUT, ShFracUByte, SH_NORMAL> ShOutputNormal2fub;
typedef ShAttrib<2, SH_INOUT, ShFracUByte, SH_NORMAL> ShInOutNormal2fub;
typedef ShAttrib<2, SH_TEMP, ShFracUByte, SH_NORMAL> ShNormal2fub;
typedef ShAttrib<2, SH_CONST, ShFracUByte, SH_NORMAL> ShConstNormal2fub;
typedef ShAttrib<3, SH_INPUT, ShFracUByte, SH_NORMAL> ShInputNormal3fub;
typedef ShAttrib<3, SH_OUTPUT, ShFracUByte, SH_NORMAL> ShOutputNormal3fub;
typedef ShAttrib<3, SH_INOUT, ShFracUByte, SH_NORMAL> ShInOutNormal3fub;
typedef ShAttrib<3, SH_TEMP, ShFracUByte, SH_NORMAL> ShNormal3fub;
typedef ShAttrib<3, SH_CONST, ShFracUByte, SH_NORMAL> ShConstNormal3fub;
typedef ShAttrib<4, SH_INPUT, ShFracUByte, SH_NORMAL> ShInputNormal4fub;
typedef ShAttrib<4, SH_OUTPUT, ShFracUByte, SH_NORMAL> ShOutputNormal4fub;
typedef ShAttrib<4, SH_INOUT, ShFracUByte, SH_NORMAL> ShInOutNormal4fub;
typedef ShAttrib<4, SH_TEMP, ShFracUByte, SH_NORMAL> ShNormal4fub;
typedef ShAttrib<4, SH_CONST, ShFracUByte, SH_NORMAL> ShConstNormal4fub;


typedef ShAttrib<1, SH_INPUT, ShHalf, SH_NORMAL> ShInputNormal1h;
typedef ShAttrib<1, SH_OUTPUT, ShHalf, SH_NORMAL> ShOutputNormal1h;
typedef ShAttrib<1, SH_INOUT, ShHalf, SH_NORMAL> ShInOutNormal1h;
typedef ShAttrib<1, SH_TEMP, ShHalf, SH_NORMAL> ShNormal1h;
typedef ShAttrib<1, SH_CONST, ShHalf, SH_NORMAL> ShConstNormal1h;
typedef ShAttrib<2, SH_INPUT, ShHalf, SH_NORMAL> ShInputNormal2h;
typedef ShAttrib<2, SH_OUTPUT, ShHalf, SH_NORMAL> ShOutputNormal2h;
typedef ShAttrib<2, SH_INOUT, ShHalf, SH_NORMAL> ShInOutNormal2h;
typedef ShAttrib<2, SH_TEMP, ShHalf, SH_NORMAL> ShNormal2h;
typedef ShAttrib<2, SH_CONST, ShHalf, SH_NORMAL> ShConstNormal2h;
typedef ShAttrib<3, SH_INPUT, ShHalf, SH_NORMAL> ShInputNormal3h;
typedef ShAttrib<3, SH_OUTPUT, ShHalf, SH_NORMAL> ShOutputNormal3h;
typedef ShAttrib<3, SH_INOUT, ShHalf, SH_NORMAL> ShInOutNormal3h;
typedef ShAttrib<3, SH_TEMP, ShHalf, SH_NORMAL> ShNormal3h;
typedef ShAttrib<3, SH_CONST, ShHalf, SH_NORMAL> ShConstNormal3h;
typedef ShAttrib<4, SH_INPUT, ShHalf, SH_NORMAL> ShInputNormal4h;
typedef ShAttrib<4, SH_OUTPUT, ShHalf, SH_NORMAL> ShOutputNormal4h;
typedef ShAttrib<4, SH_INOUT, ShHalf, SH_NORMAL> ShInOutNormal4h;
typedef ShAttrib<4, SH_TEMP, ShHalf, SH_NORMAL> ShNormal4h;
typedef ShAttrib<4, SH_CONST, ShHalf, SH_NORMAL> ShConstNormal4h;


typedef ShAttrib<1, SH_INPUT, ShFracShort, SH_NORMAL> ShInputNormal1fs;
typedef ShAttrib<1, SH_OUTPUT, ShFracShort, SH_NORMAL> ShOutputNormal1fs;
typedef ShAttrib<1, SH_INOUT, ShFracShort, SH_NORMAL> ShInOutNormal1fs;
typedef ShAttrib<1, SH_TEMP, ShFracShort, SH_NORMAL> ShNormal1fs;
typedef ShAttrib<1, SH_CONST, ShFracShort, SH_NORMAL> ShConstNormal1fs;
typedef ShAttrib<2, SH_INPUT, ShFracShort, SH_NORMAL> ShInputNormal2fs;
typedef ShAttrib<2, SH_OUTPUT, ShFracShort, SH_NORMAL> ShOutputNormal2fs;
typedef ShAttrib<2, SH_INOUT, ShFracShort, SH_NORMAL> ShInOutNormal2fs;
typedef ShAttrib<2, SH_TEMP, ShFracShort, SH_NORMAL> ShNormal2fs;
typedef ShAttrib<2, SH_CONST, ShFracShort, SH_NORMAL> ShConstNormal2fs;
typedef ShAttrib<3, SH_INPUT, ShFracShort, SH_NORMAL> ShInputNormal3fs;
typedef ShAttrib<3, SH_OUTPUT, ShFracShort, SH_NORMAL> ShOutputNormal3fs;
typedef ShAttrib<3, SH_INOUT, ShFracShort, SH_NORMAL> ShInOutNormal3fs;
typedef ShAttrib<3, SH_TEMP, ShFracShort, SH_NORMAL> ShNormal3fs;
typedef ShAttrib<3, SH_CONST, ShFracShort, SH_NORMAL> ShConstNormal3fs;
typedef ShAttrib<4, SH_INPUT, ShFracShort, SH_NORMAL> ShInputNormal4fs;
typedef ShAttrib<4, SH_OUTPUT, ShFracShort, SH_NORMAL> ShOutputNormal4fs;
typedef ShAttrib<4, SH_INOUT, ShFracShort, SH_NORMAL> ShInOutNormal4fs;
typedef ShAttrib<4, SH_TEMP, ShFracShort, SH_NORMAL> ShNormal4fs;
typedef ShAttrib<4, SH_CONST, ShFracShort, SH_NORMAL> ShConstNormal4fs;


typedef ShAttrib<1, SH_INPUT, ShFracInt, SH_NORMAL> ShInputNormal1fi;
typedef ShAttrib<1, SH_OUTPUT, ShFracInt, SH_NORMAL> ShOutputNormal1fi;
typedef ShAttrib<1, SH_INOUT, ShFracInt, SH_NORMAL> ShInOutNormal1fi;
typedef ShAttrib<1, SH_TEMP, ShFracInt, SH_NORMAL> ShNormal1fi;
typedef ShAttrib<1, SH_CONST, ShFracInt, SH_NORMAL> ShConstNormal1fi;
typedef ShAttrib<2, SH_INPUT, ShFracInt, SH_NORMAL> ShInputNormal2fi;
typedef ShAttrib<2, SH_OUTPUT, ShFracInt, SH_NORMAL> ShOutputNormal2fi;
typedef ShAttrib<2, SH_INOUT, ShFracInt, SH_NORMAL> ShInOutNormal2fi;
typedef ShAttrib<2, SH_TEMP, ShFracInt, SH_NORMAL> ShNormal2fi;
typedef ShAttrib<2, SH_CONST, ShFracInt, SH_NORMAL> ShConstNormal2fi;
typedef ShAttrib<3, SH_INPUT, ShFracInt, SH_NORMAL> ShInputNormal3fi;
typedef ShAttrib<3, SH_OUTPUT, ShFracInt, SH_NORMAL> ShOutputNormal3fi;
typedef ShAttrib<3, SH_INOUT, ShFracInt, SH_NORMAL> ShInOutNormal3fi;
typedef ShAttrib<3, SH_TEMP, ShFracInt, SH_NORMAL> ShNormal3fi;
typedef ShAttrib<3, SH_CONST, ShFracInt, SH_NORMAL> ShConstNormal3fi;
typedef ShAttrib<4, SH_INPUT, ShFracInt, SH_NORMAL> ShInputNormal4fi;
typedef ShAttrib<4, SH_OUTPUT, ShFracInt, SH_NORMAL> ShOutputNormal4fi;
typedef ShAttrib<4, SH_INOUT, ShFracInt, SH_NORMAL> ShInOutNormal4fi;
typedef ShAttrib<4, SH_TEMP, ShFracInt, SH_NORMAL> ShNormal4fi;
typedef ShAttrib<4, SH_CONST, ShFracInt, SH_NORMAL> ShConstNormal4fi;


typedef ShAttrib<1, SH_INPUT, unsigned int, SH_NORMAL> ShInputNormal1ui;
typedef ShAttrib<1, SH_OUTPUT, unsigned int, SH_NORMAL> ShOutputNormal1ui;
typedef ShAttrib<1, SH_INOUT, unsigned int, SH_NORMAL> ShInOutNormal1ui;
typedef ShAttrib<1, SH_TEMP, unsigned int, SH_NORMAL> ShNormal1ui;
typedef ShAttrib<1, SH_CONST, unsigned int, SH_NORMAL> ShConstNormal1ui;
typedef ShAttrib<2, SH_INPUT, unsigned int, SH_NORMAL> ShInputNormal2ui;
typedef ShAttrib<2, SH_OUTPUT, unsigned int, SH_NORMAL> ShOutputNormal2ui;
typedef ShAttrib<2, SH_INOUT, unsigned int, SH_NORMAL> ShInOutNormal2ui;
typedef ShAttrib<2, SH_TEMP, unsigned int, SH_NORMAL> ShNormal2ui;
typedef ShAttrib<2, SH_CONST, unsigned int, SH_NORMAL> ShConstNormal2ui;
typedef ShAttrib<3, SH_INPUT, unsigned int, SH_NORMAL> ShInputNormal3ui;
typedef ShAttrib<3, SH_OUTPUT, unsigned int, SH_NORMAL> ShOutputNormal3ui;
typedef ShAttrib<3, SH_INOUT, unsigned int, SH_NORMAL> ShInOutNormal3ui;
typedef ShAttrib<3, SH_TEMP, unsigned int, SH_NORMAL> ShNormal3ui;
typedef ShAttrib<3, SH_CONST, unsigned int, SH_NORMAL> ShConstNormal3ui;
typedef ShAttrib<4, SH_INPUT, unsigned int, SH_NORMAL> ShInputNormal4ui;
typedef ShAttrib<4, SH_OUTPUT, unsigned int, SH_NORMAL> ShOutputNormal4ui;
typedef ShAttrib<4, SH_INOUT, unsigned int, SH_NORMAL> ShInOutNormal4ui;
typedef ShAttrib<4, SH_TEMP, unsigned int, SH_NORMAL> ShNormal4ui;
typedef ShAttrib<4, SH_CONST, unsigned int, SH_NORMAL> ShConstNormal4ui;



} // namespace SH

#endif // SH_SHNORMAL_HPP
