// WARNING - DO NOT EDIT THIS FILE:
// This file was automatically generated from scripts/ShTexCoord.hpp.py.
// If you wish to change it, edit that file instead.
//
// ---
//
// Sh: A GPU metaprogramming language.
//
// Copyright (c) 2003 University of Waterloo Computer Graphics Laboratory
// Project administrator: Michael D. McCool
// Authors: Zheng Qin, Stefanus Du Toit, Kevin Moule, Tiberiu S. Popa,
//          Michael D. McCool
//
// This software is provided 'as-is', without any express or implied
// warranty. In no event will the authors be held liable for any damages
// arising from the use of this software.
//
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it
// freely, subject to the following restrictions:
//
// 1. The origin of this software must not be misrepresented; you must
// not claim that you wrote the original software. If you use this
// software in a product, an acknowledgment in the product documentation
// would be appreciated but is not required.
//
// 2. Altered source versions must be plainly marked as such, and must
// not be misrepresented as being the original software.
//
// 3. This notice may not be removed or altered from any source
// distribution.
//////////////////////////////////////////////////////////////////////////////

#ifndef SH_SHTEXCOORD_HPP
#define SH_SHTEXCOORD_HPP

#include "ShAttrib.hpp"
namespace SH {

/** A texture coordinate.
 * 
 *
 */
template<int N, ShBindingType Binding, typename T=float, bool Swizzled=false>
class ShTexCoord : public ShAttrib<N, Binding, T, Swizzled> {
public:
  ShTexCoord();
  ShTexCoord(const ShGeneric<N, T>& other);
  ShTexCoord(const ShTexCoord<N, Binding, T, Swizzled>& other);
  ShTexCoord(const ShVariableNodePtr& node, const ShSwizzle& swizzle, bool neg);
  explicit ShTexCoord(T data[N]);
  
  ~ShTexCoord();

  ShTexCoord& operator=(const ShGeneric<N, T>& other);
  ShTexCoord& operator=(const ShTexCoord<N, Binding, T, Swizzled>& other);

  ShTexCoord& operator+=(const ShGeneric<N, T>& right);
  ShTexCoord& operator-=(const ShGeneric<N, T>& right);
  ShTexCoord& operator*=(const ShGeneric<N, T>& right);
  ShTexCoord& operator/=(const ShGeneric<N, T>& right);
  ShTexCoord& operator*=(T);
  ShTexCoord& operator/=(T);
  ShTexCoord& operator*=(const ShGeneric<1, T>&);
  ShTexCoord& operator/=(const ShGeneric<1, T>&);
  ShTexCoord<1, Binding, T, true> operator()(int) const;
  ShTexCoord<2, Binding, T, true> operator()(int, int) const;
  ShTexCoord<3, Binding, T, true> operator()(int, int, int) const;
  ShTexCoord<4, Binding, T, true> operator()(int, int, int, int) const;
  ShTexCoord<1, Binding, T, true> operator[](int) const;
  
  template<int N2>
  ShTexCoord<N2, Binding, T, true> swiz(int indices[]) const;
  
  ShTexCoord operator-() const;
  typedef T ValueType;
  static const int typesize = N;
  static const ShBindingType binding_type = Binding;
  static const ShSemanticType semantic_type = SH_TEXCOORD;

  typedef ShTexCoord<N, SH_INPUT, T> InputType;
  typedef ShTexCoord<N, SH_OUTPUT, T> OutputType;
  typedef ShTexCoord<N, SH_INOUT, T> InOutType;
  typedef ShTexCoord<N, SH_TEMP, T> TempType;
  typedef ShTexCoord<N, SH_CONST, T> ConstType;
private:
  typedef ShAttrib<N, Binding, T, Swizzled> ParentType;
};

template<ShBindingType Binding, typename T, bool Swizzled>
class ShTexCoord<1, Binding, T, Swizzled> : public ShAttrib<1, Binding, T, Swizzled> {
public:
  ShTexCoord();
  ShTexCoord(const ShGeneric<1, T>& other);
  ShTexCoord(const ShTexCoord<1, Binding, T, Swizzled>& other);
  ShTexCoord(const ShVariableNodePtr& node, const ShSwizzle& swizzle, bool neg);
  explicit ShTexCoord(T data[1]);
  
  ShTexCoord(T);
  
  ~ShTexCoord();

  ShTexCoord& operator=(const ShGeneric<1, T>& other);
  ShTexCoord& operator=(const ShTexCoord<1, Binding, T, Swizzled>& other);

  ShTexCoord& operator+=(const ShGeneric<1, T>& right);
  ShTexCoord& operator-=(const ShGeneric<1, T>& right);
  ShTexCoord& operator*=(const ShGeneric<1, T>& right);
  ShTexCoord& operator/=(const ShGeneric<1, T>& right);
  ShTexCoord& operator*=(T);
  ShTexCoord& operator/=(T);
  ShTexCoord& operator+=(T);
  ShTexCoord& operator-=(T);
  ShTexCoord<1, Binding, T, true> operator()(int) const;
  ShTexCoord<2, Binding, T, true> operator()(int, int) const;
  ShTexCoord<3, Binding, T, true> operator()(int, int, int) const;
  ShTexCoord<4, Binding, T, true> operator()(int, int, int, int) const;
  ShTexCoord<1, Binding, T, true> operator[](int) const;
  
  template<int N2>
  ShTexCoord<N2, Binding, T, true> swiz(int indices[]) const;
  
  ShTexCoord operator-() const;
  typedef T ValueType;
  static const int typesize = 1;
  static const ShBindingType binding_type = Binding;
  static const ShSemanticType semantic_type = SH_TEXCOORD;

  typedef ShTexCoord<1, SH_INPUT, T> InputType;
  typedef ShTexCoord<1, SH_OUTPUT, T> OutputType;
  typedef ShTexCoord<1, SH_INOUT, T> InOutType;
  typedef ShTexCoord<1, SH_TEMP, T> TempType;
  typedef ShTexCoord<1, SH_CONST, T> ConstType;
private:
  typedef ShAttrib<1, Binding, T, Swizzled> ParentType;
};

template<ShBindingType Binding, typename T, bool Swizzled>
class ShTexCoord<2, Binding, T, Swizzled> : public ShAttrib<2, Binding, T, Swizzled> {
public:
  ShTexCoord();
  ShTexCoord(const ShGeneric<2, T>& other);
  ShTexCoord(const ShTexCoord<2, Binding, T, Swizzled>& other);
  ShTexCoord(const ShVariableNodePtr& node, const ShSwizzle& swizzle, bool neg);
  explicit ShTexCoord(T data[2]);
  
  ShTexCoord(T, T);
  ShTexCoord(const ShGeneric<1, T>&, const ShGeneric<1, T>&);
  
  ~ShTexCoord();

  ShTexCoord& operator=(const ShGeneric<2, T>& other);
  ShTexCoord& operator=(const ShTexCoord<2, Binding, T, Swizzled>& other);

  ShTexCoord& operator+=(const ShGeneric<2, T>& right);
  ShTexCoord& operator-=(const ShGeneric<2, T>& right);
  ShTexCoord& operator*=(const ShGeneric<2, T>& right);
  ShTexCoord& operator/=(const ShGeneric<2, T>& right);
  ShTexCoord& operator*=(T);
  ShTexCoord& operator/=(T);
  ShTexCoord& operator*=(const ShGeneric<1, T>&);
  ShTexCoord& operator/=(const ShGeneric<1, T>&);
  ShTexCoord<1, Binding, T, true> operator()(int) const;
  ShTexCoord<2, Binding, T, true> operator()(int, int) const;
  ShTexCoord<3, Binding, T, true> operator()(int, int, int) const;
  ShTexCoord<4, Binding, T, true> operator()(int, int, int, int) const;
  ShTexCoord<1, Binding, T, true> operator[](int) const;
  
  template<int N2>
  ShTexCoord<N2, Binding, T, true> swiz(int indices[]) const;
  
  ShTexCoord operator-() const;
  typedef T ValueType;
  static const int typesize = 2;
  static const ShBindingType binding_type = Binding;
  static const ShSemanticType semantic_type = SH_TEXCOORD;

  typedef ShTexCoord<2, SH_INPUT, T> InputType;
  typedef ShTexCoord<2, SH_OUTPUT, T> OutputType;
  typedef ShTexCoord<2, SH_INOUT, T> InOutType;
  typedef ShTexCoord<2, SH_TEMP, T> TempType;
  typedef ShTexCoord<2, SH_CONST, T> ConstType;
private:
  typedef ShAttrib<2, Binding, T, Swizzled> ParentType;
};

template<ShBindingType Binding, typename T, bool Swizzled>
class ShTexCoord<3, Binding, T, Swizzled> : public ShAttrib<3, Binding, T, Swizzled> {
public:
  ShTexCoord();
  ShTexCoord(const ShGeneric<3, T>& other);
  ShTexCoord(const ShTexCoord<3, Binding, T, Swizzled>& other);
  ShTexCoord(const ShVariableNodePtr& node, const ShSwizzle& swizzle, bool neg);
  explicit ShTexCoord(T data[3]);
  
  ShTexCoord(T, T, T);
  ShTexCoord(const ShGeneric<1, T>&, const ShGeneric<1, T>&, const ShGeneric<1, T>&);
  
  ~ShTexCoord();

  ShTexCoord& operator=(const ShGeneric<3, T>& other);
  ShTexCoord& operator=(const ShTexCoord<3, Binding, T, Swizzled>& other);

  ShTexCoord& operator+=(const ShGeneric<3, T>& right);
  ShTexCoord& operator-=(const ShGeneric<3, T>& right);
  ShTexCoord& operator*=(const ShGeneric<3, T>& right);
  ShTexCoord& operator/=(const ShGeneric<3, T>& right);
  ShTexCoord& operator*=(T);
  ShTexCoord& operator/=(T);
  ShTexCoord& operator*=(const ShGeneric<1, T>&);
  ShTexCoord& operator/=(const ShGeneric<1, T>&);
  ShTexCoord<1, Binding, T, true> operator()(int) const;
  ShTexCoord<2, Binding, T, true> operator()(int, int) const;
  ShTexCoord<3, Binding, T, true> operator()(int, int, int) const;
  ShTexCoord<4, Binding, T, true> operator()(int, int, int, int) const;
  ShTexCoord<1, Binding, T, true> operator[](int) const;
  
  template<int N2>
  ShTexCoord<N2, Binding, T, true> swiz(int indices[]) const;
  
  ShTexCoord operator-() const;
  typedef T ValueType;
  static const int typesize = 3;
  static const ShBindingType binding_type = Binding;
  static const ShSemanticType semantic_type = SH_TEXCOORD;

  typedef ShTexCoord<3, SH_INPUT, T> InputType;
  typedef ShTexCoord<3, SH_OUTPUT, T> OutputType;
  typedef ShTexCoord<3, SH_INOUT, T> InOutType;
  typedef ShTexCoord<3, SH_TEMP, T> TempType;
  typedef ShTexCoord<3, SH_CONST, T> ConstType;
private:
  typedef ShAttrib<3, Binding, T, Swizzled> ParentType;
};

template<ShBindingType Binding, typename T, bool Swizzled>
class ShTexCoord<4, Binding, T, Swizzled> : public ShAttrib<4, Binding, T, Swizzled> {
public:
  ShTexCoord();
  ShTexCoord(const ShGeneric<4, T>& other);
  ShTexCoord(const ShTexCoord<4, Binding, T, Swizzled>& other);
  ShTexCoord(const ShVariableNodePtr& node, const ShSwizzle& swizzle, bool neg);
  explicit ShTexCoord(T data[4]);
  
  ShTexCoord(T, T, T, T);
  ShTexCoord(const ShGeneric<1, T>&, const ShGeneric<1, T>&, const ShGeneric<1, T>&, const ShGeneric<1, T>&);
  
  ~ShTexCoord();

  ShTexCoord& operator=(const ShGeneric<4, T>& other);
  ShTexCoord& operator=(const ShTexCoord<4, Binding, T, Swizzled>& other);

  ShTexCoord& operator+=(const ShGeneric<4, T>& right);
  ShTexCoord& operator-=(const ShGeneric<4, T>& right);
  ShTexCoord& operator*=(const ShGeneric<4, T>& right);
  ShTexCoord& operator/=(const ShGeneric<4, T>& right);
  ShTexCoord& operator*=(T);
  ShTexCoord& operator/=(T);
  ShTexCoord& operator*=(const ShGeneric<1, T>&);
  ShTexCoord& operator/=(const ShGeneric<1, T>&);
  ShTexCoord<1, Binding, T, true> operator()(int) const;
  ShTexCoord<2, Binding, T, true> operator()(int, int) const;
  ShTexCoord<3, Binding, T, true> operator()(int, int, int) const;
  ShTexCoord<4, Binding, T, true> operator()(int, int, int, int) const;
  ShTexCoord<1, Binding, T, true> operator[](int) const;
  
  template<int N2>
  ShTexCoord<N2, Binding, T, true> swiz(int indices[]) const;
  
  ShTexCoord operator-() const;
  typedef T ValueType;
  static const int typesize = 4;
  static const ShBindingType binding_type = Binding;
  static const ShSemanticType semantic_type = SH_TEXCOORD;

  typedef ShTexCoord<4, SH_INPUT, T> InputType;
  typedef ShTexCoord<4, SH_OUTPUT, T> OutputType;
  typedef ShTexCoord<4, SH_INOUT, T> InOutType;
  typedef ShTexCoord<4, SH_TEMP, T> TempType;
  typedef ShTexCoord<4, SH_CONST, T> ConstType;
private:
  typedef ShAttrib<4, Binding, T, Swizzled> ParentType;
};

typedef ShTexCoord<1, SH_INPUT, float> ShInputTexCoord1f;
typedef ShTexCoord<1, SH_OUTPUT, float> ShOutputTexCoord1f;
typedef ShTexCoord<1, SH_INOUT, float> ShInOutTexCoord1f;
typedef ShTexCoord<1, SH_TEMP, float> ShTexCoord1f;
typedef ShTexCoord<1, SH_CONST, float> ShConstTexCoord1f;
typedef ShTexCoord<2, SH_INPUT, float> ShInputTexCoord2f;
typedef ShTexCoord<2, SH_OUTPUT, float> ShOutputTexCoord2f;
typedef ShTexCoord<2, SH_INOUT, float> ShInOutTexCoord2f;
typedef ShTexCoord<2, SH_TEMP, float> ShTexCoord2f;
typedef ShTexCoord<2, SH_CONST, float> ShConstTexCoord2f;
typedef ShTexCoord<3, SH_INPUT, float> ShInputTexCoord3f;
typedef ShTexCoord<3, SH_OUTPUT, float> ShOutputTexCoord3f;
typedef ShTexCoord<3, SH_INOUT, float> ShInOutTexCoord3f;
typedef ShTexCoord<3, SH_TEMP, float> ShTexCoord3f;
typedef ShTexCoord<3, SH_CONST, float> ShConstTexCoord3f;
typedef ShTexCoord<4, SH_INPUT, float> ShInputTexCoord4f;
typedef ShTexCoord<4, SH_OUTPUT, float> ShOutputTexCoord4f;
typedef ShTexCoord<4, SH_INOUT, float> ShInOutTexCoord4f;
typedef ShTexCoord<4, SH_TEMP, float> ShTexCoord4f;
typedef ShTexCoord<4, SH_CONST, float> ShConstTexCoord4f;

} // namespace SH
#include "ShTexCoordImpl.hpp"

#endif // SH_SHTEXCOORD_HPP
